### ISSUE TITLE
#3 - Join: Update Name Labels on the Personal info page

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#104]
Change 'Preferred Name' to 'Preferred First Name' 
Change 'First Name' To 'Legal First Name'

**Comment by staciejurczak** [comment]
@suehamre confirming Jen Wise will work on this ticket.

**Comment by suehamre** [comment]
8-17 SH - 
![image](https://user-images.githubusercontent.com/57115316/90412168-61355480-e072-11ea-83ac-0c3f054cbc11.png)
