### ISSUE TITLE
#6 Join: Add new styling to selected consultant

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#107]
Update the styling to what is displayed below when the consultant is selected: 

![image](https://user-images.githubusercontent.com/57115316/80651597-cc173d00-8a3b-11ea-9e95-d5e67a20e525.png)

**Comment by staciejurczak** [comment]
Ticket:  https://razoyo.atlassian.net/browse/TST-183

**Comment by wbyrnetx** [comment]
Looks good to us:
![Screen Shot 2020-08-27 at 9 42 35 AM](https://user-images.githubusercontent.com/4029452/91460392-bf71ec80-e855-11ea-8567-63cf77ba1818.png)

**Comment by monicakarnes** [comment]
need Bug #299 fixed 1st

**Comment by monicakarnes** [comment]
bug # 299 was fixed..... 

and here is what I see now 
![image](https://user-images.githubusercontent.com/57115301/91491032-0e7d4900-e879-11ea-889f-bcc948f7376b.png)

closing- bug #107
