### ISSUE TITLE
#5 Join: Personal Info Page: Flip flop zip code and State

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#108]
In the billing and shipping address info, we would like the zip code and state to be flip flopped. If zip code is entered first the state auto populates. 
![image](https://user-images.githubusercontent.com/57115316/80651822-37f9a580-8a3c-11ea-919d-bc0755407252.png)

**Comment by staciejurczak** [comment]
I am making this recommendation in the ticket to see if option below is possible on in this section.  It uses the space better and connects the autopopulate side by side 
![image](https://user-images.githubusercontent.com/65304780/91206770-4a73ab00-e6cd-11ea-92de-a079cb403664.png)

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-182
![image](https://user-images.githubusercontent.com/65304780/91210354-b3115680-e6d2-11ea-8142-8be065e11747.png)

**Comment by mandi920** [comment]
This is accounted for on the backlog.
