### ISSUE TITLE
#2 Join: Personal Info Page - Add State error message 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#110]
On the join personal information page we need to add an error message stopping the user if they have not chosen their state and tried to continue. Right now they are being allowed to continue without selecting their state. Therefore, once their cons agreement is processed through Ice injection and Prowess the system is auto selecting the first state available as Alabama. 
NOTE: The shipping address on the orders are correct because their is address verification and they cannot continue without selecting a state.

**Comment by TastefullySimple** [comment]
Please retest.

**Comment by suehamre** [comment]
8-12 SH - Retested, this is still an issue. I was able to continue without selecting my state.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-178](https://razoyo.atlassian.net/browse/TST-178)

**Comment by wbyrnetx** [comment]
This passed our QA on Tech Sandbox.

**Comment by suehamre** [comment]
8-25 SH  - Received error message now to enter select state. :) 
![image](https://user-images.githubusercontent.com/57115316/91202036-da622680-e6c6-11ea-8665-cc44d993aefb.png)
