### ISSUE TITLE
Credit- Order Listing & Order Listing Details are Displaying incorrect on Order Level Refund

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#111]
### Expected behavior
Totals should display correctly on the Order Listing and Order Listing Details page after a credit has been used. 

### Actual behavior
There should be no Part 3 listed for this refund on the Order Listing page it should display at $0.00 as no item was credited back only the shipping charges. 

![image](https://user-images.githubusercontent.com/57115301/81234113-be266680-8fbd-11ea-926c-a5ee82ff85f5.png)

Once you open the Order Listing Details for the order you can see that the P3 total again is showing $9.99 and should be $0.00 then Subtotal here is also showing at $9.99 and should also be $0.00

This also makes my Total refund amount off it is displaying ($16.98) but should be ($6.99) 

![image](https://user-images.githubusercontent.com/57115301/81234304-207f6700-8fbe-11ea-9627-2baff901136e.png)

**Comment by sevincent** [comment]
Picking up the placed price from the original line one.. Let's try it again...

**Comment by monicakarnes** [comment]
Looks like this is correct for order listing 
![image](https://user-images.githubusercontent.com/57115301/81352231-a9b09f80-908b-11ea-9eb1-91e52a1aa7fd.png)

This also now looks better.
![image](https://user-images.githubusercontent.com/57115301/81352316-d6fd4d80-908b-11ea-869f-12b599cc6479.png)

And it gave back, tax, as I said it should have when I ran the proc. 
So closing this bug.
