### ISSUE TITLE
Join: UI issue on android tablets

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#112]
Per Jen @ Razayo - there is an issue on Android tablets on the join path. The page is scrunched to the left. I don't have a screen shot at this time.

**Comment by TastefullySimple** [comment]
Please retest with browserstack.

**Comment by suehamre** [comment]
8-17 SH - Tested using browser stack, Galaxy Tablets S6 and S5, pages looked fine. Closing bug.
