### ISSUE TITLE
Style Guide- Duplicate Color listed 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#113]
Looks like there is a duplicate color of Grape # 56C125  listed that should be removed. 

https://tastefully-simple-sandbox-2.mybigcommerce.com/styleguide/

![image](https://user-images.githubusercontent.com/57115301/81439199-9ce78680-9133-11ea-8fd3-c8c35d12b0eb.png)

![image](https://user-images.githubusercontent.com/57115301/81439226-a7a21b80-9133-11ea-9e20-b31f68759bd4.png)

I have checked with Marketing : 
From: Rebecca Rausch <rebecca.rausch@tastefullysimple.com> 
Sent: Friday, May 8, 2020 1:47 PM
To: Monica Karnes <Monica.Karnes@TastefullySimple.com>
Subject: RE: Style Guide question on color??? looks like maybe a duplicate?

Hi Monica,

I’m guessing it was just a duplicate made – they look the exact same. 😊 
It should stay in the primary section. The other one below by the grays should probably just be deleted.
Rebecca

Action needed : 
Please remove  Grape # 56C125 from the Secondary Colors section

**Comment by TastefullySimple** [comment]
fixed

**Comment by monicakarnes** [comment]
checked, this has been fixed, closing bug
