### ISSUE TITLE
Credit- Partial order Credit- P1 Retail total displays wrong on Order Listing, and Order Details 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#115]
### Expected behavior
Totals should be correct upon doing credit for partial credit order

### Actual behavior
Original order BC 670 - issued credit back for 1 of the 2 kits ordered, also refunded tax, but no shipping. 

Order Details page  my P1 Retail total displays at ($299.98) and it should be only ($149.99)  as I only am crediting back one of the kits.  
![image](https://user-images.githubusercontent.com/57115301/81861381-c3d7fb00-952d-11ea-9e1e-355f2639c9cd.png)
 

Order Listing also displays incorrectly for the P1 Retail and the Total are showing incorrectly 
![image](https://user-images.githubusercontent.com/57115301/81861526-ff72c500-952d-11ea-8357-d77944631408.png)
 Should be P1 of ($149.99) and total of  ($151.49)

**Comment by sevincent** [comment]
The quantity on the original order is wrong, which is throwing everything off. There was a bug in flattener that caused the order quantity to be wrong. I fixed that last month, but didn’t go back and fix the data. Try a fresh order and I should tie out.

**Comment by monicakarnes** [comment]
retested- with new order- and its fixed 
![image](https://user-images.githubusercontent.com/57115301/82092038-1a743f00-96be-11ea-88ea-64311dc45df0.png)


![image](https://user-images.githubusercontent.com/57115301/82092084-31b32c80-96be-11ea-906d-f316aafb7832.png)
