### ISSUE TITLE
Credit- Exploding Kit item placed on Big Commerce not being sent

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#117]
Exploding Kit (Item #101248 – The Essential Four )  is being placed on Big Commerce and is failing being sent to Softeon due to parent item number being sent vs the child items. 
This need to explode so it will be sent to Softeon correctly 
![image](https://user-images.githubusercontent.com/57115301/82265308-4dbc0580-992c-11ea-81a1-2a9678a136ea.png)

![image](https://user-images.githubusercontent.com/57115301/82265237-22391b00-992c-11ea-8b95-9daed7df0d72.png)

![image](https://user-images.githubusercontent.com/57115301/82265255-2f560a00-992c-11ea-978b-b50e69b47915.png)

![image](https://user-images.githubusercontent.com/57115301/82265277-3da42600-992c-11ea-80e6-8983403ef3d7.png)

**Comment by sevincent** [comment]
Corrected problem with Entity Framework mapping for ExplodingKit in Line Item.

**Comment by monicakarnes** [comment]
placed new order today 26931749 - and still is failing- :(
![image](https://user-images.githubusercontent.com/57115301/82474459-b58b6100-9a90-11ea-8949-2aa7d71b6df2.png)


![image](https://user-images.githubusercontent.com/57115301/82474504-c2a85000-9a90-11ea-802f-23012b15186b.png)


![image](https://user-images.githubusercontent.com/57115301/82474558-d05dd580-9a90-11ea-9bd3-4c4d60fef633.png)

**Comment by sevincent** [comment]
Changed ValidateExternalOrderJob to set component item LineItemStatus to shipable (8) not zero.

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/82615925-49dced00-9b91-11ea-81c2-a77ec6569e4a.png)

![image](https://user-images.githubusercontent.com/57115301/82615943-56f9dc00-9b91-11ea-9908-e2d73350376f.png)

Its there, closing bug
