### ISSUE TITLE
Credit- Promo Code- P1 Non Commissionable & Client Promotion Discount

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#121]
Cons # 160785
Original BC order #726 
![image](https://user-images.githubusercontent.com/57115301/82944213-69449300-9f60-11ea-8fa2-cd2f1e6a6b6b.png)

MyHQ Order# 26929034
Looks like this is incorrect on the original order going into myhq  as my promo code was for $15.00 
![image](https://user-images.githubusercontent.com/57115301/82944115-431ef300-9f60-11ea-895a-e4688b3002df.png)

Credit order 26932831 shows up incorrectly as well... 
![image](https://user-images.githubusercontent.com/57115301/82944052-2be00580-9f60-11ea-9653-86b5d37d4997.png)

Here is a production example Cons# 170754  original order 28742942
![image](https://user-images.githubusercontent.com/57115301/82944356-aad53e00-9f60-11ea-8bb3-e51c11c0efa3.png)

If you try to do a credit you only see the credit promo price per line. 
![image](https://user-images.githubusercontent.com/57115301/82944410-c50f1c00-9f60-11ea-84f0-e3f5bf0dc0cb.png)

**Comment by sevincent** [comment]
Changed the calcullation for TotalDiscount and TotalDiscountdollarValue in ValidateExternalOrderJob.

**Comment by monicakarnes** [comment]
This is still incorrect... 
My original order discount for my Promo code is coming over wrong  the P1 Retail Non Commission able on the order and Client Promotion Discount should only be for $15.00 It looks like it doubled, its displaying at $30.00
![image](https://user-images.githubusercontent.com/57115301/83204157-c1ba9280-a110-11ea-8ceb-1271bd43fe77.png)

So when I then went to do the credit again,  it displayed incorrectly again. 
![image](https://user-images.githubusercontent.com/57115301/83204386-58874f00-a111-11ea-93ad-4bc30cb5ad28.png)

The the P1 Retail Non Commission this order should be I believe on this one should actually be ($7.50) and the client Promotion should be the same ($7.50)   **This is half of the original $15 as there was only 2 items on the original order**

So that would make the P1 total $2.49 and the $0.17 for tax with the refund total of $2.66 Which is what it showed me for the refund total in Big Commerce. 

![image](https://user-images.githubusercontent.com/57115301/83205999-99816280-a115-11ea-9622-b7ba40e8121c.png)

**Comment by sevincent** [comment]
Needed to do a fresh order to see the fix. Ran a fresh order like it (#737) and P1 Non-com and discount looked better. Other stuff looked wrong. Deployed changes to fix OrderTotal and DiscountDollarValue.

**Comment by monicakarnes** [comment]
Did Fresh order BC # 740 

When I issued credit back via BC here is my summary- 
![image](https://user-images.githubusercontent.com/57115301/83452162-d8692e00-a41d-11ea-86c8-75aaa5b801bf.png)


 My HQ.....This is still a mess.... 


The P1 Retail- ($2.49 is correct) 
**P1 Retail Non-Commissionable is wrong** it should be ($7.50) (this is because 2 items were ordered and the discount was for $15.00 so its divided per line) 
**The Client Promotion Discount**  is wrong it again should match showing ($7.50)(as this is only for this one item that is credited back on this one line) 
**The P1 SubTotal is wrong**- should be same as above for ($2.49) 
Total P2 items- correct 
Total P3 items- correct
**SubTotal is  wrong-** should be same as other P1- ($2.49) 
Tax is correct at what I entered ($0.08) 
Shipping is correct (partial credit order so no shipping) 
Shipping discount is correct there wasn't one so none to give back
**Total is  wrong** - it should be ( $2.57)

$2.49 + $0.08 = ($2.57)  
![image](https://user-images.githubusercontent.com/57115301/83452438-4f062b80-a41e-11ea-9ce9-4557d2ae7588.png)

**Comment by sevincent** [comment]
Partly was that I hadn't pushed my last round of validator changes when order #740 was entered. Corrected AdjustedPartOneTotal logic in uspI_CreateCreditOrderForExternal

**Comment by monicakarnes** [comment]
These are still wrong in the order details see highlights
![image](https://user-images.githubusercontent.com/57115301/83578660-f9548080-a4fc-11ea-8750-e60865b03140.png)

This is almost right it should be P1 of 2.49  maybe thats part of the problem? 
![image](https://user-images.githubusercontent.com/57115301/83579229-50a72080-a4fe-11ea-8afd-53c2deb0ac10.png)

**Comment by monicakarnes** [comment]
Here is my example from Prod... these hightlights match up
![image](https://user-images.githubusercontent.com/57115301/83579372-b1365d80-a4fe-11ea-9338-56b0f2e54efd.png)

As does the order listing page
![image](https://user-images.githubusercontent.com/57115301/83579398-c4e1c400-a4fe-11ea-807b-29eb62fdc027.png)

**Comment by monicakarnes** [comment]
Redo on order # 787, aka # 26949288 
![image](https://user-images.githubusercontent.com/57115301/86619529-6043da00-bf80-11ea-8e6c-fcd520b245be.png)

Discounts look right now on the credit order 
![image](https://user-images.githubusercontent.com/57115301/86619576-7e113f00-bf80-11ea-9a3e-815e3c80a4f7.png)

Closing bug
