### ISSUE TITLE
Credit - Join Credit Refund order not showing up in myHQ 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#122]
New consultant ID 188892 Ron Burgundy

TSN- I can see the original order- 26929045 and the Credit order 26931933 
![image](https://user-images.githubusercontent.com/57115301/82945968-2afca300-9f63-11ea-81d7-31c5b095855f.png)

In BC you can see the original order 729 and see that I refunded it... 
![image](https://user-images.githubusercontent.com/57115301/82946045-4bc4f880-9f63-11ea-94de-3cdb2455f42d.png)

myHQ I see the original order listed but not the credit order and I should see that as well. 
![image](https://user-images.githubusercontent.com/57115301/82946093-6303e600-9f63-11ea-827b-be1e6c788be4.png)

**Comment by sevincent** [comment]
Added additional order type, user type and listing type mappings to the database. View uvw_OrderListingSummary returns the order now.

**Comment by monicakarnes** [comment]
Sorry I'm still not seeing this appear in myHQ and I even re-ran it

![image](https://user-images.githubusercontent.com/57115301/83202156-9b92f380-a10c-11ea-98ce-586e7a0eee60.png)

I re- ran the sql script and it created in the table 
![image](https://user-images.githubusercontent.com/57115301/83202208-bb2a1c00-a10c-11ea-9e0b-e653c5b343a1.png)

 And I can see that it created a new credit order in TNS, but again it also needs to flow over to myHQ

![image](https://user-images.githubusercontent.com/57115301/83202295-e9a7f700-a10c-11ea-96ec-ba2bed2e8640.png)

**Comment by sevincent** [comment]
Added a mapping to DimListingTypeMapping. I can see them both now,

**Comment by monicakarnes** [comment]
Here we go! 
![image](https://user-images.githubusercontent.com/57115301/83645992-b801b680-a578-11ea-9682-31340cb5d0fb.png)

Yeah! 
![image](https://user-images.githubusercontent.com/57115301/83646050-c8b22c80-a578-11ea-9c92-db549f93382c.png)

Nice!
![image](https://user-images.githubusercontent.com/57115301/83646185-f0a19000-a578-11ea-8a11-df39c6550e01.png)

Wahoo! 
![image](https://user-images.githubusercontent.com/57115301/83646486-4f670980-a579-11ea-976b-e215359f0c28.png)

Closing bug!
