### ISSUE TITLE
Credit- Multiple Line Credit- Created multiple Credit orders one for each line that was credited back 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#123]
BC order 724
![image](https://user-images.githubusercontent.com/57115301/82956651-de22c780-9f76-11ea-959f-70b8bc948423.png)

Myhq Order # 26929028 
![image](https://user-images.githubusercontent.com/57115301/82956732-0c080c00-9f77-11ea-9150-f778529a36ff.png)

Issued Credit back... seen via myhq I see 2 credit orders created
![image](https://user-images.githubusercontent.com/57115301/82956800-34900600-9f77-11ea-9ecb-db6a2bcb3556.png)

26935340
![image](https://user-images.githubusercontent.com/57115301/82956831-4a9dc680-9f77-11ea-8fcc-07bf03dae980.png)

26935341 
![image](https://user-images.githubusercontent.com/57115301/82956857-5a1d0f80-9f77-11ea-8b23-b7ec8b4d02e8.png)

It should be like this to match BC 
![image](https://user-images.githubusercontent.com/57115301/82956983-a2d4c880-9f77-11ea-92ac-2b3faf7ffb5d.png)

**Comment by monicakarnes** [comment]
Looks like it only gave me one credit order number in the table.  
![image](https://user-images.githubusercontent.com/57115301/82957193-11198b00-9f78-11ea-8f33-02c1d774d01f.png)

**Comment by monicakarnes** [comment]
and note- I messed up and forgot to delete the tax part out... oops

**Comment by sevincent** [comment]
TaxTotal and ShippingShippingCreditAmount are "order level" values, so they should be the same on all the items credited for the order. Being different caused the uspI_CreateCreditOrderForExternalProcess to process the items as separate orders. I did add code so that when this happens it will take them max of each of the values just in case this happens again.

**Comment by monicakarnes** [comment]
Looks like this is fixed 
![image](https://user-images.githubusercontent.com/57115301/83201764-d9dbe300-a10b-11ea-8bbe-61f5742cc7dd.png)

![image](https://user-images.githubusercontent.com/57115301/83201799-e9f3c280-a10b-11ea-8866-307e19a7eaf8.png)


![image](https://user-images.githubusercontent.com/57115301/83201839-02fc7380-a10c-11ea-9910-55cb2c8809be.png)


Closing bug
