### ISSUE TITLE
Footer - Email Collection Box - Submit button does not work

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#127]
### Expected behavior
When I enter my email address and click the submit button I would expect that I would get a pop-up message either saying the address had already been used or giving me my coupon code. If my email address had not been used I would expect my email address to flow into the CSV file in BigCommerce.

### Actual behavior
When I enter my email address and click submit nothing happens. I do not get a pop-up message and my email address does not flow over to the subscriber count in BigCommerce.

### Steps to reproduce behavior
Go to https://tastefully-simple-sandbox-2.mybigcommerce.com/store
Enter mandiemailtest@gmail.com into the email collection box in the footer on the desktop view
Click submit

**Comment by monicakarnes** [comment]
I entered a new email address and received the pop up message. 
![image](https://user-images.githubusercontent.com/57115301/83574750-b7730c80-a4f3-11ea-899e-9b9236066177.png)


I re-entered my email address and received this message 
![image](https://user-images.githubusercontent.com/57115301/83574865-f012e600-a4f3-11ea-8b0f-6975fde0f25e.png)

I see my email added to the CSV file 

![image](https://user-images.githubusercontent.com/57115301/83574955-218bb180-a4f4-11ea-9e9c-618786300a34.png)

Closing bug.
