### ISSUE TITLE
Footer - DSA Logo

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#128]
### Expected behavior
When the DSA logo is clicked I would expect this to open in a new tab instead of taking them away from the current Tastefully Simple page.

### Actual behavior
When the DSA logo is clicked you are taken away from the Tastefully Simple page.

### Steps to reproduce behavior
Go to https://tastefully-simple-sandbox-2.mybigcommerce.com/store scroll all the way to the bottom and click on the DSA logo.

**Comment by monicakarnes** [comment]
Opened in new tab 
![image](https://user-images.githubusercontent.com/57115301/83575249-b8f10480-a4f4-11ea-9df1-ba6b3cfa6ed9.png)

Closing bug
