### ISSUE TITLE
Footer - BBB Logo

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#129]
### Expected behavior
When the BBB logo is clicked I would expect this to open in a new tab instead of taking them away from the current Tastefully Simple page.

### Actual behavior
When the BBB logo is clicked you are taken away from the Tastefully Simple page.

### Steps to reproduce behavior
Go to https://tastefully-simple-sandbox-2.mybigcommerce.com/store scroll all the way to the bottom and click on the BBB logo.

**Comment by monicakarnes** [comment]
Opened in new tab 
![image](https://user-images.githubusercontent.com/57115301/83575152-8b0bc000-a4f4-11ea-9c20-c33cb1131c6d.png)

 Closing bug
