### ISSUE TITLE
Header - Desktop - Circle Image of a person is missing from Sign In

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#130]
### Expected behavior
I would expect to see a circle image of a person displayed next to the verbiage "Sign In"
![image](https://user-images.githubusercontent.com/57953952/83293474-773d2280-a1b1-11ea-9181-c17065c519bd.png)

### Actual behavior
I do not see a circle image of a person just the text "Sign In"
![image](https://user-images.githubusercontent.com/57953952/83293491-7dcb9a00-a1b1-11ea-8357-e94ccca7e297.png)

### Steps to reproduce behavior
Go to https://tastefully-simple-sandbox-2.mybigcommerce.com/shop and view the header at the top.

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/83914918-d19d2c80-a737-11ea-80a4-7ba348399613.png)

Fixed closing
