### ISSUE TITLE
Header - Desktop - When signed in the header says Sign Out instead of Hi, "name" (arrow)

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#131]
### Expected behavior
When I have signed into my account I would expect it to say Hi, "my name" (arrow).
![headersignedin](https://user-images.githubusercontent.com/57953952/83294240-9d16f700-a1b2-11ea-9ef0-e9b83e875547.JPG)

### Actual behavior
When I have signed into my account it says Sign Out
![image](https://user-images.githubusercontent.com/57953952/83294073-4b6e6c80-a1b2-11ea-85f3-59694ef360fc.png)

### Steps to reproduce behavior
Go to https://tastefully-simple-sandbox-2.mybigcommerce.com/shop
Click Sign In
Click Create an Account
Enter details to create an account
Once you submit your details it says your account has been created click Continue Shopping. The header then says sign out instead of Hi, Mandi

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/83915005-07421580-a738-11ea-8ba7-06935d2a41e4.png)

Fixed closing

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/83915060-1fb23000-a738-11ea-9aff-d2a6d33787ea.png)

Promotion banner is also fixed and displayed
