### ISSUE TITLE
Header - Desktop - Magnifying glass next to Search is the wrong color

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#132]
### Expected behavior
I would expect the magnifying glass to be burgundy.
![image](https://user-images.githubusercontent.com/57953952/83294709-5c6bad80-a1b3-11ea-8703-5772f0fc40c6.png)

### Actual behavior
The magnifying glass is teal.
![image](https://user-images.githubusercontent.com/57953952/83294721-61306180-a1b3-11ea-983e-de2d01396eee.png)

### Steps to reproduce behavior
Go to https://tastefully-simple-sandbox-2.mybigcommerce.com/shop
View the magnifying glass next to the search box in the header.

**Comment by monicakarnes** [comment]
Still Teal 
![image](https://user-images.githubusercontent.com/57115301/83916608-15456580-a73b-11ea-9bf7-3be0be5c8839.png)

**Comment by staciejurczak** [comment]
Closing out as a non bug due to Styleguide directon for this feature to be teal.
