### ISSUE TITLE
Credit - Refund order with Rush processing item 

### ISSUE THREAD

**Issue by Denise219** [tastefully-simple/cornerstone#134]
Order # 676 has 14 day kit and Rush processing fee applied.
![image](https://user-images.githubusercontent.com/57686045/83303471-b58f0d80-a1c2-11ea-818a-1791f5660633.png)

When I view the credit order # 26936951 in myHQ under CID 122575
The Part 1 Retail and Part 1 Retail Non Commissionable amounts are incorrect.

Original order # 26912601:
![image](https://user-images.githubusercontent.com/57686045/83303717-2d5d3800-a1c3-11ea-8060-a9fbb48ad134.png)

Credit order # 26936951:
![image](https://user-images.githubusercontent.com/57686045/83303913-87f69400-a1c3-11ea-8ea6-1023c2d0bd48.png)

I would expect the Part 1 Retail (Products) to appear as ($149.99) and the Part 1 Retail Non Commissionable* amount to be at $0.00

**Comment by monicakarnes** [comment]
Did new order, 759 but its still wrong in the order listing totals. 

![image](https://user-images.githubusercontent.com/57115301/84827218-bfe63f80-afe9-11ea-97b9-e140925a9913.png)

![image](https://user-images.githubusercontent.com/57115301/84827304-e015fe80-afe9-11ea-9387-e6fcc40897a9.png)

**Comment by monicakarnes** [comment]
Here is my example of how it worked in Mock 
![image](https://user-images.githubusercontent.com/57115301/84828276-6d0d8780-afeb-11ea-9785-0f4e39133991.png)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/84828345-87dffc00-afeb-11ea-895d-a2acf6b71a73.png)

**Comment by sevincent** [comment]
Corrected NonCommissionablePartOne logic.

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/85415936-83f43280-b533-11ea-9792-3b9da0e64022.png)
![image](https://user-images.githubusercontent.com/57115301/85415995-940c1200-b533-11ea-8a8e-70f1457ca197.png)

Yeah! Fixed closing bug!
