### ISSUE TITLE
Footer- Entered email address for Flavor to my inbox- Never Received email to my inbox

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#139]
### Expected behavior
I would expect that once I have entered my email in to receive flavor to my inbox, that I would get the pop up with the code, and also receive the email in my email inbox within an hour.

### Actual behavior
I did receive the pop up with the code, but didn't receive anything via my email inbox
![image](https://user-images.githubusercontent.com/57115301/83770444-af77b180-a646-11ea-92fd-9bc2762e2b9a.png)

![image](https://user-images.githubusercontent.com/57115301/83770488-bef6fa80-a646-11ea-9a4f-41906310dffd.png)

I see it was entered in BC in the spread sheet 
![image](https://user-images.githubusercontent.com/57115301/83770640-eb127b80-a646-11ea-8c4f-8525cf4afc69.png)

And I see its saved in the table [TSProfiles].[dbo].[TsoEmailSignUp]
![image](https://user-images.githubusercontent.com/57115301/83770886-3e84c980-a647-11ea-8a65-fab1397c6f80.png)

Checked my email inbox and my spam folder and I have nothing in there. 
![image](https://user-images.githubusercontent.com/57115301/83771505-f87c3580-a647-11ea-89fc-d6321620f9af.png)

### Steps to reproduce behavior
Go to https://tastefully-simple-sandbox-2.mybigcommerce.com/store
Scroll to the bottom
Enter in email to the Flavor Collector and Submit
Receive pop up with code
* Should receive email via my inbox*

**Comment by TastefullySimple** [comment]
This is ready for QA. You will need to use new email addresses.

**Comment by monicakarnes** [comment]
Signed up with new email address- BillyJJ@mail.com and I'm still not getting the email, even days after..sign up...

![image](https://user-images.githubusercontent.com/57115301/84674842-17ed4b00-aef1-11ea-95d4-e0d70527e4d9.png)

![image](https://user-images.githubusercontent.com/57115301/84674857-1e7bc280-aef1-11ea-891b-7cf05d0d8763.png)

![image](https://user-images.githubusercontent.com/57115301/84674883-23d90d00-aef1-11ea-9ad1-021b51bcca3a.png)


![image](https://user-images.githubusercontent.com/57115301/84674960-3b17fa80-aef1-11ea-9023-0963f2dbaf66.png)

Looks like they didn't make it to TSOEmailSignUp

![image](https://user-images.githubusercontent.com/57115301/84675792-5b948480-aef2-11ea-853c-dc9ccde7fac4.png)

**Comment by TastefullySimple** [comment]
trying another fix.

**Comment by monicakarnes** [comment]
Tried new email, bluetails@mail.com 
![image](https://user-images.githubusercontent.com/57115301/84909899-da68f900-b07b-11ea-8411-c7ed9c803163.png)

still didn't make it to the table, 
![image](https://user-images.githubusercontent.com/57115301/84910048-05ebe380-b07c-11ea-9651-9d03f35f302b.png)

still didn't get my email....  :(
![image](https://user-images.githubusercontent.com/57115301/84911366-a989c380-b07d-11ea-9d9b-370771f38f5d.png)

**Comment by suehamre** [comment]
6/18 - SH - Signed up with new email address funtesting20@gmail.com, at first did not receive the email and it was not in the TSOEmailsignup table, but Jared found that the Big Commerce service had been stopped for some reason and once he restarted I rec'd the email. Closing bug.
