### ISSUE TITLE
Header- Mega Menu- MisSpelling- seasonings 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#141]
Please fix the spelling of seaonsings to the correct spelling of seasonings 

![image](https://user-images.githubusercontent.com/57115301/83917713-f7790000-a73c-11ea-8476-bf39a851bc8c.png)

**Comment by suehamre** [comment]
6/16  - SH - This was corrected with yesterdays build. Closing bug.
