### ISSUE TITLE
FireFox- Consultant Name/Association Not correct 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#142]
Go to FireFox and enter 

https://tastefully-simple-sandbox-2.mybigcommerce.com/store

Scrolled down to see products, add one to the cart 
![image](https://user-images.githubusercontent.com/57115301/83926710-3bc1cb80-a750-11ea-9ce7-626f9a2be394.png)

Shows I'm shopping with TS, click to change 
![image](https://user-images.githubusercontent.com/57115301/83926744-55fba980-a750-11ea-8708-40bed8d1ee63.png)

Find Dawn Stewart  and click shop now 
![image](https://user-images.githubusercontent.com/57115301/83926788-79beef80-a750-11ea-9b8b-79ab261d1e64.png)

It brings you back to cart, scroll down, and your consultant has now changed, but its not to Dawn Stewart like you selected its to Charys Kunkel. 
![image](https://user-images.githubusercontent.com/57115301/83926851-ad9a1500-a750-11ea-9835-9f7fef7122fc.png)

Not sure what is missing, but its working correctly in Chrome see below, it should work in other browsers, besides Chrome. 

*Below is Example of how it is WORKING in Chrome*

https://tastefully-simple-sandbox-2.mybigcommerce.com/store

Went to Store to shop, scrolled down to featured products picked item added to my cart 
![image](https://user-images.githubusercontent.com/57115301/83926387-50519400-a74f-11ea-9737-8512a62acfe1.png)

Currently shopping with TS, clicked to change 
![image](https://user-images.githubusercontent.com/57115301/83926427-6bbc9f00-a74f-11ea-8bbd-0f6b9dd2b5cc.png)
Search by id, 505 
![image](https://user-images.githubusercontent.com/57115301/83926475-83942300-a74f-11ea-8565-a02d4f54d3b8.png)
scroll to find her then click shop now
![image](https://user-images.githubusercontent.com/57115301/83926500-973f8980-a74f-11ea-9b91-6b5f5b180e47.png)

takes me back to cart and name has changed to Dawn as it should... 
![image](https://user-images.githubusercontent.com/57115301/83926551-bf2eed00-a74f-11ea-8cdf-58903778df08.png)

**Comment by staciejurczak** [comment]
SJ to post in External Slack and reconfirm with Jared if API call relate issue.

**Comment by monicakarnes** [comment]
This has since changed, the change link at the bottom will no longer be there- as we are moving away from social bug, However I did see that the name was correct now for the flyout when I changed my consultant. 

Closing bug
