### ISSUE TITLE
Credit- Order Level Refund - Credit back one item from Kit- Not Creating order Refund

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#145]
Placed BC order # 757
ordered qty 1 of Item# 101281 Essential 4
Tried to credit back one item from within the kit, at the Order Level refund 
It did not create my credit order

My original order via myHQ # 26946788
![image](https://user-images.githubusercontent.com/57115301/84819167-33ce1b00-afdd-11ea-99c4-9e41cd21ef66.png)

Here you can see my order refund via BC
![image](https://user-images.githubusercontent.com/57115301/84819062-0c774e00-afdd-11ea-939d-c8222097d42c.png)

Ran the script below- USE TSApplications
GO
INSERT INTO bcom.Credits
(
    UserID,
    OrderID,
    ShippingCreditAmount,
       TaxTotal,
    ItemNumber,--ItemNumber ItemDescription (No column name)
                                  --43 SHIPPING CHARGES 
                                  --42 CREDIT SHIPPING CHARGES 
                                  --45 Client Promo Code Correction 
    Quantity
)
VALUES
(   'TSIMPLE\mkarnes',        -- UserID - varchar(150)
    757,         -- OrderID - int
    0.00,         -- ShippingCreditAmount - decimal(18, 2)
       0.00,               --TaxTotal - decimal(18, 2) 
       163108,        -- ItemNumber - varchar(10)
    1        -- Quantity - int
)

But I'm not seeing anything in the tables for my order- and it shows complete 
![image](https://user-images.githubusercontent.com/57115301/84819306-6710aa00-afdd-11ea-9685-7adca9795c5a.png)

**Comment by sevincent** [comment]
Added code for component credits.

**Comment by monicakarnes** [comment]
Ok, so now I see this, in the table for my credit order- 
![image](https://user-images.githubusercontent.com/57115301/85474502-639b9680-b57a-11ea-8680-a80a91e29e82.png)
 
But There is nothing listed in the , order details. for my order....  nothing showing that I was crediting back the Garlic Garlic qty 1 
![image](https://user-images.githubusercontent.com/57115301/85474576-8463ec00-b57a-11ea-8b17-9c17012cad91.png)
I see that I am getting the P1 Retail, and the P1 Non comm, info, but nothing else,,, and my total for the credit shows  0.00 which means I probably got nothing back for an actual refund............

**Comment by sevincent** [comment]
Order line didn't go to TSDW because the PartentLineItemGuid was left in place. Removed the value from the order line, and it shows on the report. Made the change to uspI_CreateCreditOrderForExternal

**Comment by monicakarnes** [comment]
So the line item is here now..... 
![image](https://user-images.githubusercontent.com/57115301/85628745-44fad580-b636-11ea-91f5-43f0cb29bd9a.png)

What do we do about the price? That didn't carry down to show 9.99 credit back?
![image](https://user-images.githubusercontent.com/57115301/85629024-baff3c80-b636-11ea-881c-0a0e5de624fc.png)

**Comment by monicakarnes** [comment]
Placed new order 786- aka #26949285 
![image](https://user-images.githubusercontent.com/57115301/86619178-b5cbb700-bf7f-11ea-933b-150085def414.png)

Then did Order level refund, for one item- Garlic, just the cost of the item, no shipping, no tax and now I see my credit order displayed correctly. 
![image](https://user-images.githubusercontent.com/57115301/86619292-e7dd1900-bf7f-11ea-834a-da826ee2417a.png)

closing bug
