### ISSUE TITLE
Credit- Discount for % off- not going into myHQ correctly P1 Non Commissionable & Client Promo discounts 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#146]
Placed order for 2 S&H, and 2 Garlic- used Promo 10% off, - issued credit back 1 each S&H, Garlic
Noticed that upon checking totals, that we are off on the P1 retail non commissionable  
Original order # 26946880 Credit order#26947409
Original order shows discount at $3.59 but it should be $4.00  as you can see with BC below
![image](https://user-images.githubusercontent.com/57115301/84835896-3b4fed00-affa-11ea-876c-72d2945f3e5a.png)

But if you look at the BC order, looks like the total for the discount using 10Fall was $4.00 
![image](https://user-images.githubusercontent.com/57115301/84835987-794d1100-affa-11ea-8462-340dbaf1f854.png)

**Comment by sevincent** [comment]
Fixed DiscountDollarValue and TotalDiscountDollarValue calculations in ValidateExternalOrderJob.cs.

**Comment by monicakarnes** [comment]
Placed new order# 768
![image](https://user-images.githubusercontent.com/57115301/85417672-7dff5100-b535-11ea-936e-d65a16a53321.png)

not seeing this in the table for my order... 
![image](https://user-images.githubusercontent.com/57115301/85417741-940d1180-b535-11ea-900a-5fc7e32f8ded.png)

but I do see this order, placed in myhq 
![image](https://user-images.githubusercontent.com/57115301/85417855-b868ee00-b535-11ea-84a3-be6e004c8bb6.png)

when, I go to the details of this order, then I don't see the discounts... they are missing.. 
![image](https://user-images.githubusercontent.com/57115301/85418261-3200dc00-b536-11ea-8ef9-c55845e8df03.png)


Here is what is an Example, of the section that is missing on my order.... 

![image](https://user-images.githubusercontent.com/57115301/85418353-4ba22380-b536-11ea-9bff-106bd932325e.png)

**Comment by monicakarnes** [comment]
I now see it in the table, 
![image](https://user-images.githubusercontent.com/57115301/85627167-b9804500-b633-11ea-8bae-2afd4312422d.png)

and see my order.... but the discount amount still is wrong... at 3.59 when it shows in BC as 4.00
![image](https://user-images.githubusercontent.com/57115301/85627305-ee8c9780-b633-11ea-9a70-07c3b45a32d0.png)

BC
![image](https://user-images.githubusercontent.com/57115301/85627428-15e36480-b634-11ea-9e97-42f589046294.png)

**Comment by sevincent** [comment]
Think it's fixed (maybe order went through before I pushed my last changes). Did order 772/26949263 and it looks better.

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/86060110-b3baa300-ba29-11ea-886d-ba53ab848102.png)
So looks like its going in to myhq correctly now, but seems to be issues with the credit discount amounts.. will log separate bugs for those
