### ISSUE TITLE
Shipping information table in cart is auto displayed and can't close it

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#149]
### Expected behavior
The shipping information table should display when clicking on the Shipping table link. 

### Actual behavior
The shipping information table is automatically displaying in the cart and should not be and it can't be closed. 
### Steps to reproduce behavior
View the cart. 
![image](https://user-images.githubusercontent.com/57115316/86022052-776a5100-b9ef-11ea-810f-76757aa7f1a7.png)

![image](https://user-images.githubusercontent.com/57115316/86022120-89e48a80-b9ef-11ea-9fcd-7078433113f4.png)
![image](https://user-images.githubusercontent.com/57115316/86022152-94068900-b9ef-11ea-8200-4c8aef212193.png)

**Comment by monicakarnes** [comment]
it is no longer taking up the page, and when you click the link it open up the shipping table as it should

![image](https://user-images.githubusercontent.com/57115301/87079844-4a3a5180-c1ec-11ea-8af7-6b0577228457.png)


![image](https://user-images.githubusercontent.com/57115301/87079808-3bec3580-c1ec-11ea-93e0-a832df99f9d4.png)

Closing bug
