### ISSUE TITLE
Credit- Discount for % off- Full Credit back-  P1 Non Commissionable & Client Promo discounts Still off on Credit

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#151]
Single line- multiple qty - Promo (10Fall) 10% off each item in order
Dill Pickle- qty 4- 750403
Credit back full order
ID# 160785
BC# 781 
# 26949274
CR#26949277

So looks like the discount amount on the original order is correct but when I comes to the credit order, on the full credit discount the numbers should match and they don't both of them should read as $3.20 in the highlighted areas.... so somehow you are off by $0.32 cents 
![image](https://user-images.githubusercontent.com/57115301/86060759-08125280-ba2b-11ea-8a18-5ccbb807f0da.png)

![image](https://user-images.githubusercontent.com/57115301/86060771-11032400-ba2b-11ea-8c11-831b63a8b3a2.png)
![image](https://user-images.githubusercontent.com/57115301/86060780-17919b80-ba2b-11ea-93a7-c278c1126749.png)

**Comment by sevincent** [comment]
Made a fix to the discount calculation in uspI_CreateCreditOrderForExternal.

**Comment by monicakarnes** [comment]
Looks better in the Order listings. 
![image](https://user-images.githubusercontent.com/57115301/86628063-f1ba4880-bf8e-11ea-991d-a88c82bdb87f.png)

Order details also look better 
![image](https://user-images.githubusercontent.com/57115301/86628228-380fa780-bf8f-11ea-8f04-96c76c39738d.png)

closing bug
