### ISSUE TITLE
Credit- Discount for % off- Partial Credit back- P1 Non Commissionable & Client Promo discounts Still off on Credit

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#152]
multiple  line- multiple qty - Promo (10Fall) 10% off each item in order
Credit back partial order
ID# 160785
BC# 782
# 26949275
CR# 26949278

if on the Original order, the discount was $4.00..... for 4 items.... then on the partial credit order for 2 items, the discount should be $2.00..... not $1.80.... so off by $0.20 cents...... 

![image](https://user-images.githubusercontent.com/57115301/86061229-fed5b580-ba2b-11ea-8531-cb8b5c6ec711.png)

**Comment by sevincent** [comment]
Fixed price used to calculate the credit in uspI_CreateCreditOrderForExternal

**Comment by monicakarnes** [comment]
Looks better on Order Listings 
![image](https://user-images.githubusercontent.com/57115301/86629055-7194e280-bf90-11ea-8d41-d2f2899c2a2b.png)

Looks better on Order Details 
![image](https://user-images.githubusercontent.com/57115301/86629101-85d8df80-bf90-11ea-8310-6e5ad0283552.png)

Closing bug
