### ISSUE TITLE
Not able to shop when signed into client account 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#155]
### Expected behavior
Should be able to be logged into my client account and shop in any of the mega menu categories. 

### Actual behavior
When logged in and try to shop I receive this error below: 
![image](https://user-images.githubusercontent.com/57115316/86646415-dce8af80-bfa4-11ea-8646-7343686c396a.png)

### Steps to reproduce behavior

View Big Commerce store, login with client account. 
Click on shop and a category, and receive error above to sign in.

**Comment by staciejurczak** [comment]
@wbyrnetx will regroup before Marcom to see if related to DEV or is a BC related issue.

**Comment by staciejurczak** [comment]
@suehamre 

Before committing this to further investigation, please review the settings below for why you may be seeing this. 
1.  Check your EVERYONE group setting and check off the Group Access below and advise results!  
![image](https://user-images.githubusercontent.com/65304780/87574773-78101200-c694-11ea-9b75-1c2b1570a739.png)


![2020-07-14--1594742253_691x409_scrot](https://user-images.githubusercontent.com/65304780/87574539-1f407980-c694-11ea-9aa5-7988de15728c.png)

![2020-07-14--1594742243_700x540_scrot](https://user-images.githubusercontent.com/65304780/87574537-1e0f4c80-c694-11ea-891b-390e29922a1f.png)

**Comment by suehamre** [comment]
7/16 SH - I updated the 'everyone' customer group to include to see all products in all categories and that resolved the issue. Thanks!
