### ISSUE TITLE
Credit- Rush Fee ONLY- No Credit gets created - item number not found (table error)

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#156]
Placed order BC order 792, TSN 26949296

Issued a credit back for just the RUSH fee only

![image](https://user-images.githubusercontent.com/57115301/86656507-23daa300-bfad-11ea-8bf6-c8e3ba370bd1.png)

![image](https://user-images.githubusercontent.com/57115301/86656378-0c031f00-bfad-11ea-83d7-80da7e2368d1.png)

Ran the script, but I'm not getting anything back for a credit order, 

![image](https://user-images.githubusercontent.com/57115301/86656982-7fa52c00-bfad-11ea-8972-d7fe6901df4f.png)

![image](https://user-images.githubusercontent.com/57115301/86656821-5edcd680-bfad-11ea-8180-e79b781d7a70.png)

![image](https://user-images.githubusercontent.com/57115301/86656753-508eba80-bfad-11ea-8dd6-ce646a2fa7c3.png)

**Comment by sevincent** [comment]
Add the handling amount to uspI_CreateCreditOrderLevelForExternalProces. Set the process date and status to null on credit record 141 and it processed into credit order 26949310.

**Comment by monicakarnes** [comment]
So I did another one, but I'm still not seeing the credit order created.... I see the updates you did for process date and process status... but still not seeing my order created...
![image](https://user-images.githubusercontent.com/57115301/87095940-5d0e4f80-c207-11ea-945d-c94651ba04a5.png)

I only see my original order via TSN and MyHQ
![image](https://user-images.githubusercontent.com/57115301/87096022-84fdb300-c207-11ea-8378-ca43a1ba2b41.png)

**Comment by monicakarnes** [comment]
I see my credit now... after running your script...  the order was created and credit amounts look correct. Closing bug!!! 
![image](https://user-images.githubusercontent.com/57115301/87180840-e88aed80-c2a6-11ea-81b9-a491eb785457.png)
