### ISSUE TITLE
Consultants name does not display in header after selecting & affiliating 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#157]
### Expected behavior
Click find a cons
Select a consultant and continue
Header displays consultants name just selected 

### Actual behavior
Click find a cons
Select a consultant and continue
Header does NOT display consultants name just selected 
![image](https://user-images.githubusercontent.com/57115316/86849434-4637f380-c075-11ea-8def-3c618db365d8.png)

Consultant affiliation is reflected on the cart page. 
![image](https://user-images.githubusercontent.com/57115316/86849476-55b73c80-c075-11ea-86e6-fdc5eb3c3041.png)

### Steps to reproduce behavior
See steps above

**Comment by wbyrnetx** [comment]
Will need to ask Jared for some clarification on this. When implementing the consultant selection... we were just told that all was needed was adding an iframe to the page and that was supposed to take care of associating the user to the consultant.

**Comment by staciejurczak** [comment]
Design provided without tech requirements.  Jared updated 7/13 and Razoyo to proceed with updating this feature/functionality.  
<img width="452" alt="Screen Shot 2020-07-14 at 10 47 18 AM" src="https://user-images.githubusercontent.com/65304780/87446934-8f310000-c5bf-11ea-8a4e-274b2fb2e46a.png">
