### ISSUE TITLE
Pagination on find a consultant search results are not displayed correctly

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#158]
### Expected behavior
Per the user story #P1R - 435 - The pagination should match the example in the PLP mockup. 

**Link to the PLP mockup grid view** https://teams.microsoft.com/_#/png/viewer/teams/https:~2F~2Ftastefullysimple.sharepoint.com~2Fsites~2FPhase1Relaunch~2FShared%20Documents~2FPDP,%20Header,%20Footer~2FComps~2FTSOP1_PLP_063020_Final~2FComps~2Fproduct%20listing%20page%20-%20grid.png?threadId=19:e546d1ba87104dfca84e0d505def27f4@thread.tacv2&baseUrl=https:~2F~2Ftastefullysimple.sharepoint.com~2Fsites~2FPhase1Relaunch&fileId=eaae7a96-15b0-46c8-b099-a14b63383c9c&ctx=files&rootContext=items_view&viewerAction=view

### Actual behavior
When searching for a consultant and there are several search results that come back the pagination looks like this: 
![image](https://user-images.githubusercontent.com/57115316/86850626-37524080-c077-11ea-9934-e7a76ac649d4.png)

### Steps to reproduce behavior
Search by zip code 56343 and select max radius of 200 miles.

**Comment by wbyrnetx** [comment]
Bug confirmed and assigned out to fix.

**Comment by TastefullySimple** [comment]
This is ready for testing.

**Comment by monicakarnes** [comment]
Looks good. closing 
![image](https://user-images.githubusercontent.com/57115301/87589890-92091f00-c6ab-11ea-9252-33f6d668eb11.png)
![image](https://user-images.githubusercontent.com/57115301/87589915-9af9f080-c6ab-11ea-9455-3df633697a23.png)
