### ISSUE TITLE
Join- Link in Business Sandbox- Should go to Join landing page

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#160]
In the business sandbox, if you click on join in the header, it’s going to the join process page and I believe it should go to the join landing page.  

![image](https://user-images.githubusercontent.com/57115301/86977573-83b68280-c142-11ea-8bfb-c206c4256eda.png)

Here is where it is taking you: 
![image](https://user-images.githubusercontent.com/57115301/86977614-9d57ca00-c142-11ea-9e74-2b41e7f578f7.png)

Here is where it should take you to:

![image](https://user-images.githubusercontent.com/57115301/86977655-c24c3d00-c142-11ea-8495-708386744c1b.png)

Can we update when the click on Join in the Header it takes them here
https://tastefully-simple-sandbox-1.mybigcommerce.com/join-us

![image](https://user-images.githubusercontent.com/57115301/86977894-3c7cc180-c143-11ea-8ca0-e12115adbfee.png)

**Comment by wbyrnetx** [comment]
On the sandbox that we work on... there is no page at /join-us
https://tastefully-simple-sandbox-2.mybigcommerce.com/join-us
![Screen Shot 2020-07-09 at 9 53 04 AM](https://user-images.githubusercontent.com/4029452/87055514-10585380-c1ca-11ea-8f2d-daef1bafcbe0.png)

I've updated the link to go to /join-us/ .. and it is included in the PR I just opened:
https://github.com/tastefully-simple/cornerstone/pull/161

**Comment by monicakarnes** [comment]
Business Sandbox has been updated, to take you to the correct link... 
![image](https://user-images.githubusercontent.com/57115301/87078908-e9f6e000-c1ea-11ea-92b1-aed75cbda622.png)

And Tech Sandbox now also has the same link and page built 
![image](https://user-images.githubusercontent.com/57115301/87078983-0561eb00-c1eb-11ea-985f-8c155a4d0244.png)


Closing bug
