### ISSUE TITLE
PDP- Share Social Media Platforms- Copy Link

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#162]
Share section – Facebook, Instagram, Pinterest, & Copy Link button. Clicking on each social media icon should open the appropriate site. Clicking on the copy link allows user to copy the URL to share. 

Expected Result
It should say its copied to the clipboard 
![image](https://user-images.githubusercontent.com/57115301/87080648-a05bc480-c1ed-11ea-8e56-03aa2bb9208a.png)

Actual Result
However when I click on it it only darkens to burgundy and doesn't copy to the clipboard
![image](https://user-images.githubusercontent.com/57115301/87080712-c2554700-c1ed-11ea-8560-f4a1cc5757ab.png)

**Comment by staciejurczak** [comment]
@monicakarnes confirming Jen Wise is addressing this functionality with the dev and will oversee the styling before we resubmit updated pr.

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/87572256-e652d580-c690-11ea-8000-8e4c97729d6d.png)
 
and looks like it copies it for me, as when I paste I get this. 

https://tastefully-simple-sandbox-2.mybigcommerce.com/test-product/

closing bug thanks!
