### ISSUE TITLE
PDP- Social Media- Links when clicked should open in New Tab

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#164]
When you click on a social media icon, it should take you to that page, but opened in a new tab. 
![image](https://user-images.githubusercontent.com/57115301/87178828-6816bd80-c2a3-11ea-9ada-0a951e0d343f.png)

before I click, on Facebook, 
![image](https://user-images.githubusercontent.com/57115301/87178909-84b2f580-c2a3-11ea-86af-04907cbbf94a.png)

after I click on Facebook, 
![image](https://user-images.githubusercontent.com/57115301/87178951-94323e80-c2a3-11ea-955a-bcbaca716ac5.png)

It should open in a new window.... for the social media you click, and the current TS Product PDP you were looking at is also still open in another tab.

![image](https://user-images.githubusercontent.com/57115301/87179143-dce9f780-c2a3-11ea-91b7-64f75a95e72b.png)

**Comment by staciejurczak** [comment]
@monicakarnes - confirming we completed a pr on this correct to the icons on 7/13.  We are pushing the correction to the copy link in a pr today and will be pending on Jared's return.

**Comment by monicakarnes** [comment]
Fixed for Facebook and Twitter..... 
Pinterest is still taking over the window, we will look at options down the road for this after release
