### ISSUE TITLE
Mobile--- Out of Stock--- Looks funny with part picture and words

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#165]
On the phones, it takes the images out and only leave a tiny bit at the top and it looks funny..

here is image from iPhone 11 Pro Max
![image](https://user-images.githubusercontent.com/57115301/87207265-24d34380-c2d1-11ea-9c72-204e112bf9de.png)

here is image from Samsung 10+
![image](https://user-images.githubusercontent.com/57115301/87207311-40d6e500-c2d1-11ea-9689-75f67f04fd69.png)

When you look at the desktop it looks like this..... Can we get it to look like this..... - NOTE- we do NOT want the quick view just the " ! Temporarily out of stock message- Please check out other delicious products"
![image](https://user-images.githubusercontent.com/57115301/87207365-59df9600-c2d1-11ea-8974-10e3fe000376.png)

**Comment by staciejurczak** [comment]
@monicakarnes 

**Bug Related in @165**
****Approach for Mobile to correct PLP search with OOS results**** 
**Response:** I can create a style that hides the "Please check out our other delicious products" message on mobile on the PLP/Search/Product Cards only.  @monicakarnes confirm if this will work and noting we didn't have a mock-up for reference so may need to review with Sue/Mandi/Julie.  Your thoughts?  
![image](https://user-images.githubusercontent.com/65304780/87573425-80ffe400-c692-11ea-97bf-62279fe3e945.png)


**Enhancement Related in #165** 
we do NOT want the quick view just the " ! Temporarily out of stock message- Please check out other delicious products"

**Response:**  This enhancement isn't OOTB but if critical for Phase 1 we would need approval for ticket to investigate.  If not critical, suggesting to add to backlog for any changes once MVP in sprints are addressed

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-117

**Comment by monicakarnes** [comment]
better for both, closing 
![image](https://user-images.githubusercontent.com/57115301/88112992-8370ab00-cb76-11ea-8eed-3d08759aad0f.png)
![image](https://user-images.githubusercontent.com/57115301/88113036-9edbb600-cb76-11ea-9dad-8c3199770734.png)
