### ISSUE TITLE
Mobile- Templates for Kits- Vertical View - Shows Spinners and Prices- and it shouldn't 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#169]
Templates for Kits- Vertical View - Shows Spinners and Prices- and it shouldn't 

Here is what I see on Samsung 10+ and iPhone 11 Pro Max 
Samsung
![image](https://user-images.githubusercontent.com/57115301/87490166-9fba9800-c60a-11ea-9a43-7f00583f19bb.png)
iPhone 
![image](https://user-images.githubusercontent.com/57115301/87490202-b660ef00-c60a-11ea-9549-bce32b1f757b.png)

What it should do in Vertical view - like it does in Horizontal view-- 
Samsung
![image](https://user-images.githubusercontent.com/57115301/87490280-ef995f00-c60a-11ea-996f-1814ab976b4f.png)
iPhone 
![image](https://user-images.githubusercontent.com/57115301/87490261-e3150680-c60a-11ea-95f8-b3b2ca5c4ae2.png)

**Comment by staciejurczak** [comment]
confirming received and will review on 7/15 to address for Sprint 9

**Comment by staciejurczak** [comment]
confirming received and will review on 7/15 to address for Sprint 9

**Comment by staciejurczak** [comment]
![image](https://user-images.githubusercontent.com/65304780/87988046-47214a00-caa5-11ea-9bb2-100224f12483.png)

**Comment by monicakarnes** [comment]
I still see prices... 
this is Samsung Galaxy S10+
![image](https://user-images.githubusercontent.com/57115301/88113226-fc700280-cb76-11ea-9220-e40f22f7ffa2.png)
this is Iphone 11 Pro Max
![image](https://user-images.githubusercontent.com/57115301/88113346-380acc80-cb77-11ea-91c2-a087115f1871.png)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/88348023-ec405a80-cd11-11ea-876d-7cd39cba38c3.png)
![image](https://user-images.githubusercontent.com/57115301/88348059-0da14680-cd12-11ea-8ad3-5073fd751ee1.png)

fixed closing bug
