### ISSUE TITLE
Desktop & Mobile - Kits Template- Hover over expand view Not working 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#170]
What comes in your kit? When you hover over one of the items it should expand it to magnify the details of that item. 

It is not happening... 
![image](https://user-images.githubusercontent.com/57115301/87491352-88c97500-c60d-11ea-8021-510e0a3a3693.png)

What it should do per Mock up:
![image](https://user-images.githubusercontent.com/57115301/87491380-9979eb00-c60d-11ea-82da-8de61853a5fb.png)

**Comment by monicakarnes** [comment]
Updating, this is also suppose to happen for mobile and its not..  When you hover over an item from the kit, it should magnify the details as show from the mock up.

**Comment by TastefullySimple** [comment]
The hover feature was cut from the MVP.
