### ISSUE TITLE
Find a Consultant- Choose a Consultant- Zip Code is missing from details

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#172]
When the client searches for a consultant using the modal, the results that display for the consultants seems to be missing the zip code for the consultants.  Please add this information when the details are displayed. 

Here is what I am seeing:
![image](https://user-images.githubusercontent.com/57115301/87607213-6f363500-c6c2-11ea-909a-0f9bea4de155.png)

Here is what is show on the mock up: 
![image](https://user-images.githubusercontent.com/57115301/87607246-7fe6ab00-c6c2-11ea-823a-836ff516065f.png)

**Comment by staciejurczak** [comment]
@wbyrnetx - I'm going to ask Jared if this is API error.

**Comment by monicakarnes** [comment]
Sounds like it was decided to leave as is... closing bug
