### ISSUE TITLE
'Hi Name' disappears from header when signed in and click on dropdown arrow 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#173]
### Expected behavior
When signed into client account the 'Hi Sue' and dropdown arrow remain in the header. 

### Actual behavior
When signed into client account, header dispays 'Hi Sue' with dropdown arrow as it should. When I click directly on the arrow after signing in, the 'Hi Sue' and arrow disappear. 
![image](https://user-images.githubusercontent.com/57115316/87799999-833d7c00-c813-11ea-8528-1249e44c9616.png)

![image](https://user-images.githubusercontent.com/57115316/87794144-d27fae80-c80b-11ea-93ce-4e6ea114ae74.png)

### Steps to reproduce behavior
Sign in to client account 
Click on dropdown arrow.

**Comment by staciejurczak** [comment]
@suehamre - agreed.  I am seeing the same user experience and will make this a bug.

**Comment by suehamre** [comment]
7/27 SH - This has been fixed. Closing bug.
