### ISSUE TITLE
Clicking on the consultant name in the header should bring user to the cons webpage not bring up the find a cons modal

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#179]
### Expected behavior
When clicking on the consultants name in the heaader, the user should be brought to the consultants webpage. ( I know this page is not done yet). 
![image](https://user-images.githubusercontent.com/57115316/88074217-bb5afc80-cb3c-11ea-9621-ed4007ee103a.png)

### Actual behavior
When clicking on the consultants name in the header it is bringing up the find a cons modal and should not be. 
![image](https://user-images.githubusercontent.com/57115316/88074268-cc0b7280-cb3c-11ea-9af3-4ba355810e8d.png)

![image](https://user-images.githubusercontent.com/57115316/88074291-d3328080-cb3c-11ea-99c2-b0a076d7dd71.png)

### Steps to reproduce behavior
Have a consultant listed in the header and click on the name.

**Comment by staciejurczak** [comment]
Watching this priority as Consultants Webpage is completed

**Comment by wbyrnetx** [comment]
Getting this queued up in our system [TST-134](https://razoyo.atlassian.net/browse/TST-134)

**Comment by wbyrnetx** [comment]
I just realized that there is an "edit" link up there in the header when you have a consultant selected.
<img width="656" alt="Screen Shot 2020-07-28 at 4 31 12 PM" src="https://user-images.githubusercontent.com/4029452/88718360-dd7ded00-d0ef-11ea-9e0b-6427d409525e.png">

In my opinion, that implies that you will be changing consultants when you click there.

Do you want us to get rid of that edit link as well if we are to redirect to the consultant's page? Or do you want to keep that in there?

**Comment by suehamre** [comment]
Keep the edit link there please.

**Comment by suehamre** [comment]
Will, just to make sure we are on the same page. When a user clicks on the consultant name in the header, they should be brought to the consultants webpage. If they click the 'edit' link, the find a consultant modal appears.

**Comment by wbyrnetx** [comment]
@suehamre that is actually not what I was thinking but makes sense so glad you clarified. We'll have 2 separate click actions depending on if you click the "edit" link or elsewhere.

- "edit" will re-open the modal
- Anywhere else will take you to the consultant page

**Comment by wbyrnetx** [comment]
I just put in pull request #203 to fix this issue. Once it gets deployed by the TST team, it will work like this...

Without consultant:
<img width="1264" alt="Screen Shot 2020-07-28 at 5 58 41 PM" src="https://user-images.githubusercontent.com/4029452/88726855-76b30080-d0fc-11ea-8574-7b65e7c3114c.png">

With consultant:
<img width="1262" alt="Screen Shot 2020-07-28 at 5 59 00 PM" src="https://user-images.githubusercontent.com/4029452/88726876-7dda0e80-d0fc-11ea-996e-35146a70b0b1.png">

**Comment by wbyrnetx** [comment]
This has been deployed to the tech sandbox and it looks good to me there.

**Comment by suehamre** [comment]
7-29 SH - Clicking on name now goes to cons webpage.
