### ISSUE TITLE
Can't select Sponsor yet til Styling is doneJoin- ERROR - Unable to connect to remote server -- Can't complete the Join agreement upon clicking to checkout after Tells us about you page

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#183]
### Expected behavior
Should be able to enter in details and complete the check out for Join to complete agreement.  

### Actual behavior
I entered my details, and upon clicking check out received an error. 
![image](https://user-images.githubusercontent.com/57115301/88115312-81f5b180-cb7b-11ea-85a7-8769aa8c15d1.png)

Unable to connect to the remote server at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context) at System.Net.HttpWebRequest.GetRequestStream() at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters) at TastefullySimple.Framework.WebReference.EncryptionManagerWebService.Encrypt(String applicationName, String clearText) at TSAPI.Core.Data.Join.Context.SocialSecurityService.EncryptSsn(String ssn) at TSAPI.Areas.Join.Controllers.ApiInterfaceController.ValidateSignUp(ConsultantSignupInformation consultantSignupInformation, String ssn) at TSAPI.Areas.Join.Controllers.ApiInterfaceController.CreateUser(User user)
IF YOU CONTINUE TO EXPERIENCE ISSUES, PLEASE CONTACT THE CUSTOMER SERVICES TEAM AT 866.448.6446.

### Steps to reproduce behavior
Go to https://tastefully-simple-sandbox-2.mybigcommerce.com/join-us
 Click on Join Now! Link
 Sign up
 enter in new Join details and click to get to Whats in your kit page
enter details to complete the Tells us about yourself page
click check out to continue
then I takes a min, as it thinks, but then instead gives you the above error

**Comment by TastefullySimple** [comment]
Please try this again. I did a sign up from the test page an it worked.

**Comment by monicakarnes** [comment]
HOLD- Can't select my sponsor yet--- waiting for styling

**Comment by TastefullySimple** [comment]
Duplicate see #182
