### ISSUE TITLE
Account- Account Settings for Client to update their password- Flow of password boxes

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#186]
### Expected behavior
I would expect that I would have to enter my Current Password
Then enter my NEW Password
Then Confirm Password

can we control the names:
Current Password
New Password
Confirm Password

### Actual behavior
You enter Password, Confirm password and then Current Password 
![image](https://user-images.githubusercontent.com/57115301/88327956-57c40100-cced-11ea-91c7-a59c894d7308.png)

### Steps to reproduce behavior
go to site https://tastefully-simple-sandbox-2.mybigcommerce.com/store
Go to upper right corner click to sign in
sign into your client account 
click on drop down arrow by your name and select profile
then click on account settings

**Comment by wbyrnetx** [comment]
Not seeing that BigCommerce has an easy way for us to switch the order of those fields. We can spend some time investigating more, just need to know if you guys want to prioritize this.

**Comment by mandi920** [comment]
@wbyrnetx we do not feel like it is worth it to spend time on right now. I have added it to our backlog and will close the bug.
