### ISSUE TITLE
Account- Login from Cart page- Shipping table- Still takes you to old account sign in page

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#187]
### Expected behavior
From cart page - shipping table link - when opened there is a link under tracking to 'sign in or create an account' this link needs to be redirected to the new sign in/create an account for Big Commerce. Currently it is going to sitecore TSO create an account page.

**it should take me here
![image](https://user-images.githubusercontent.com/57115301/88331782-22baad00-ccf3-11ea-9155-5147b2a9eafe.png)

### Actual behavior
click on shipping table link within cart
![image](https://user-images.githubusercontent.com/57115301/88331474-a32cde00-ccf2-11ea-8097-b1cf1137fe22.png)

click on sign in or create account link 
![image](https://user-images.githubusercontent.com/57115301/88331553-c5266080-ccf2-11ea-8eec-ab0a2ae7e7b4.png)

It takes you here
![image](https://user-images.githubusercontent.com/57115301/88331604-d7a09a00-ccf2-11ea-90e8-05246af534bd.png)

### Steps to reproduce behavior
go to ts store
add items to your cart
view items in cart
click on shipping table
click on sign in or create account

**Comment by staciejurczak** [comment]
7/24 Confirm if this is hard coded by Irish Titan and if the approach to fix this bug is to address the file OR if this will go away at launch.

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-131

**Comment by monicakarnes** [comment]
fixed - closing
