### ISSUE TITLE
Client account - orders tab - missing contact customer service message

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#189]
### Expected behavior
When logged into a client account and viewing the orders page a message to contact customer service should be displayed: 
![image](https://user-images.githubusercontent.com/57115316/88341057-80a2c100-cd02-11ea-8ab2-6db12d2f31d6.png)

### Actual behavior
Login to account, view orders page and no message appears: 
![image](https://user-images.githubusercontent.com/57115316/88341116-9dd78f80-cd02-11ea-87ee-28a67164012a.png)

### Steps to reproduce behavior
Login to client account and view orders page/tab.

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-126 - recommending to close this but or freeze as QA bug technically preceded development

**Comment by mandi920** [comment]
@monicakarnes I'm assigning this back to you until the user story has been completed. A couple of the client account user stories were missed so no work had been done on this yet.

**Comment by wbyrnetx** [comment]
A PR has been opened in your Github for this #215. Jen QA'ed this on her environment, I've requested some screenshots from her, which I'll upload here.

I also updated [P1R-515](https://tsrelaunchtest.atlassian.net/browse/P1R-515)

Just waiting on the PR to be deployed...

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/88943660-5fd1f280-d251-11ea-9d65-9b167a5f89dd.png)
