### ISSUE TITLE
IE- Is a Mess- Header, Sticky Header, Main page details, Footer

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#190]
### Actual behavior
Header----Cart is lodged under the Sign in
Sticky Header---- Shop is weird under Join 
Sticky Header---- Search bar isn't long enough to see what you enter for search
![image](https://user-images.githubusercontent.com/57115301/88341121-a16b1680-cd02-11ea-8c48-5a6df573cc71.png)

Main page images are all messed up and add to cart is on the right
![image](https://user-images.githubusercontent.com/57115301/88342231-a7fa8d80-cd04-11ea-9991-99364dc602fc.png)
![image](https://user-images.githubusercontent.com/57115301/88342272-b3e64f80-cd04-11ea-85a1-b65d6c70c3bb.png)
![image](https://user-images.githubusercontent.com/57115301/88342322-cbbdd380-cd04-11ea-9f9b-679f87f7e891.png)

Footer is HUGE for guarantee
![image](https://user-images.githubusercontent.com/57115301/88342373-e09a6700-cd04-11ea-953b-5e4ba555532f.png)

### Steps to reproduce behavior

Use Internet Explorer 
go https://tastefully-simple-sandbox-2.mybigcommerce.com/

**Comment by TastefullySimple** [comment]
Internet Explorer is not supported
