### ISSUE TITLE
Client account - order details page - reorder button color should be burgundy

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#191]
### Expected behavior
Button colors should match the style guide. 

### Actual behavior
When logged into a client account and viewing the order details page of an order the reorder button and the print button is white and should be burgundy based on the style guide. 
![image](https://user-images.githubusercontent.com/57115316/88344384-0e81aa80-cd09-11ea-8ab7-5ae70cf79491.png)
![image](https://user-images.githubusercontent.com/57115316/88344395-16414f00-cd09-11ea-8e78-8f5ead2d16f1.png)
![image](https://user-images.githubusercontent.com/57115316/88344989-8b615400-cd0a-11ea-85dd-2c7a6304019f.png)

### Steps to reproduce behavior

Login to a client account and click on the orders tab, then click on an order number to view the details.

**Comment by mandi920** [comment]
Due to the low priority of this bug we are closing and added to the backlog.

**Comment by mandi920** [comment]
Should be fixed in next pull request.

**Comment by staciejurczak** [comment]
@mandi920 
In discussion with Jen 7/27 - this will be corrected on 7/28 on Razoyo ticket TST-130.  
https://razoyo.atlassian.net/browse/TST-130

**Comment by wbyrnetx** [comment]
Pull request is in #205, waiting for it to be deployed.

**Comment by suehamre** [comment]
@wbyrnetx  - I see the reorder button updated to burgundy but not the print button. Can we update the print button as well? I realize I didn't have the print button listed in the title but I did in the body of the email.

**Comment by wbyrnetx** [comment]
Sending this back to Jen with that update.

**Comment by TastefullySimple** [comment]
ready to test

**Comment by suehamre** [comment]
7-30 SH - fixed.
