### ISSUE TITLE
Client account - account settings should be change to profile 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#192]
### Expected behavior
Per the US #516 
 - Change current OOTB label 'Account Settings' to 'Profile' and move to the front of the tabs list. 

### Actual behavior
Still displays "account settings'" and is not in the front 
![image](https://user-images.githubusercontent.com/57115316/88346055-0deb1300-cd0d-11ea-811d-50b0ea2957f0.png)

### Steps to reproduce behavior

Login to client account, view tabs.

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-129
PR #200 is pending Jared to push out on 7/27 5:47pm

**Comment by suehamre** [comment]
7/28 SH - Label has been changed to Profile, however was not moved to the front of the list. Jen is going to do this and send in another PR or let me know via teams if it's not possible.

**Comment by suehamre** [comment]
7-29 Profile has been moved to the front of the list now.
