### ISSUE TITLE
Consultant is not updated in cart page

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#193]
### Expected behavior
When I have a consultant selected, the tan bar in the cart should reflect the consultant I am shopping with, along with the header. 

### Actual behavior
When a consultant is selected and user is in the cart page, the tan bar always shows 'you are shopping with Sally Sue Hernandez vs the consultant that was selected. The consultant name is also disappearing from the header when viewing the cart page. 
![image](https://user-images.githubusercontent.com/57115316/88419837-72f54600-cdab-11ea-9501-1bf074bfe00f.png)

### Steps to reproduce behavior
Search for a consultant and select one. Then view the cart page. ( will need to add items if you have an empty cart). 
After selecting the consultant, the consultant is updated in the header: 
![image](https://user-images.githubusercontent.com/57115316/88420005-c798c100-cdab-11ea-98e1-fbcfefcfe6bf.png)
Then go to the cart page and see that the tan banner is not correct and the consultant name has disappeared from the header: 

![image](https://user-images.githubusercontent.com/57115316/88420088-ed25ca80-cdab-11ea-84b0-4953c0f28bf0.png)

**Comment by TastefullySimple** [comment]
This is ready for testing.

**Comment by suehamre** [comment]
7-27 SH - Cart page is now updating. Closing bug.
