### ISSUE TITLE
Account- Client Wish List- Does not Delete List or Remove item form list once you click the button

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#196]
### Expected behavior
•	Ability to delete an item from the wish list or delete all. 
•	Ability to remove an item from the wish list. 

### Actual behavior

When I click to Delete my wish list, it does not delete even though it seemed like it was attempting to 
![image](https://user-images.githubusercontent.com/57115301/88429130-b8ba0a80-cdbb-11ea-9b56-5b8f6a763c36.png)

When inside my Wish list, I clicked on the button to Remove the Test Product and it did not delete 
![image](https://user-images.githubusercontent.com/57115301/88429256-ebfc9980-cdbb-11ea-9891-6a44c8d7675a.png)

** Note** when -trying to Delete All Wish lists this did work- Not sure why the other ones didn't 
![image](https://user-images.githubusercontent.com/57115301/88429492-61686a00-cdbc-11ea-9abd-56f4388c9333.png)

![image](https://user-images.githubusercontent.com/57115301/88429714-b73d1200-cdbc-11ea-9005-6169a6ae6992.png)

### Steps to reproduce behavior

Log into client account
Go to wish lists
Attempt to delete one whole wish list- by clicking on delete---- List doesn't delete

Log into client account
Go to wish lists, Open list with items in it
Click to Remove one of the items ----- Item remains and doesn't Remove from the wish List

**Comment by staciejurczak** [comment]
@monicakarnes 
I concur and was able to replicate this experience.  Adding this bug. 
I am noting that this function did work last week as I did delete 3 wishlists. Not sure what changed prior to the button color change.

**Comment by monicakarnes** [comment]
Fixed, closing bug
