### ISSUE TITLE
Choose your party modal does not match the mockup

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#197]
### Expected behavior
After I search for a party and results are displayed, it should look like this per the mockup: 
![image](https://user-images.githubusercontent.com/57115316/88433496-d4291380-cdc3-11ea-92a6-2c144a2ea236.png)

### Actual behavior
party results look like this: 
![image](https://user-images.githubusercontent.com/57115316/88433566-f589ff80-cdc3-11ea-9648-acc38c4b7695.png)

### Steps to reproduce behavior

Click the find a party modal, and view results. Click a party to select.

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-119

**Comment by suehamre** [comment]
7-28  - Fixed.
