### ISSUE TITLE
Big Commerce orders are not getting downloaded

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#202]
### Expected behavior
Orders placed in Big Commerce (new tastefullysimple.com orders) should be downloaded to TS databases and appear in the big commerce table 
![image](https://user-images.githubusercontent.com/57115316/88717722-917a7a80-d0e6-11ea-8654-710968710c13.png)
 TSN, myHQ, Prowess. 

### Actual behavior
I placed a few orders, #806, and #808 and they are not being downloaded. The last order appearing in the Big C. dbo.order table is #804 from 11:28am this morning. 
![image](https://user-images.githubusercontent.com/57115316/88717392-1913b980-d0e6-11ea-8057-6a32808298c6.png)
Jared checked for me and Big commerce jobs is running on HQINTRA10.
I'm also not able to view the event log, it just keeps 'executing' and not giving me results: 
SELECT TOP 500 DATEADD(HOUR,-5,EventDate) AS 'Central Time',*
FROM [TSApplicationLog].[dbo].[EventLog] WITH (nolock)
WHERE logger = 'ScheduledJobs.Jobs.Integration.BigCommerce.Import.DownloadOrdersForFulfillmentJob'
ORDER BY EventDate DESC

### Steps to reproduce behavior
Place an order in Big C and wait. LOL. :) View the table: 
![image](https://user-images.githubusercontent.com/57115316/88717551-4eb8a280-d0e6-11ea-83f2-ff2ca32d60bc.png)

**Comment by TastefullySimple** [comment]
SELECT TOP 500 DATEADD(HOUR,-5,EventDate) AS 'Central Time',*
FROM [TSApplicationLog].[dbo].[EventLog] WITH (nolock)
WHERE logger = 'BigCommerceJobs.Jobs.Download.DownloadOrdersForFulfillmentJob'
AND EventXID > 229485223
ORDER BY EventDate DESC

**Comment by TastefullySimple** [comment]
Please check again. I posted the updated event log query above.

**Comment by suehamre** [comment]
7-29 SH - I see the orders are being downloaded now. My order from yesterday that I attached to a party is not showing in myhq so I will log a new bug for this.
