### ISSUE TITLE
Party Search by Host Last name Receive Error no results found

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#204]
### Expected behavior
I would expect that if I search for a host via State, and search by name- either 1st name, or Last name that I should be able to see the party information display in the results. 

### Actual behavior
When I search by the last name, I get no results error
![image](https://user-images.githubusercontent.com/57115301/88736833-6a2fa780-d0fe-11ea-8704-15ba12c951d7.png)

![image](https://user-images.githubusercontent.com/57115301/88736980-761b6980-d0fe-11ea-8333-26da094488c0.png)

When I search by 1st name I get results- 

![image](https://user-images.githubusercontent.com/57115301/88737280-8cc1c080-d0fe-11ea-8033-576f25d906ae.png)

![image](https://user-images.githubusercontent.com/57115301/88737382-96e3bf00-d0fe-11ea-9dc3-0156c7b966db.png)

### Steps to reproduce behavior
Set up party- with host
Go to website and search for party
Search via state and last name, receive error

**Comment by wbyrnetx** [comment]
I'm thinking that this might be an issue with the API. As far as I can tell, our request to the API looks correct, but we are getting no results back from it.

Here's the request & response for "reiplinger"
<img width="556" alt="Screen Shot 2020-07-29 at 9 07 20 AM" src="https://user-images.githubusercontent.com/4029452/88803992-452d4a00-d17b-11ea-8ded-aac32d755229.png">

I double checked the Find a Party API docs, and didn't see anything obvious. @TastefullySimple (Jared) can you take a look?

**Comment by TastefullySimple** [comment]
API fixed

**Comment by monicakarnes** [comment]
Fixed- closing
![image](https://user-images.githubusercontent.com/57115301/88842738-8df9f880-d1a5-11ea-8ecc-0a5f2f9eb9ff.png)
