### ISSUE TITLE
Consultant Webpage - Changing the consultant does not update the page

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#206]
### Expected behavior
If user is on the consultants webpage, and clicks the edit link to change the consultant, the consultant should be updated in the header and also user should be on the newly selected consultant's webpage. 

### Actual behavior
If user is on the consultants webpage and clicks the edit link to change the consultant, the consultant is updated in the header but the page does not refresh to the newly selected consultants webpage. 
![image](https://user-images.githubusercontent.com/57115316/88801478-6425df00-d16f-11ea-81b9-b43b8893a5b4.png)

### Steps to reproduce behavior
Search for a consultant and click the name to view the consultants webpage. 
Click the edit link to select a different consultant and continue.

**Comment by wbyrnetx** [comment]
Pull request #207 to fix this was just opened.

**Comment by wbyrnetx** [comment]
This was deployed to the Tech Sandbox.

Consultant page **before** clicking "edit" and choosing another...
<img width="1274" alt="Screen Shot 2020-07-29 at 9 35 50 AM" src="https://user-images.githubusercontent.com/4029452/88806874-000b1700-d17f-11ea-962d-813d60e95af8.png">

Consultant page **after** clicking "edit" and choosing another...
<img width="1275" alt="Screen Shot 2020-07-29 at 9 36 07 AM" src="https://user-images.githubusercontent.com/4029452/88806922-0e593300-d17f-11ea-9809-32bd6076c3ab.png">

**Comment by suehamre** [comment]
7-29 SH - Thank you!
