### ISSUE TITLE
Clicking on 'view my ts webpage' in the returned consultant results should bring user to the consultants webpage

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#208]
### Expected behavior
After searching for a consultant, when the results are displayed, if user clicks on the 'view my ts webpage' they should be brought to the consultants webpage. 
![image](https://user-images.githubusercontent.com/57115316/88808032-fd58f380-d177-11ea-9e64-aec9526d25cb.png)

### Actual behavior
After searching for a consultant, when the results are displayed, if user clicks on the 'view my ts webpage', the system just selects the consultant. 
![image](https://user-images.githubusercontent.com/57115316/88808359-680a2f00-d178-11ea-9a99-5c31cb1953e1.png)

### Steps to reproduce behavior
Search for a consultants. When results are displayed, click on 'view my ts webpage'.

**Comment by wbyrnetx** [comment]
On it: [TST-128](https://razoyo.atlassian.net/browse/TST-128)

**Comment by suehamre** [comment]
7-31 SH  - Clicking on the view my TS page is now going to our current sitecore ts.com vs the new big commerce consultant webpage: 
![image](https://user-images.githubusercontent.com/57115316/89066959-f971d080-d333-11ea-9996-d7cde708e3f0.png)
![image](https://user-images.githubusercontent.com/57115316/89067057-24f4bb00-d334-11ea-9278-639459c9a8eb.png)

**Comment by wbyrnetx** [comment]
Jared let us know in Slack that he was going to update the API URLs to reflect the correct environment.

Currently, we get URLs like this:
https://www.tastefullysimple.com/web/lleichinger
<img width="559" alt="Screen Shot 2020-08-03 at 8 11 37 AM" src="https://user-images.githubusercontent.com/4029452/89181299-6a4a0000-d561-11ea-829b-09e2bde2a9c7.png">

**Comment by wbyrnetx** [comment]
Confirmed that I'm still getting tastefullysimple.com URLs from the Tech Sandbox as of this morning.

**Comment by wbyrnetx** [comment]
@monicakarnes I believe this one should not be assigned to me. Per our standup yesterday, there are no code modifications needed on our end. The API response values need to be updated.

**Comment by suehamre** [comment]
8-5 SH - Now getting a 404 error page when clicking the view my TS page link. 

https://us04web.zoom.us/j/78041793840?pwd=bVJxLzNZWmpOa2JwMWkxUEkwQUhhUT09

**Comment by wbyrnetx** [comment]
This was deployed to the Tech Sandbox.

**Comment by suehamre** [comment]
8/6 @wbyrnetx I think you updated the wrong bug. Looks like you meant to update #231 for the BBOK item vs this one that is for the cons webpage link. I am still getting the 404 error on this.

**Comment by TastefullySimple** [comment]
Clicking the View My TS Webpage should affiliate the user with the consultant. 
![image](https://user-images.githubusercontent.com/53190431/89821227-e6b98180-db13-11ea-8906-8d38f7166d86.png)

**Comment by wbyrnetx** [comment]
We've identified the issue here and are working on it.

**Comment by jsmnglng-w** [comment]
Created a ticket for this 404 issue: [TST-168](https://razoyo.atlassian.net/browse/TST-168)

**Comment by suehamre** [comment]
8-17 SH - Fixed.
