### ISSUE TITLE
Consultant Webpage - Social media icons should only display if consultant has entered their info in myHQ

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#209]
### Expected behavior
When a consultant enters their social media information in myHQ under customize my website, the appropriate icons will be displayed on their webpage. 
![image](https://user-images.githubusercontent.com/57115316/88821796-b1627a80-d188-11ea-8ad3-fa67e296d7dc.png)

### Actual behavior
Icons are all displayed on consultants webpage and no social media information is entered for them in myhq. 
![image](https://user-images.githubusercontent.com/57115316/88821904-d1923980-d188-11ea-8865-d71bc55d08ac.png)
![image](https://user-images.githubusercontent.com/57115316/88821796-b1627a80-d188-11ea-8ad3-fa67e296d7dc.png)
This is consultant ID #0000032

### Steps to reproduce behavior
View consultants webpage. 
View consultants myHQ customize website info - contact me.

**Comment by wbyrnetx** [comment]
@suehamre  we are swapping in the social media icons with real URLs as we speak. I am going to make a not that we should not show icons if we don't get URLs for all/any of the platforms. Do you have a consultant that we can use as an example that doesn't have them all filled out?

**Comment by suehamre** [comment]
@wbyrnetx , sounds good. The one above has none entered. Let me see if I can find one or update one for you to have something entered.

**Comment by suehamre** [comment]
@wbyrnetx Consultant ID#0000505 has all social media links filled in in QA1/Tech Sandbox. 
![image](https://user-images.githubusercontent.com/57115316/88823174-66496700-d18a-11ea-84c1-e942411300a2.png)

**Comment by wbyrnetx** [comment]
The code for this is in a PR I opened this morning #215, however this is not ready to QA yet. We are working through some Shogun blocks on the consultant page, and so this is what it currently looks like:
<img width="1276" alt="Screen Shot 2020-07-30 at 9 05 48 AM" src="https://user-images.githubusercontent.com/4029452/88926530-1f1fac80-d244-11ea-9f7c-67967278c2fb.png">

As soon as the consultant page is back up, then I will let you know and you can QA the social icons and them being dependent on if the consultant has entered a URL in myHQ or not.

**Comment by TastefullySimple** [comment]
Ready for QA.

**Comment by monicakarnes** [comment]
I've deleted my cookies, and it does not look fixed... also verified that myhq was still empty- for 32 Holly
![image](https://user-images.githubusercontent.com/57115301/88957718-f360ee80-d264-11ea-9b07-f92702e86e94.png)

![image](https://user-images.githubusercontent.com/57115301/88957750-0247a100-d265-11ea-8bd6-010d5cb09331.png)

Also checked, 505 Dawn 
![image](https://user-images.githubusercontent.com/57115301/88957933-518dd180-d265-11ea-86b9-67d7fcf7c858.png)

**Comment by suehamre** [comment]
7-30 SH - This is working for me. 
![image](https://user-images.githubusercontent.com/57115316/88968919-b05b4700-d275-11ea-9828-ab99c380df3f.png)
![image](https://user-images.githubusercontent.com/57115316/88969019-d1bc3300-d275-11ea-87bf-970b8b3523df.png)
I also made a change to CID#28 and the facebook icon appeared. 
![image](https://user-images.githubusercontent.com/57115316/88969388-658dff00-d276-11ea-9a28-319b9f8f4758.png)
