### ISSUE TITLE
Need Styling fixed to test -Join path - Party bar should not be displayed

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#211]
### Expected behavior
When the user is in the join path the party bar should not be displayed. They cannot attach their BBOK order to a party. 

### Actual behavior
In the join path the party bar is displayed on all pages and needs to be removed. 
![image](https://user-images.githubusercontent.com/57115316/88826362-47e56a80-d18e-11ea-9b05-fcb577ffbce8.png)

### Steps to reproduce behavior
Click on join, and start down the join path. View pages.

**Comment by wbyrnetx** [comment]
@suehamre I'm not familiar with "the join path". Can you point me towards how you get to that page that you are on in your screenshot plz?

**Comment by suehamre** [comment]
@wbyrnetx , Click on join in the header:
![image](https://user-images.githubusercontent.com/57115316/88930127-aa973e80-d240-11ea-8641-a191c4b17c5b.png)
Click on the join now link: 
![image](https://user-images.githubusercontent.com/57115316/88930180-bb47b480-d240-11ea-9279-cd979b3167d7.png)
You will then need to login or sign up to navigate through: 
You can use this login if you want just to get past this page: Email =wonderingwhathappens@mailinator.com Password = Password123
![image](https://user-images.githubusercontent.com/57115316/88930256-da464680-d240-11ea-8dbf-0106322bb86b.png)

**Comment by suehamre** [comment]
@wbyrnetx , I would expect the party bar to be removed starting on this login/sign up and through the join path.

**Comment by wbyrnetx** [comment]
Got it, thank you for the clarification. Jen is on it [TST-142](https://razoyo.atlassian.net/browse/TST-142)

**Comment by suehamre** [comment]
7-31 SH - On hold - cannot complete test all the way through join path until styling is fixed, because I cannot select a consultant to continue. If i just check the terms and conditions and click continue I am brought out of the join path to the cart. 
![image](https://user-images.githubusercontent.com/57115316/89070301-6daf7280-d33a-11ea-9016-2f3d7d32f99d.png)

**Comment by staciejurczak** [comment]
Also see TST-136 which was created to address the styling issue on the Join path - where party bar should not be displayed.

**Comment by TastefullySimple** [comment]
@suehamre I think this is ready for QA.

**Comment by suehamre** [comment]
8/10 SH - Fixed.
