### ISSUE TITLE
Big Commerce order attached to a party does not display in myHQ

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#213]
### Expected behavior
Orders placed in Big C that are attached to a party should display in myHQ. 

### Actual behavior
Order is not displaying in myhq. 
I placed Big C order #806 yesterday and attached to 'Jason Test' party under CID#28. The order is appearing in TSN but not myHQ. 
![image](https://user-images.githubusercontent.com/57115316/88853854-fc46b700-d1b5-11ea-99e1-965675863168.png)

![image](https://user-images.githubusercontent.com/57115316/88853741-cacdeb80-d1b5-11ea-8595-4d719fb09bcf.png)
![image](https://user-images.githubusercontent.com/57115316/88853751-d02b3600-d1b5-11ea-89c7-37cbf4b365c3.png)
![image](https://user-images.githubusercontent.com/57115316/88853770-d5888080-d1b5-11ea-95f0-64df5299d59f.png)

### Steps to reproduce behavior
Place order in Big C and attached to a party. 
Wait for order to be downloaded and view TSN, myHQ.

**Comment by suehamre** [comment]
7-31 SH - Denise placed an order today attached to a party and her order is appearing in myHQ, however the details page is empty. 
Under CID#505 order number # 26949348
![image](https://user-images.githubusercontent.com/57115316/89060684-0dfc9b80-d329-11ea-95ec-38ca09fdcb91.png)

**Comment by sevincent** [comment]
Added additional BC source order mapping to ConfigOrderTypeMapping

**Comment by suehamre** [comment]
I am still not seeing my party orders in myHQ. 
![image](https://user-images.githubusercontent.com/57115316/89916728-95fe6300-dbbd-11ea-863c-42c0586ff9df.png)
![image](https://user-images.githubusercontent.com/57115316/89916805-aadaf680-dbbd-11ea-96d9-2bad74dee575.png)

**Comment by sevincent** [comment]
Added additional User type mapping.

**Comment by suehamre** [comment]
8-12 SH. Fixed!! :)
