### ISSUE TITLE
Checkbox to reorder items is barely visible on the order details page

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#214]
### Expected behavior
When viewing the order details page of an order that was previously placed there should be a checkbox next to each item for the user to select to then click 'reorder'. See below for the OOTB functionality. 
![image](https://user-images.githubusercontent.com/57115316/88869145-a3881600-d1d7-11ea-8dc2-c32ceab138b0.png)

### Actual behavior
When logged in as a client and viewing the order details page, the checkbox for the items is so far left on the page it is barely visible. Sometimes you can't see it at all. 
![image](https://user-images.githubusercontent.com/57115316/88869214-ce726a00-d1d7-11ea-9166-5a0fe6308a6e.png)

### Steps to reproduce behavior

Login as a client, view the order details page of a previously placed order.

**Comment by staciejurczak** [comment]
@suehamre reviewed with Jen.  We think it's because OOTB isn't seeing the widescreen settings.  This is under Razoyo ticket https://razoyo.atlassian.net/browse/TST-146

**Comment by suehamre** [comment]
8-7 SH - Looks good on desktop and mobile.
