### ISSUE TITLE
Tastefully Simple should not be displayed in the header when shopping with

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#216]
### Expected behavior
Per the requirement in  User Story P1R-540:
If shopping with Tastefully Simple the header does NOT display Tastefully Simple, the Find A Consultant remains. Only the banner in the cart will display to the user that they are shopping with Tastefully Simple. 

![image](https://user-images.githubusercontent.com/57115316/88942692-3b294b00-d250-11ea-935d-3d65a44abf4a.png)

### Actual behavior
When shopping with tastefully simple, Tastefully Simple is displayed in the header and should not be. 
![image](https://user-images.githubusercontent.com/57115316/88942872-71ff6100-d250-11ea-811e-9e56e6ee3741.png)

### Steps to reproduce behavior
Search for a consultant with no results found and continue shopping with TS.

**Comment by staciejurczak** [comment]
@suehamre - I'm replicating this bug now.

**Comment by wbyrnetx** [comment]
Got it, Victor is on it [TST-136](https://razoyo.atlassian.net/browse/TST-136)

**Comment by suehamre** [comment]
7-31 SH - Fixed
