### ISSUE TITLE
Update the default consultant in the cart to Tastefully Simple

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#218]
### Expected behavior
If a client comes to the Tastefully Simple website to shop and is not affiliated with a consultant, the system will automatically affiliate the order to the HQ Tastefully Simple consultant. CID#0160785 (prod cons).  There is a separate bug logged to for this functionality to work #217 
The cart would then display 
![image](https://user-images.githubusercontent.com/57115316/88955147-243f2480-d261-11ea-9913-fb30e51e2257.png)

### Actual behavior
When no consultant is selected, 'Sally Sue Hernandez' is displayed. This should be Tastefully Simple. 
If a client comes to the Tastefully Simple website to shop and is not affiliated with a consultant, the system will automatically affiliate the order to the HQ Tastefully Simple consultant. CID#0160785 (prod cons).

### Steps to reproduce behavior
Clear cookies so no consultant is selected. Add item to cart and view cart.

**Comment by wbyrnetx** [comment]
On it.

**Comment by suehamre** [comment]
8/3 SH  - Default is now displaying TS.
