### ISSUE TITLE
Remove the extra 'orders' text on orders page

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#219]
### Expected behavior
Orders page should only have this: 
![image](https://user-images.githubusercontent.com/57115316/88970512-282a7100-d278-11ea-8bd0-7edbe81de7c4.png)

### Actual behavior
When viewing the orders page there is an extra 'orders' text above the images: 
![image](https://user-images.githubusercontent.com/57115316/88970608-56a84c00-d278-11ea-93e4-b126495d84f6.png)

### Steps to reproduce behavior

Login as a client and view the orders tab.

**Comment by wbyrnetx** [comment]
Jen is fixing this, will group it with work in TST-142

**Comment by suehamre** [comment]
7/31 SH - Fixed.
