### ISSUE TITLE
PartyBar/Header-  Selecting a party- Doesn't update my Consultant in Header for Desk top & Mobile

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#222]
### Expected behavior
When you select a party from the party bar, and the page refreshes with information, it show that you are now shopping with that Host's party, but also should update the Header to the Consultant that the Host is having the party with. 

### Actual behavior
Its updating the party bar with the host details- But the Consultant's information is not updating in the Header. 
![image](https://user-images.githubusercontent.com/57115301/89087443-ed990500-d359-11ea-913b-bdfff1726ac6.png)

### Steps to reproduce behavior
Go to Site
click on Find a Party
Search for a host
Select Host
See updated party details
Should see updated consultant in Header

**Comment by monicakarnes** [comment]
This is also broken for mobile 
![image](https://user-images.githubusercontent.com/57115301/89104565-d3096f00-d3df-11ea-86f9-7a58d02f03e6.png)

**Comment by staciejurczak** [comment]
This is on TST-148

**Comment by wbyrnetx** [comment]
This was deployed to the Tech Sandbox and is ready to QA

**Comment by monicakarnes** [comment]
Consultant is updated

![image](https://user-images.githubusercontent.com/57115301/89460679-4ab50200-d730-11ea-8a31-e35912b3729e.png)
![image](https://user-images.githubusercontent.com/57115301/89460706-556f9700-d730-11ea-81bd-18484e6aa615.png)
