### ISSUE TITLE
Desktop & Mobile- Party Bar/ Find a party disappears after I added items to my cart 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#223]
### Expected behavior
When on mobile, if you select a party, add items to your cart and then want to switch parties. You should be able to do so in the party bar and find a different party. 

### Actual behavior
After I selected my party, added an item to my cart and then went to change the party. The party bar is gone, I'm not able to switch parties. 
![image](https://user-images.githubusercontent.com/57115301/89104708-f54fbc80-d3e0-11ea-925c-a4cc161203e5.png)
 added item to my cart (note consultant is also wrong) 
![image](https://user-images.githubusercontent.com/57115301/89104714-01d41500-d3e1-11ea-87b0-44338467f9cf.png)
Tried to update do different party but can't as my party info is gone, no way for me to change it
![image](https://user-images.githubusercontent.com/57115301/89104728-144e4e80-d3e1-11ea-9c8a-d3dc8f6e34bc.png)

### Steps to reproduce behavior
on mobile
select party
add item to your cart
go back to menu to change parties, you will see that your original selected party is gone and no option to edit your party

**Comment by monicakarnes** [comment]
I had a party for Mikey in my party bar and once I added the item to my cart, it kicked my information out of the partybar and it turned white, and not clickable 

![image](https://user-images.githubusercontent.com/57115301/89109694-2c39c880-d409-11ea-829f-2b9ec3798bd9.png)

![image](https://user-images.githubusercontent.com/57115301/89109664-d9f8a780-d408-11ea-8e22-674740aa96d9.png)

**Comment by monicakarnes** [comment]
and not sure if this helps or not,but I just logged out of Smiles account and it now shows on the page that I'm still shopping with Mikey's party 
![image](https://user-images.githubusercontent.com/57115301/89109732-8dfa3280-d409-11ea-83ff-a09c3eb62b56.png)

**Comment by wbyrnetx** [comment]
On it [TST-147](https://razoyo.atlassian.net/browse/TST-147)

**Comment by wbyrnetx** [comment]
This was deployed to the Tech Sandbox and is ready to QA

**Comment by monicakarnes** [comment]
party bar now is there for mobile and desktop after I add items to the cart
![image](https://user-images.githubusercontent.com/57115301/89459028-a5009380-d72d-11ea-904f-0372a83c9992.png)
![image](https://user-images.githubusercontent.com/57115301/89459066-b2b61900-d72d-11ea-960f-55df90cb527f.png)

But I'm not able to switch parties on Mobile- When I click nothing happens yet... should get the find party modal 
![image](https://user-images.githubusercontent.com/57115301/89460127-653aab80-d72f-11ea-987e-8dc3b04e5120.png)

**Comment by monicakarnes** [comment]
@wbyrnetx was this still part of what your are working on for mobile?

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/90036192-58b2d780-dc88-11ea-94d9-02cc53b1869c.png)
![image](https://user-images.githubusercontent.com/57115301/90036745-fc9c8300-dc88-11ea-8f2a-030f1ea939ac.png)
Closing this bug, the party bar remains after adding items to my cart
