### ISSUE TITLE
Mobile- Iphone- menus overlap each other- hard to read 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#224]
### Expected behavior
When on mobile- I would expect that when you open an menu, that they should open so that you can see all of the details and they are legible to read 

Seems to work on Samsung- 
![image](https://user-images.githubusercontent.com/57115301/89106675-5a131300-d3f1-11ea-89fe-af7aa62cf463.png)

### Actual behavior
I tried Iphone 11 max pro and  7 and got same results when you expand menu the contents get merged into whatever is listed below it. See screen shots. 

Before you open - menu- 
![image](https://user-images.githubusercontent.com/57115301/89106594-c4778380-d3f0-11ea-9a2d-0f0890ce7274.png)

When you open meal prep menu- 
![image](https://user-images.githubusercontent.com/57115301/89106599-d0634580-d3f0-11ea-95bb-69e654abbdfa.png)
When you open products menu- 
![image](https://user-images.githubusercontent.com/57115301/89106603-dc4f0780-d3f0-11ea-87c4-f3208bfd5291.png)
When you open sales& specials menu-
![image](https://user-images.githubusercontent.com/57115301/89106616-ef61d780-d3f0-11ea-81a3-8e2ceaee0ead.png)
When you open cooking styles& ingredients
![image](https://user-images.githubusercontent.com/57115301/89106626-01dc1100-d3f1-11ea-96e2-c0004e6ff664.png)
When you open gifts menu- 
![image](https://user-images.githubusercontent.com/57115301/89106628-0acce280-d3f1-11ea-8f94-6adda7aba46d.png)

not attached to party- it does the same thing-
![image](https://user-images.githubusercontent.com/57115301/89106588-bb86b200-d3f0-11ea-88f6-680e20bb20b1.png)

### Steps to reproduce behavior

Mobile -  seems to not play nice on iphones I checked 11 pro max  and iphone 7 
go to meun
open menu
You will see that when it opens it doesn't display correctly

**Comment by wbyrnetx** [comment]
Got this assigned out to Jen [TST-144](https://razoyo.atlassian.net/browse/TST-144)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/89461650-dda26c00-d731-11ea-9db8-29083804e691.png)
![image](https://user-images.githubusercontent.com/57115301/89461674-e6933d80-d731-11ea-8215-2715888a2bbc.png)
![image](https://user-images.githubusercontent.com/57115301/89461748-06c2fc80-d732-11ea-83b6-b5a2227b884f.png)
![image](https://user-images.githubusercontent.com/57115301/89461775-0f1b3780-d732-11ea-8344-bddca4b18b21.png)
![image](https://user-images.githubusercontent.com/57115301/89461813-180c0900-d732-11ea-845e-6523b6f864e2.png)

Looks good- closing
