### ISSUE TITLE
Mobile- Home page- most items on the Home page are not centered

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#225]
### Expected behavior
I would expect that when I click to the home page on mobile that it would be centered. 

### Actual behavior
When you click on the Tastefully Simple Logo at the top you are take to the Home page, but the Home page is all off center. 
Below Samsung 10+ 
![image](https://user-images.githubusercontent.com/57115301/89109156-47eea000-d404-11ea-969c-beb9273946c8.png)
![image](https://user-images.githubusercontent.com/57115301/89109159-4d4bea80-d404-11ea-850f-686db5832dbe.png)
![image](https://user-images.githubusercontent.com/57115301/89109162-51780800-d404-11ea-9267-6887dce5af56.png)
![image](https://user-images.githubusercontent.com/57115301/89109165-563cbc00-d404-11ea-896f-e9e463e272c8.png)

Below iPhone 11 Pro Max
![image](https://user-images.githubusercontent.com/57115301/89109205-cf3c1380-d404-11ea-9026-82dfc9b66273.png)
![image](https://user-images.githubusercontent.com/57115301/89109209-d2370400-d404-11ea-80cb-8e7c38f57335.png)
![image](https://user-images.githubusercontent.com/57115301/89109211-d6fbb800-d404-11ea-8e9e-5af95837030d.png)
![image](https://user-images.githubusercontent.com/57115301/89109213-db27d580-d404-11ea-92ab-28aa001e3384.png)

### Steps to reproduce behavior
Mobile- Samsung 10+ and iPhone 11 Pro Max 
when you click on the TS logo at the top, you are taken to the home page
and you can see that the page is not centered, images and verbiage is off.

**Comment by staciejurczak** [comment]
@monicakarnes 
1.  Homepage is broken on TechSandbox and will discuss on 8/3 Daily Scrum

**Comment by wbyrnetx** [comment]
We discussed the homepage in standup yesterday. This something that is going to have to be sync'ed. @monicakarnes I'm thinking this one should not be assigned to me. If there's something you need us to do, just let me know.

**Comment by TastefullySimple** [comment]
Fixed by syncing all elements from the marketing sandbox.

**Comment by suehamre** [comment]
8-13 SH - Jen fixed the issue with the wrong homepage displaying, so now seeing the correct homepage and it looks good on both iphone and samsung.
