### ISSUE TITLE
Mobile- No Party Bar on home page for iPhone

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#226]
### Expected behavior
On Mobile- iPhone 11 Pro Max-- I would expect to see the party bar like I do on Samsung  10 + 

### Actual behavior
 I don't see the party bar on the Home page 
iPhone 11 Pro Max
![image](https://user-images.githubusercontent.com/57115301/89109205-cf3c1380-d404-11ea-9026-82dfc9b66273.png)
![image](https://user-images.githubusercontent.com/57115301/89109209-d2370400-d404-11ea-80cb-8e7c38f57335.png)

I see it on the Samsung 10+ 
![image](https://user-images.githubusercontent.com/57115301/89109159-4d4bea80-d404-11ea-850f-686db5832dbe.png)
![image](https://user-images.githubusercontent.com/57115301/89109162-51780800-d404-11ea-9267-6887dce5af56.png)

### Steps to reproduce behavior

Mobile- iPhone- click on the TS logo at the top of the page
This should take you to the Home page and you should see the party bar

**Comment by staciejurczak** [comment]
@monicakarnes 
1.  Homepage is broken on TechSandbox and will discuss on 8/3 Daily Scrum

**Comment by wbyrnetx** [comment]
We discussed the homepage in standup yesterday. This something that is going to have to by sync'ed. @monicakarnes I'm thinking this one should not be assigned to me. If there's something you need us to do, just let me know.

**Comment by TastefullySimple** [comment]
The home sync was fixed on Friday 8/7/2020

**Comment by suehamre** [comment]
8-13 SH - Per conversation the party bar shows in the menu on mobile.
