### ISSUE TITLE
Consultant name in Sticky Header - messed up when you scroll page down 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#229]
### Expected behavior
When you scroll the page down to  see contents of the cart, the details for the consultant in your header should still be readable

### Actual behavior
When you scroll down to see contents of cart or go check out, the Sticky header comes with your but the Consultant information is messed up in the upper right corner 

before I scroll 
![image](https://user-images.githubusercontent.com/57115301/89348688-9bfebc00-d672-11ea-9438-d0fa94d36265.png)

after I scroll 
![image](https://user-images.githubusercontent.com/57115301/89348741-b3d64000-d672-11ea-9a22-37b0f8514e32.png)

### Steps to reproduce behavior
Go to site
find a consultant, select consultant
add item to cart
scroll down to check out
see the sticky header is messed up with consultant info as displayed

**Comment by jsmnglng-w** [comment]
This issue is being fixed now, and included in this Razoyo ticket: https://razoyo.atlassian.net/browse/TST-149

**Comment by monicakarnes** [comment]
fixed - closing
![image](https://user-images.githubusercontent.com/57115301/89821812-cf2ec880-db14-11ea-817a-096cce9576f5.png)
