### ISSUE TITLE
Client order confirmation email  - Consultant info listed

### ISSUE THREAD

**Issue by Denise219** [tastefully-simple/cornerstone#23]
### Expected Behavior:

After placing an order the client receives the order confirmation email to their entered email address.
The Consultant listed in the email should have the consultant information that was selected during shopping.
Here is an image of what we see today.
![image](https://user-images.githubusercontent.com/57686045/71995652-891d2980-3200-11ea-9d5a-06178c51fde1.png)
The Consultant in this scenario is Betty Evans

1. Under the Order Date - consultant should appear
Order date: 12/09/2019  
Consultant: Betty Evans

2. We would also want her Consultant ID number and the email address on file to display as it does today.
Sincerely,
Betty Evans
Your Independent Tastefully Simple Consultant
ID# 0000028
Email: snowfrid@yahoo.com 

3. In this message area we would also include the consultant email address.
If you have any questions about your order, hosting a party or starting your own business, please feel free to email me at
snowfrid@yahoo.com » 

4. Nice to have if possible.  Date formatting changed to 
Order date: 01/06/2020  instead of Order date: 06th Jan 2020

### Actual behavior
The received order confirmation email populates with Tastefully Simple email: help@tastefullysimple.com 
I had picked a different consultant when shopping. (consultant name Dawn Stewart)

### Steps to reproduce behavior
Place an order and view the order confirmation email.

**Comment by mandi920** [comment]
As long as we are using Social Bug this likely will not be possible. Work around is to create a journey in SalesForce to send them messages after. Otherwise this is also already being accomplished with the 2-4-6 journey.
