### ISSUE TITLE
Party is associated to wrong consultant

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#232]
### Expected behavior
I selected a party from the modal, and it updated in the cart and header and should have gone under CID#28. 

### Actual behavior
My order went under the TS consultant, CID#160785, even though I selected 'Sue's test' party that is under CID#28. 
Big C order #824 TSN order #26949355
![image](https://user-images.githubusercontent.com/57115316/89452153-d3c53c80-d722-11ea-84e9-bdbe08ebeaeb.png)
Looks like the party ID is correct, but under the wrong consultant. 
![image](https://user-images.githubusercontent.com/57115316/89452295-096a2580-d723-11ea-9f0d-10c1c092f58b.png)
![image](https://user-images.githubusercontent.com/57115316/89452326-15ee7e00-d723-11ea-8e13-66ba2517aecc.png)

### Steps to reproduce behavior
Add items to cart
Select party from modal 
Checkout

**Comment by wbyrnetx** [comment]
Looking at this one.

**Comment by jsmnglng-w** [comment]
Checked on the cookies being updated when selecting a party, and the Consultant Name and ID cookies are being updated, but found that the consultant ID from the API response is `null`. This response is coming from `/search/party/{state}/{page}/{size}?name={name}`

![Screen Shot 2020-08-06 at 10 58 53 AM](https://user-images.githubusercontent.com/69249028/89554675-c9637b00-d7d4-11ea-815b-c70fdd991e91.png)

**Comment by jsmnglng-w** [comment]
The API has been updated and returning the consultant IDs. The party should be associated to the right consultant now.
![Screen Shot 2020-08-06 at 3 11 46 PM](https://user-images.githubusercontent.com/69249028/89578176-61725c00-d7f7-11ea-8f49-20c27040168c.png)

**Comment by TastefullySimple** [comment]
Ready for testing

**Comment by suehamre** [comment]
8-7 SH  Fixed.
