### ISSUE TITLE
Change of consultant, Didn't drop my party who is under a different consultant

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#233]
### Expected behavior

If I am currently associated to a party host and a consultant, and I choose to edit my consultant, The consultant should update as I have selected, and they party host would drop and no longer be associated. 

### Actual behavior
My consultant updates as it should, however the Host Party still shows its associated- and it shouldn't 

My party is under consultant Kylie Jo- as you can see listed in myHQ
![image](https://user-images.githubusercontent.com/57115301/89469123-6aebbd80-d73e-11ea-82d9-bb1ec2799d57.png)

![image](https://user-images.githubusercontent.com/57115301/89469366-e51c4200-d73e-11ea-8502-5362f31a9821.png)

You can see I was able to edit my consultant to Jennifer but my Host info still stayed for Alaina's party 
![image](https://user-images.githubusercontent.com/57115301/89469219-9ec6e300-d73e-11ea-8d01-b4cdfe5872b2.png)

### Steps to reproduce behavior
go to site 
find a party and select it to associated
once it updated with Host and Consultant
select to edit your consultant from main page, or from cart page
search for new consultant via find a consultant modal and select
Consultant will update, party info stays the same, but shouldn't as this party is not under this newly selected consultant

**Comment by wbyrnetx** [comment]
Looking at this.

**Comment by jsmnglng-w** [comment]
Created a Razoyo ticket for this issue: https://razoyo.atlassian.net/browse/TST-152

**Comment by monicakarnes** [comment]
So, it did remove me from the party, but now it also sits here and spins and it shouldn't do that. 

I had selected a party- then on the same page went in and changed my consultant, it dropped the party, but it shouldn't stay and spin here. 
![image](https://user-images.githubusercontent.com/57115301/89662665-0ba2c000-d89a-11ea-8ed0-40eefed5db52.png)

**Comment by wbyrnetx** [comment]
Brought this one up in standup today. We need to know what to show instead of the grey loading box whenever you do not have a party selected (i.e., cleared out after changing consultant). Normally the content that appears there is the party details, so in this scenario, we do not have party details to siplay.

**Comment by suehamre** [comment]
@wbyrnetx , We just discussed this and would like the user to be brought to the home page when the party has been dropped.

**Comment by wbyrnetx** [comment]
Code for this is written and will be in the next PR (see c02f7)

**Comment by monicakarnes** [comment]
Fixed, now it did drop my party as it should when I flipped consultants. AND it took me back to home page so its not sitting and spinning anymore. 
![image](https://user-images.githubusercontent.com/57115301/90039370-26a37480-dc8c-11ea-9005-d4d2207e2c82.png)
