### ISSUE TITLE
Consultant webpage is displaying past parties that have been closed from 2007 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#235]
### Expected behavior
The consultants webpage past parties section should only display the past 30 days of open parties. 

### Actual behavior
The consultants webpage is displaying parties from 2007 that are closed, and not my recent parties that are still open within the last 30 days.  This is under Cons ID #28
![image](https://user-images.githubusercontent.com/57115316/89582425-393a2b80-d7fe-11ea-832d-59a53936ad15.png)
![image](https://user-images.githubusercontent.com/57115316/89582723-b6fe3700-d7fe-11ea-91b9-ff6abde55171.png)
Parties that should be displayed: 
![image](https://user-images.githubusercontent.com/57115316/89582981-270cbd00-d7ff-11ea-9889-ae70a49fdfa5.png)

### Steps to reproduce behavior
Need to have parties set up on your consultant in myHQ. 
Go to website in big commerce and view the consultants webpage and past parties section.

**Comment by jsmnglng-w** [comment]
This looks like an API issue. Going to `consultant/parties?cid=0000028`, I only get the party results from the Past tab last 2007

![Screen Shot 2020-08-07 at 8 16 15 AM](https://user-images.githubusercontent.com/69249028/89650322-e016da00-d887-11ea-91f3-e5930b17739e.png)

**Comment by richierubin** [comment]
Added filterPartyDateAfter parameter for 30 days, PR requested

**Comment by suehamre** [comment]
8/10 SH - Fixed.
