### ISSUE TITLE
Consultant webpage - Open parties not displaying under 'attend' 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#236]
### Expected behavior
Open parties should be displayed under the 'attend' tab under my parties. 

### Actual behavior
Open parties are not being displayed under the 'attend' tab. Example below. Consultant ID #505 has a few open parties for August and her webpage shows none. 
![image](https://user-images.githubusercontent.com/57115316/89583706-6a1b6000-d800-11ea-8d85-30e1691a2cd0.png)
![image](https://user-images.githubusercontent.com/57115316/89583720-71db0480-d800-11ea-8597-1307497cd7ed.png)

### Steps to reproduce behavior
Create open parties in myHQ.
View consultant webpage in website/big commerce.

**Comment by TastefullySimple** [comment]
This might be an API issue.

**Comment by jsmnglng-w** [comment]
Tested ConsultantID#505, and I'm getting 1 result from the API
![Screen Shot 2020-08-07 at 8 22 00 AM](https://user-images.githubusercontent.com/69249028/89649969-3fc0b580-d887-11ea-8ba2-c5a879b6205d.png)

**Comment by richierubin** [comment]
Fix associated with #235 has also fixed this issue.

![image](https://user-images.githubusercontent.com/66743596/89690342-e29b2300-d8cb-11ea-98e3-4a10155d080a.png)

**Comment by suehamre** [comment]
8-10 SH -  Fixed.
