### ISSUE TITLE
Guest is unable to join using Safari on a MAC

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#237]
**Summary of issue:** 
Guest is unable to join using Safari on a MAC because the birthdate field is grayed out and won't let them fill it in. 
Troubleshooting steps taken:  Instructed the users to switch to Google Chrome and it worked but its not the best experience.
Steps taken to reproduce:  I do not have access to a MAC with Safari and my iphone uses the mobile site so its not a true test.
Specific examples (attach screen shots if available): 

**Additional notes:**
I have at least two people attempting to sign up and experiencing countless system issues. The birthday section is grayed out (see attached photo) and she cannot enter. She had been trying to join since last night. I told her not to use IE and recommended Chrome.

**She kept getting this issue using the following devices:**
Tablet, Phone, and Desktop computer - tried using Firefox and Chrome (all failed)
She finally got it to work by using her laptop in conjunction with Google Chrome.

![image](https://user-images.githubusercontent.com/57953952/89587659-a900e400-d807-11ea-8ae1-30d7e2ef2f5f.png)

More Info
Another person tried using Safari browser on their MAC and got the same issue.
Both people were able to Join using Chrome on a Chromebook/laptop only 

### Steps to reproduce behavior
Using Safari on a Mac go to tastefullysimple.com on our live site. Click Join us. Click Get Started Now. On the Ready to Join? page move the slider over to Sign up. Fill out the fields and click next>. On the What comes in your kit page click next>. On the Tell us about yourself page

**Comment by jsmnglng-w** [comment]
Created a Razoyo ticket for this issue: https://razoyo.atlassian.net/browse/TST-153

**Comment by suehamre** [comment]
8-11 SH - Retested this today using browser stack, Mac with a few different options. The birth date field is not greyed out and I am able to type in it. However, it does not applying the formatting and the calendar is missing. See screenshot below: 
![image](https://user-images.githubusercontent.com/57115316/89922961-710dee00-dbc5-11ea-8e21-54fe5b268677.png)
I am able to get past it if I correct the formatting. Should a new bug be logged?

**Comment by staciejurczak** [comment]
@suehamre 
8/10/20 testing resulted in formatting on Mac via Safari 
![image](https://user-images.githubusercontent.com/65304780/89931929-82112c00-dbd2-11ea-859f-eef61d1267e1.png)

8/11/20 testing won't show API results to replicate today.  This is as far as I'm able to get to replicate.  
![image](https://user-images.githubusercontent.com/65304780/89932055-a967f900-dbd2-11ea-9a1e-9c52fa43b357.png)

**Comment by mandi920** [comment]
@suehamre yep lets close this bug and enter a new one for the formatting and calendar.
