### ISSUE TITLE
Consultant Web page- After I select my cover photo it's Not updating my cover photo

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#238]
### Expected behavior
As a consultant I should be able to select a cover photo for my web page

### Actual behavior
When I select a cover photo and click to save to my website it says it saves and my page is updated However the Cover image is the same one every time. 
![image](https://user-images.githubusercontent.com/57115301/89590550-c6d14780-d80d-11ea-82d4-b7a63edd214d.png)

![image](https://user-images.githubusercontent.com/57115301/89590594-e2d4e900-d80d-11ea-8e8c-3f81a6f51f5e.png)

![image](https://user-images.githubusercontent.com/57115301/89590612-eec0ab00-d80d-11ea-8814-efbb8cfbeeae.png)

### Steps to reproduce behavior
Consultant logs into myHQ
Market my Business,Customize my Webpage, About me, Cover Photo
Select one of the radio buttons to choose your image
click Save to update your webpage

**Comment by richierubin** [comment]
Jared looked at this and change Karen's image and it worked across the systems.

**Comment by monicakarnes** [comment]
This is still broken, I'have selected the top image with pickles and chicken legs ..... and clicked on save....
![image](https://user-images.githubusercontent.com/57115301/90449250-a1b1c400-e0ac-11ea-9873-224eaf7ebe75.png)

And it still shows me the image that is show in Shogun the shot glass of veggies, with the meatballs 
![image](https://user-images.githubusercontent.com/57115301/90449307-c4dc7380-e0ac-11ea-91e8-e3f912455618.png)

**Comment by TastefullySimple** [comment]
@monicakarnes We need more details. What consultant are you testing with?

**Comment by monicakarnes** [comment]
@TastefullySimple  I've tried with Consultant ID # 2051 Stephanie Cone which is the screen shots you see above..... I've also tried with Consultant Kylie Jo Consultant ID# 187769 and with both of these it seems like once I have clicked save it shows the pop up box that my website has been updated but when I go to check my actual web page it still showing the same one image from Shogun.

**Comment by TastefullySimple** [comment]
This is ready for testing.

**Comment by monicakarnes** [comment]
We are closing this one for now, and will come back to it in prioritization
