### ISSUE TITLE
Party Search returns incorrect results 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#239]
### Expected behavior
When searching for a party by state and name, the results should match the state and name entered. 

### Actual behavior
Searched for a party in Minnesota with the first name of Denise and got the following results: 
![image](https://user-images.githubusercontent.com/57115316/89592272-d05cae80-d811-11ea-9c35-4ee54725ba2a.png)

### Steps to reproduce behavior

Click on find a party
Search by state MN and name Denise

**Comment by suehamre** [comment]
8-17 SH - Still getting the same results listed above.

**Comment by TastefullySimple** [comment]
I'm seeing 2 pages. Cache issue. Ctrl + f5. Then search again.
![image](https://user-images.githubusercontent.com/53190431/90408182-20870c80-e06d-11ea-87ae-11a84459a543.png)

![image](https://user-images.githubusercontent.com/53190431/90408207-28df4780-e06d-11ea-99b7-1ec44b11a239.png)

**Comment by suehamre** [comment]
8-17 SH - I cleared cookies and still get the same results. :( 
![image](https://user-images.githubusercontent.com/57115316/90410671-44981d00-e070-11ea-9abb-60c0eb3b45e1.png)
![image](https://user-images.githubusercontent.com/57115316/90410690-495cd100-e070-11ea-8e6f-b3294a2f15db.png)

**Comment by TastefullySimple** [comment]
@suehamre most detail is needed. What results are missing?

**Comment by suehamre** [comment]
Jared, sorry..if I was not clear on the issue. Today, if I search by state and first name, I get only the results that match that first name in that state.  
![image](https://user-images.githubusercontent.com/57115316/90433704-de23f680-e091-11ea-80e9-749d3e52de2a.png)
If there are no parties matching the name, I should get the 'no results found' message: 
![image](https://user-images.githubusercontent.com/57115316/90433745-f1cf5d00-e091-11ea-9a27-3d12044bc5bb.png)
I did verify if there were results matching in QA1 for the name and state only those results displayed: 
![image](https://user-images.githubusercontent.com/57115316/90433802-0c093b00-e092-11ea-944b-12342306a9f8.png)
So, I guess the bug is actually that we are not receiving the no match found if there are no parties matching the name entered. Instead it is just displaying all results for the state.

**Comment by suehamre** [comment]
8-18 SH - Fixed. :)
