### ISSUE TITLE
Consultant Web page - My phone, and email address 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#240]
### Expected behavior
As a Consultant I should be able to updated if I would like my phone number and my email address to display on my webpage. 

### Actual behavior
If I select to remove my phone number and email address, it doesn't remove them... and looks like its not even the correct information that is being displayed. 
Here is my information via TSN
![image](https://user-images.githubusercontent.com/57115301/89595848-3a2d8600-d81b-11ea-9c5c-b19d11e3af3b.png)

Here is what I see on my webpage
![image](https://user-images.githubusercontent.com/57115301/89595908-79f46d80-d81b-11ea-8ecb-b204f2d2c2bf.png)

Here is where I clicked to remove them 
![image](https://user-images.githubusercontent.com/57115301/89595939-92fd1e80-d81b-11ea-9871-ec5756b37523.png)

### Steps to reproduce behavior
Consultant logs into myHQ
Market my Business,Customize my Webpage, About me, Contact information
uncheck phone or email checkbox, or both
click Save to update your webpage

**Comment by jsmnglng-w** [comment]
This looks like an API issue. Going to `consultant/info?cid=0187769`, the phone number and email address are empty strings

![Screen Shot 2020-08-07 at 8 33 14 AM](https://user-images.githubusercontent.com/69249028/89651018-dcd01e00-d888-11ea-8dda-842f1db4c1d5.png)

**Comment by richierubin** [comment]
The API will return empty string values for Phone and Email when they're to be hidden.
The values are displaying as 888-888-8888 and help@ because they're hardcoded in consultant-detail.js.

![image](https://user-images.githubusercontent.com/66743596/89686101-4ec55900-d8c3-11ea-8b31-80852371080b.png)

**Comment by monicakarnes** [comment]
then the phone number should be 866-448-6446  as this will bring them to Customer Service

**Comment by jsmnglng-w** [comment]
Created a Razoyo ticket for this issue: https://razoyo.atlassian.net/browse/TST-156

**Comment by TastefullySimple** [comment]
@jsmnglng-w @monicakarnes comment is not correct. When no phone number or email address is returned nothing should be shown.

**Comment by monicakarnes** [comment]
fixed, thanks! 
![image](https://user-images.githubusercontent.com/57115301/90041145-7edb7600-dc8e-11ea-9317-deb2cf1095bc.png)
