### ISSUE TITLE
Join path - system is directing user to cart page vs step one of checkout

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#241]
### Expected behavior
On the join path when the user clicks checkout from the personal information page they should be brought to step 1 of checkout. 

### Actual behavior
On the join path when the user clicks checkout from the personal information page they are brought to the cart page. 
![image](https://user-images.githubusercontent.com/57115316/89651841-29682900-d88a-11ea-827f-628c093e925b.png)
![image](https://user-images.githubusercontent.com/57115316/89651854-2f5e0a00-d88a-11ea-8462-17152304018a.png)

### Steps to reproduce behavior
Navigate through the join path to checkout on the personal information page.

**Comment by jsmnglng-w** [comment]
Created a Razoyo ticket for this issue: https://razoyo.atlassian.net/browse/TST-153

**Comment by suehamre** [comment]
8-10 SH - Fixed.

**Comment by suehamre** [comment]
8-11 SH - Tested again this morning and am now being brought to the cart page again. :( 
![image](https://user-images.githubusercontent.com/57115316/89904579-ba067800-dbae-11ea-9a2c-296d302bdb67.png)

**Comment by jsmnglng-w** [comment]
@suehamre I tested it in [Tech Sandbox](https://tastefully-simple-sandbox-2.mybigcommerce.com/) and it brings me to the checkout page after clicking the checkout button.
![Screen Shot 2020-08-12 at 10 56 44 AM](https://user-images.githubusercontent.com/69249028/90038069-944ea100-dc8a-11ea-973f-6cd51c6d8232.png)

**Comment by suehamre** [comment]
8-12 SH - I was also brought to the checkout page. Closing bug again. :)
