### ISSUE TITLE
Mobile -Client account - Recently viewed tab is displayed and should be hidden 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#242]
### Expected behavior
The recently viewed tab should be hidden in the clients account.

### Actual behavior
On a mobile device when logged into a client account the recently viewed tab is displayed: 
![image](https://user-images.githubusercontent.com/57115316/89676858-fcc80780-d8b1-11ea-9532-df711b37fb47.png)

### Steps to reproduce behavior
I am using browser stack to test on a mobile device, tested Samsung S10+ and Iphone 11 Pro. 
Login into client account and view menu:

**Comment by staciejurczak** [comment]
@suehamre looking at this one to replicate.

**Comment by wbyrnetx** [comment]
Code for this is written and will be in the next PR (see 3e1300)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/90044584-73d71480-dc93-11ea-9e68-59ac4d5fe63b.png)
fixed closing
