### ISSUE TITLE
Mobile - Communication preferences tab is missing 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#243]
### Expected behavior
When logged into a client account on a mobile device I should see the communication preferences tab in the menu. 

### Actual behavior
When logged into a client account on a mobile device I am not seeing the communication preferences tab in the menu. 
![image](https://user-images.githubusercontent.com/57115316/89677304-d060bb00-d8b2-11ea-9d42-36d19c414168.png)

### Steps to reproduce behavior
Using Browser Stack - Tested Samsung S10+ and iphone11 Pro
Login to client account.
View menu dropdown

**Comment by wbyrnetx** [comment]
Code for this is written and will be in the next PR (see 3e1300)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/90044360-29559800-dc93-11ea-8418-0537547cc300.png)
![image](https://user-images.githubusercontent.com/57115301/90044401-35d9f080-dc93-11ea-9617-da73335a889e.png)
 
fixed - closing
