### ISSUE TITLE
Find a cons modal - Consultants photos are not displayed 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#244]
### Expected behavior
When searching for a consultant and the results are displayed, if the consultant has a photo uploaded it should display. 

### Actual behavior
When searching for a consultant and the results are displayed, if the consultant has a photo uploaded it does not display on the results: 
![image](https://user-images.githubusercontent.com/57115316/89682373-3b62bf80-d8bc-11ea-99b1-8037292b8d2d.png)
You can see if you view this consultants webpage CID#505 Dawn Stewart she has a photo uploaded. 
![image](https://user-images.githubusercontent.com/57115316/89682506-75cc5c80-d8bc-11ea-9e2e-8af73bacaeee.png)

### Steps to reproduce behavior
Click on find a consultant. 
Searched by State Wisconsin and first name Dawn
View results

**Comment by staciejurczak** [comment]
Reviewed with Jasmine and I sent inquiry to Jared in slack if this should have an API tag.

**Comment by richierubin** [comment]
Changed image base URL to use 'tso.tastefullysimple....' instead of the sandbox url.  This new URL will be used for all environments, per Jared

**Comment by suehamre** [comment]
8-11 SH - fixed
