### ISSUE TITLE
Consultant webpage- phone number formatting 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#245]
### Expected behavior
Phone number should be formatted for easier to read  we need to add - or . to separate it out
 
Here is what it does in prod today 
![image](https://user-images.githubusercontent.com/57115301/89690985-77525080-d8cd-11ea-8884-077b8009c6a5.png)

### Actual behavior
Here is what I see 
![image](https://user-images.githubusercontent.com/57115301/89690876-32c6b500-d8cd-11ea-8021-3dec344fe6d5.png)

**Comment by jsmnglng-w** [comment]
Including this fix in https://razoyo.atlassian.net/browse/TST-156

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/90041031-58b5d600-dc8e-11ea-904d-b2bf9f80eb18.png)

Fixed- thanks
