### ISSUE TITLE
Consultant Details - remove incorrect/test hardcoded values

### ISSUE THREAD

**Issue by richierubin** [tastefully-simple/cornerstone#247]
Cornerstone project:  **consultant-details.js**
Names should be 'Tastefully Simple' if not otherwise set.

![image](https://user-images.githubusercontent.com/66743596/89803889-0becc680-daf9-11ea-9601-916d5134a4cf.png)

![image](https://user-images.githubusercontent.com/66743596/89803113-08a50b00-daf8-11ea-8029-f9b37a6af871.png)

Use environment specific domain URL, not the hardcoded production URL
Just a thought:  Can this No Consultant image be added to BigCommerce and just reference it from there?  Everyone uses the same image, regardless of environment.

![image](https://user-images.githubusercontent.com/66743596/89803788-e790ea00-daf8-11ea-864d-bbee2584383f.png)

**Comment by jsmnglng-w** [comment]
Created a Razoyo ticket for this issue: https://razoyo.atlassian.net/browse/TST-157

**Comment by wbyrnetx** [comment]
@richierubin can you specify what you want instead of:
"Testing Shop or Host with me headline"

We will add the noconsultant image to the theme and just reference it that way.

**Comment by jsmnglng-w** [comment]
@richierubin The script for the Consultant page is written in Shogun via custom elements. It's in **Consultant page - script** file

Got to change the default value for the **Consultant Name** to "Tastefully Simple". But still need clarification on what should be the default value for the **Headline**
![Screen Shot 2020-08-12 at 11 38 58 AM](https://user-images.githubusercontent.com/69249028/90042716-a6cbd900-dc90-11ea-93c9-b8caa7b39579.png)

---

For the **noconsultant** image, here's how we did it with Shogun:

In the custom element for the basic info section, we added a `no_consultant_photo` variable and changed its value type to `Image (URL)` to have the ability to upload an image. We applied that variable in the `onerror` attribute.

![Screen Shot 2020-08-12 at 10 38 03 AM](https://user-images.githubusercontent.com/69249028/90043114-412c1c80-dc91-11ea-9bcf-801555311045.png)

Then in the Shogun editor, you can upload any image you want in the `no_consultant_photo` field
![Screen Shot 2020-08-12 at 10 37 13 AM](https://user-images.githubusercontent.com/69249028/90043221-72a4e800-dc91-11ea-95a2-b62c9758b3ed.png)
![Screen Shot 2020-08-12 at 10 37 41 AM](https://user-images.githubusercontent.com/69249028/90043286-82bcc780-dc91-11ea-8491-fbe1b620d7aa.png)

In the script, we changed this code
```javascript
var imgError =
            "this.onerror=null;" +
             "this.src='https://www.tastefullysimple.com/_/media/images/noconsultantphoto.png';";

$img.setAttribute('onerror', imgError);
```

To this, to account for when there's an image coming from the API or not
![Screen Shot 2020-08-12 at 11 49 07 AM](https://user-images.githubusercontent.com/69249028/90043543-de875080-dc91-11ea-9def-0dc518148268.png)

**Comment by wbyrnetx** [comment]
<img width="1060" alt="Screen Shot 2020-08-13 at 11 02 15 AM" src="https://user-images.githubusercontent.com/4029452/90151265-86fde900-dd54-11ea-95a2-08f4c5815b87.png">
This is the headline.

**Comment by wbyrnetx** [comment]
@jsmnglng-w we have decided to hide the headline if you don't get a value from the API.

**Comment by jsmnglng-w** [comment]
Removed the default value for the headline when you don't get any value from the API
![Screen Shot 2020-08-13 at 10 13 26 AM](https://user-images.githubusercontent.com/69249028/90152727-bfe68f80-dd4d-11ea-87f3-b5a00b9bac4a.png)

**Comment by TastefullySimple** [comment]
@jsmnglng-w, @wbyrnetx has this fix being included in a PR?  Or no PR needed shogun widget change?

**Comment by jsmnglng-w** [comment]
@TastefullySimple no PR needed. It's in Shogun widget (file name: **Consultant page - script**)

**Comment by wbyrnetx** [comment]
Can this be closed now?

**Comment by monicakarnes** [comment]
With no image uploaded, and only the default of Consultant homepage headline- which is " hello there!"-Then nothing shows on the webpage. 
![image](https://user-images.githubusercontent.com/57115301/91057496-e1b50180-e5ec-11ea-8901-279de3c2546c.png)
![image](https://user-images.githubusercontent.com/57115301/91057774-483a1f80-e5ed-11ea-9d88-1738bbe58adc.png)


However if they don't upload an image, but they do update the Consultant homepage headline- it did display as what was entered. Which is good, and what I would have expected to happen. 
![image](https://user-images.githubusercontent.com/57115301/91059029-d367e500-e5ee-11ea-8ed5-e06820716e68.png)
![image](https://user-images.githubusercontent.com/57115301/91059057-dbc02000-e5ee-11ea-842b-40e9f7a80dbc.png)

Fixed, closing - thanks
