### ISSUE TITLE
Find a consultant and find a host or party is not working

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#248]
### Expected behavior
Find a cons and find a host or party should return results. 

### Actual behavior
Find a consultant & Find a host or party is not returning any results. 
### Steps to reproduce behavior
Search either find a consultant or find a host or party.

**Comment by staciejurczak** [comment]
Reconfirming bug from Razoyo 

![Screen Shot 2020-08-10 at 11 38 59 AM](https://user-images.githubusercontent.com/65304780/89807595-78b68f80-dafe-11ea-9de4-7731b38220b3.png)
![Screen Shot 2020-08-10 at 11 43 43 AM](https://user-images.githubusercontent.com/65304780/89807797-c6cb9300-dafe-11ea-92bc-08cbb952db30.png)

**Comment by TastefullySimple** [comment]
Internal database issues.
