### ISSUE TITLE
Find a consultant modal  - Search results  - User has to click on the image now to select consultant

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#249]
### Expected behavior
On the find a consultant search results, we should be able to click anywhere in the box to select the consultant. 
![image](https://user-images.githubusercontent.com/57115316/89825656-8548e100-db1a-11ea-837f-5a8895e74f7e.png)

### Actual behavior
User has to click on the photo image to select the consultant. 

### Steps to reproduce behavior
Click find a consultant
Search
View results and attempt to select the consultant by clicking anywhere in the box.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: https://razoyo.atlassian.net/browse/TST-159

**Comment by suehamre** [comment]
8-12 SH  - Fixed.
