### ISSUE TITLE
Mobile - Party Bar is GONE

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#250]
### Expected behavior
Party Bar is expected to be on all pages- (only exception is of the Join Path pages). 

### Actual behavior
I am only seeing the Party bar on the Menu page, it is no longer appearing on any other page and should be. 

iPhone 
![image](https://user-images.githubusercontent.com/57115301/89831807-0a84c380-db24-11ea-968b-f992d27b5139.png)
![image](https://user-images.githubusercontent.com/57115301/89831819-12446800-db24-11ea-890f-18a9305468da.png)
![image](https://user-images.githubusercontent.com/57115301/89831851-1ec8c080-db24-11ea-95a4-4b2c8055279d.png)
![image](https://user-images.githubusercontent.com/57115301/89831861-24260b00-db24-11ea-9652-8fbf9bbc649f.png)

Samsung 
![image](https://user-images.githubusercontent.com/57115301/89831882-2e480980-db24-11ea-917c-4ef5c8c28684.png)
![image](https://user-images.githubusercontent.com/57115301/89831890-32742700-db24-11ea-87c6-d43854f6a0d7.png)
![image](https://user-images.githubusercontent.com/57115301/89831900-37d17180-db24-11ea-9357-14ddce7ab07b.png)
![image](https://user-images.githubusercontent.com/57115301/89831921-3dc75280-db24-11ea-8df8-f8398415b2e6.png)

**Comment by TastefullySimple** [comment]
Not a bug matches the mock up
