### ISSUE TITLE
Photos are no longer appearing on the site 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#253]
### Expected behavior
On the find a consultant search results and the consultants webpage, if the consultant has a photo uploaded it should display. 

### Actual behavior
when viewing the consultant search results and wepages for consultants that have photos they are not displayed. 
![image](https://user-images.githubusercontent.com/57115316/90032207-bbee3b00-dc83-11ea-92c1-ca13c85f936b.png)
![image](https://user-images.githubusercontent.com/57115316/90032225-c27cb280-dc83-11ea-8532-547c88fcfff3.png)

Not sure if this is related, but in myHQ photos are not appearing either. For example the cover photos. See below: 
![image](https://user-images.githubusercontent.com/57115316/90032306-db856380-dc83-11ea-999d-eea6903f9f37.png)

### Steps to reproduce behavior
Execute find a consultant search and view results. 
Click to view a consultants webpage (name in header)
myHQ - Login, go to market my business, and customize webpage, my photo and cover.

**Comment by TastefullySimple** [comment]
This is ready for QA.

**Comment by suehamre** [comment]
8-19 SH - fixed! :)
