### ISSUE TITLE
Mobile- party bar- Arrow down- Don't know its open unless you scroll

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#254]
### Expected behavior
When you click onto the arrow to expand the options for the party, the arrow should move to pointed down and the options should expand and adjust to be seen. 

Mock up
![image](https://user-images.githubusercontent.com/57115301/90037955-6b2e1080-dc8a-11ea-8558-0297a9c6efb5.png)

### Actual behavior
When you click on the arrow to expand the options, it looks like nothing happened unless you scroll down then you are able to see your options to see party details or switch parties. 

Samsung 
![image](https://user-images.githubusercontent.com/57115301/90037677-18545900-dc8a-11ea-9987-c9b65ba0c87a.png)
![image](https://user-images.githubusercontent.com/57115301/90037716-20ac9400-dc8a-11ea-88fc-b0af581ac694.png)

Iphone
![image](https://user-images.githubusercontent.com/57115301/90037783-34f09100-dc8a-11ea-8223-3e50a3146d1d.png)
![image](https://user-images.githubusercontent.com/57115301/90037797-3a4ddb80-dc8a-11ea-9780-561c4a94ba16.png)

### Steps to reproduce behavior
Go to site on mobile
Find a party
Select a party
attempt to see party details or switch parties

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-164](https://razoyo.atlassian.net/browse/TST-164)

**Comment by suehamre** [comment]
8-14 This is still happening for me on Samsung S10+  - Not logged in as a client
![image](https://user-images.githubusercontent.com/57115316/90290083-d7537480-de42-11ea-952b-4a7b08d6c02d.png)
Also, on iphone 11 promax 
![image](https://user-images.githubusercontent.com/57115316/90290247-200b2d80-de43-11ea-8329-8fde78790f8e.png)

If logged in, you can kinda see some of the info under the drop down, this is the same for iphone and samsung
![image](https://user-images.githubusercontent.com/57115316/90290374-652f5f80-de43-11ea-8e41-e7a7c7c9a6eb.png)

**Comment by jsmnglng-w** [comment]
Missed the part that it should adjust the screen as well when showing the options. Will fix that in [TST-164](https://razoyo.atlassian.net/browse/TST-164)

**Comment by monicakarnes** [comment]
**iPhone is still broke**, if you click the arrow it does turn to point down,but screen doesn't resize to show you the details, you still have to scroll to see them. 
iphone 11 ProMax
![image](https://user-images.githubusercontent.com/57115301/90555351-d8471780-e15c-11ea-9c73-a3dd2f92de71.png)

Samsung is fixed- thanks 
![image](https://user-images.githubusercontent.com/57115301/90555423-f1e85f00-e15c-11ea-84db-592fc2c81a21.png)

**Comment by jsmnglng-w** [comment]
Looking into this now

**Comment by monicakarnes** [comment]
fixed, closing- thanks
![image](https://user-images.githubusercontent.com/57115301/90802640-284ce800-e2dd-11ea-937d-072835888924.png)
