### ISSUE TITLE
Party orders are not being affiliated to the party

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#255]
### Expected behavior
When placing a party order on Big C, the order should be affiliated to the party. 

### Actual behavior
I've placed two new party orders today, and the party affiliation is NULL. See screenshots below: 

![image](https://user-images.githubusercontent.com/57115316/90056571-b523f000-dca4-11ea-9595-b18007891e7f.png)
![image](https://user-images.githubusercontent.com/57115316/90056584-ba813a80-dca4-11ea-997b-ccfbdbb2fcb7.png)
both of the above orders should have been affiliated to this party: 
![image](https://user-images.githubusercontent.com/57115316/90056621-cb31b080-dca4-11ea-9f09-4e5f701c359a.png)

### Steps to reproduce behavior
Search for a party, shop and checkout. 
View SQL table. 
FROM [BigCommerce].[dbo].[OrderAffiliation]

**Comment by jsmnglng-w** [comment]
With an initial investigation, I found that after selecting a party, it redirects me to the homepage and changes the party ID value to `undefined`. Created a ticket for this: [TST-165](https://razoyo.atlassian.net/browse/TST-165)

**Comment by suehamre** [comment]
8-14 SH - Placed new order this morning and it is affiliated to the party!
