### ISSUE TITLE
Mobile: Messages tab needs to be hidden and order of tabs is incorrect

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#257]
### Expected behavior
When logged in as a client we wanted the 'messages' tab hidden. And the order of the tabs to be : Profile, Orders, Addresses, Wish Lists, Communication Preferences

### Actual behavior
When logged in as a client on mobile the 'messages' tab is displayed and the order of the tabs is incorrect. See below: 
![image](https://user-images.githubusercontent.com/57115316/90164861-86b61b80-dd5d-11ea-8765-633411c12e1d.png)

DESKTOP Image below - this is the correct order: 
![image](https://user-images.githubusercontent.com/57115316/90164914-96cdfb00-dd5d-11ea-9562-57e3546b1507.png)

### Steps to reproduce behavior

Logged into Browser Stack and viewed the menu logged in as a client on iphone 11 pro max and samsung S10 +

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-167](https://razoyo.atlassian.net/browse/TST-167)

**Comment by suehamre** [comment]
8-14 SH Fixed.
