### ISSUE TITLE
Future parties are not displayed in party search

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#260]
### Expected behavior
All open future parties should be displayed in the party search. 

### Actual behavior
I set up many parties under CID 4287 Judy Zimmerman
Some have Sept and Oct.
When I do the party search by State in Big C for IL
The Sept and Oct parties are not appearing.
![image](https://user-images.githubusercontent.com/57115316/90259075-11a31e80-de0f-11ea-84b1-65277ce3a949.png)

![image](https://user-images.githubusercontent.com/57115316/90259115-21bafe00-de0f-11ea-81f6-ccfc903e722a.png)

### Steps to reproduce behavior
Set up parties in myHQ that have a future date. 
Execute party search in Big C.

**Comment by TastefullySimple** [comment]
This is ready to test

**Comment by suehamre** [comment]
8-17 SH - Fixed
