### ISSUE TITLE
Clicking 'view my webpage' link does not clear out the party selected from previous cons

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#264]
### Expected behavior
When clicking on 'view my webpage' link from the consultant search results the user is brought to the consultants webpage and is affiliated with that consultant. IF the user had a party selected before this that was associated to a different consultant, the party should be cleared from the party bar. 

### Actual behavior
After selecting a party to shop with and then clicking edit for the consultant and clicking on their webpage link, the consultant is updated but the party remains that is associated to previous consultant. 

### Steps to reproduce behavior
Searched for party in MN and selected 'Sue Test's Party' that is under CID#28 Betty Evans. 
Clicked on 'edit' next to the consultant name in the header, and searched for a consultant. When results are returned, click on the 'view my ts page'. User is brought to the consultants webpage and the header is updated, but the party bar still shows shopping in Sue Test's party and should not. 
![image](https://user-images.githubusercontent.com/57115316/90442425-3eba3000-e0a0-11ea-8878-1f58f72d94fb.png)

**Comment by jsmnglng-w** [comment]
Will fix this in [TST-168](https://razoyo.atlassian.net/browse/TST-168)

**Comment by suehamre** [comment]
8-18 SH - Fixed.
