### ISSUE TITLE
Extra Contact Us Link in the Footer

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#266]
### Expected behavior
The contact us link should only be under the support heading.

### Actual behavior
The contact us link is under the support heading now but also still under the about us heading. Please remove the one that is under the about us heading.

### Steps to reproduce behavior
View the footer at the bottom of the website.

**Comment by jsmnglng-w** [comment]
This will be fixed in [TST-158](https://razoyo.atlassian.net/browse/TST-158)

**Comment by TastefullySimple** [comment]
Ready for QA.

**Comment by suehamre** [comment]
8-19 SH - Fixed.
