### ISSUE TITLE
View host planner link in myHQ is going to the wrong page 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#267]
### Expected behavior
When clicking on the view host planner link the user should be brought to the host planner page: https://tastefully-simple-sandbox-2.mybigcommerce.com/host-planner for that party. 

![image](https://user-images.githubusercontent.com/57115316/90535388-74aef100-e140-11ea-9d5e-5474d04d448f.png)

### Actual behavior
When clicking on the view host planner link the user is being brought to the party details page: 
https://tastefully-simple-sandbox-2.mybigcommerce.com/party-details 
![image](https://user-images.githubusercontent.com/57115316/90535564-a9bb4380-e140-11ea-93ba-05e6a7cb6291.png)

### Steps to reproduce behavior
Login to myHQ, set up a non consultant hosted party. Click the view host planner link. 

Again, should be brought here: 
 https://tastefully-simple-sandbox-2.mybigcommerce.com/host-planner

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-171](https://razoyo.atlassian.net/browse/TST-171)

**Comment by suehamre** [comment]
8-19 SH - Retested, and this is still going to the party details page instead of the host planner page. I tried previous party and new party, new party link: 
![image](https://user-images.githubusercontent.com/57115316/90652857-22cf9f00-e204-11ea-90d6-41733db2b847.png)

**Comment by TastefullySimple** [comment]
Ready for QA

**Comment by suehamre** [comment]
8-19 SH - Fixed
