### ISSUE TITLE
Cuztomize Webpage- Shop or Host with me introduction- not updating text - still shows default text 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#268]
### Expected behavior

Ability to customize the Shop or Host with me introduction. Maximum characters = 435

### Actual behavior

When I Customize my  Shop or Host with me details and save this information does not get updated on my webpage- 
You can see that I have updated to use the max amount of characters 435 and have 0 remaining. 

![image](https://user-images.githubusercontent.com/57115301/90532663-20eed880-e13d-11ea-90cc-d33a3b6e8ca9.png)

When I go to my website, the information I have typed does not appear it is still showing the default text, as if they entered nothing. 
![image](https://user-images.githubusercontent.com/57115301/90532548-00268300-e13d-11ea-89b6-fb2f5957c853.png)

### Steps to reproduce behavior
Using Consultant # 187769 Kylie Jo
Go to myHQ and click Market my business
Customize my website
click about me
Shop or Host with me
enter text in text box and click save to update the webpage

**Comment by suehamre** [comment]
8-19 SH  - Per slack conversation we are hiding this capability for now and adding to backlog for prioritization.
