### ISSUE TITLE
Customize my Webpage- View my website button from myHQ doesn't take me to Consultants webpage & URL is different 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#269]
### Expected behavior

When you click view my Website button from myHQ it should take you to see that consultants webpage 

### Actual behavior
After making edits to customize my webpage, I clicked on the view my website button and its not taking me directly to the consultants webpage. 
![image](https://user-images.githubusercontent.com/57115301/90537337-d53f2d80-e142-11ea-940c-ef96b0f37837.png)
![image](https://user-images.githubusercontent.com/57115301/90537355-da9c7800-e142-11ea-934f-4c8697f3d52f.png)

it takes me here... https://tastefully-simple-sandbox-2.mybigcommerce.com/
![image](https://user-images.githubusercontent.com/57115301/90537392-e4be7680-e142-11ea-9628-ab0851546e66.png)

but should take me here to the consultants web page
![image](https://user-images.githubusercontent.com/57115301/90537430-eee07500-e142-11ea-9e8e-a59a580dd6c2.png)

It shows that the WebURL is https://tastefully-simple-sandbox-2.mybigcommerce.com/web 
But in myHQ it shows my WebURL is   https://www.tastefullysimple.com/web/kjo
![image](https://user-images.githubusercontent.com/57115301/90539380-5bf50a00-e145-11ea-95a6-7ae1467d9e78.png)

### Steps to reproduce behavior
Using Consultant # 187769 Kylie Jo----- password is Beerbread1! 
Go to myHQ and click Market my business
Customize my website
click about me
Shop or Host with me
enter text in text box and click save to update the webpage

**Comment by TastefullySimple** [comment]
This is ready for testing.

**Comment by monicakarnes** [comment]
Fixed - Closing- thanks!
