### ISSUE TITLE
Customize my webpage- My Story section should not display if Consultant didn't enter their story 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#270]
### Expected behavior

If you do not enter any text below, the “my story” section will not display on your webpage.

Production example- ID- 182528 - no story entered - no my story displayed
![image](https://user-images.githubusercontent.com/57115301/90543113-ca889680-e14a-11ea-9aef-99582a3d3ab8.png)
![image](https://user-images.githubusercontent.com/57115301/90543133-d3796800-e14a-11ea-93a4-854496584063.png)

Production example - ID 43454- story entered - story displayed
![image](https://user-images.githubusercontent.com/57115301/90543311-1a675d80-e14b-11ea-8c45-4e90f5613f18.png)

### Actual behavior
No story entered in myhq
![image](https://user-images.githubusercontent.com/57115301/90543512-6d411500-e14b-11ea-9b77-55772594f887.png)

Kylie's webpage- still shows a my story section and shouldn't as no story was entered 
![image](https://user-images.githubusercontent.com/57115301/90543727-b98c5500-e14b-11ea-9ba4-8d67a74f51f5.png)

### Steps to reproduce behavior
Using Consultant # 187769 Kylie Jo----- password is Beerbread1!
Go to myHQ and click Market my business
Customize my website
click about me
My Story
do not enter a story
view webpage

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-172](https://razoyo.atlassian.net/browse/TST-172)

**Comment by jsmnglng-w** [comment]
Removed the title in story section if there are no story coming from the API in Shogun
![Screen Shot 2020-08-18 at 12 58 22 PM](https://user-images.githubusercontent.com/69249028/90549074-906fc280-e153-11ea-8c08-c96ebcf5912a.png)

**Comment by TastefullySimple** [comment]
This is QA ready

**Comment by monicakarnes** [comment]
fixed- closing- thanks
![image](https://user-images.githubusercontent.com/57115301/90694545-6646ff00-e23e-11ea-93f4-6c51071eeb4b.png)
