### ISSUE TITLE
Host Planner page does not display party details

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#272]
### Expected behavior
The host planner page should display the party details. 

### Actual behavior
The host planner page is not displaying the party details. 
![image](https://user-images.githubusercontent.com/57115316/90691683-5973dc80-e239-11ea-9efd-83d9c0c018ff.png)

### Steps to reproduce behavior
Clicked on the 'your hosts party planner website' link in myHQ 
User is brought to the host planner page as they should be, but the details are not displayed: 
Name, Date, Time Consultant, Total so far 
![image](https://user-images.githubusercontent.com/57115316/90691787-8de79880-e239-11ea-81f6-36687db91ebb.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-174](https://razoyo.atlassian.net/browse/TST-174)

**Comment by jsmnglng-w** [comment]
In Shogun, I found that the JS for the custom element (filename: Party Detail) associated with the Party Detail section of the Host Planner page is calling the `TSCookie` as a class and that class doesn't exist. Refactored it and now it's displaying the party details
![Screen Shot 2020-08-20 at 1 16 34 PM](https://user-images.githubusercontent.com/69249028/90809857-b928c100-e2e7-11ea-9bec-649dc1fa7d1e.png)

**Comment by suehamre** [comment]
@jsmnglng-w , I do see the details that you have posted above in my host planners, however we are still missing the Total (so far). As in your screenshot above it is displaying 0 and I have parties that have totals and they are not displayed. This total is in myHQ and listed as 'Current party total' and is Part 1 retail only. Does not include tax or shipping amounts. See example below: 
![image](https://user-images.githubusercontent.com/57115316/90816153-6ce27e80-e2f1-11ea-8ae9-606aabcff6a0.png)
![image](https://user-images.githubusercontent.com/57115316/90816202-7cfa5e00-e2f1-11ea-8922-9c0c9af43672.png)

**Comment by jsmnglng-w** [comment]
This looks like an API issue. I looked up the setting of the party cookies, and when I select a party, it's setting the fields correctly coming from the API. I also looked up the response coming from the API and the `Total` field is always `0` from the result
![Screen Shot 2020-08-20 at 3 57 44 PM](https://user-images.githubusercontent.com/69249028/90826276-c94c9a80-e2ff-11ea-97e9-843e43a66fb6.png)
![Screen Shot 2020-08-20 at 4 08 12 PM](https://user-images.githubusercontent.com/69249028/90826278-ca7dc780-e2ff-11ea-99e0-e5e9b6ba0667.png)

**Comment by wbyrnetx** [comment]
I'm thinking this should be assigned to TST

**Comment by jsmnglng-w** [comment]
Talked to @richierubin and we needed to hit another API call `/party/planner?pid=<partyId>` to get the party details data. Will add the API call in [TST-174](https://razoyo.atlassian.net/browse/TST-174)

**Comment by wbyrnetx** [comment]
This is ready for QA on Tech Sandbox
![Screen Shot 2020-08-31 at 12 53 21 PM](https://user-images.githubusercontent.com/4029452/91862493-05ef8e80-ec3c-11ea-92ed-1f322e89c156.png)

**Comment by suehamre** [comment]
9-1 I am seeing the totals now. :)
