### ISSUE TITLE
Header is displaying Tastefully Simple as my consultant and should not 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#290]
### Expected behavior
When shopping with Tastefully Simple the header should NOT display 'Tastefully Simple'. 

### Actual behavior
The header is displaying Tastefully Simple as my consultant and should not. 

### Steps to reproduce behavior

Searched for a consultant by zip code that returned no results. 
Selected to continue with TS 
Viewed header 
![image](https://user-images.githubusercontent.com/57115316/90897082-46245680-e38a-11ea-907c-25816970dfd8.png)

**Comment by wbyrnetx** [comment]
This should be fixed now and is ready for QA on tech sandbox.

**Comment by monicakarnes** [comment]
If you search within the header, search by zipcode 11111 receive the error of no match and Select to shop with TS the cart & header appears correctly. 
![image](https://user-images.githubusercontent.com/57115301/91065711-7112e280-e5f6-11ea-9b99-91e3d8ff20d7.png)
