### ISSUE TITLE
Two different consultants are being used in QA1 as the TS consultant

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#292]
### Expected behavior
When shopping with Tastefully Simple, the consultant ID used should be #160785. 

### Actual behavior
If shopping and not selecting a consultant, the order is being affiliated with CID#187682. 
If searching for a consultant and getting the no results found error message, then selecting the button to shop with Tastefully Simple, the order is affiliated with CID#160785.

### Steps to reproduce behavior
Started with clean cookies, added items to cart, never selected a consultant and placed an order. The order went under CID#187682. 
![image](https://user-images.githubusercontent.com/57115316/91099645-50b04b80-e629-11ea-900d-d69aa7234975.png)

Cleared cookies again. Clicked find a consultant and entered an invalid zip code, got the error message no results found. Clicked the button to continue with Tastefully Simple and the order was affiliated with CID#160785 as it should be. 
![image](https://user-images.githubusercontent.com/57115316/91099549-252d6100-e629-11ea-8a42-dd5b811be5f3.png)

Please update the first scenario to use CID#160785.

**Comment by wbyrnetx** [comment]
We've addressed this in the Shogun script (no PR needed). Ready for you guys to QA again.

**Comment by monicakarnes** [comment]
started with cleancookies, shopped added items to cart, checked out, looks like now it going to ID#  160785 as it should 
![image](https://user-images.githubusercontent.com/57115301/91483390-43839e80-e86d-11ea-8c5e-9d21d8a2704d.png)
closing
