### ISSUE TITLE
Confirmation page - tastefully simple logo needs to be clickable

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#295]
### Expected behavior
On the order confirmation page the tastefully simple logo should be clickable and bring user to the home page. 

### Actual behavior
When clicking on tastefully simple it does nothing and should bring user to the homepage. 
![image](https://user-images.githubusercontent.com/57115316/91217464-291abb00-e6dd-11ea-9e7d-cdfd3715f696.png)

### Steps to reproduce behavior

Place an order. 
When the order confirmation page appears click on tastefullysimple.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-184](https://razoyo.atlassian.net/browse/TST-184)

**Comment by monicakarnes** [comment]
this works, take me to the main page closing
