### ISSUE TITLE
JOIN- ERROR- please provide ID Can't get past login/sign up page 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#299]
Trying to go in to check on the bug 107-  but I can't get past this page, keep getting the ERROR to provide and ID 
![image](https://user-images.githubusercontent.com/57115301/91482592-e9cea480-e86b-11ea-8ea8-1ea6b50af78f.png)

**Comment by jsmnglng-w** [comment]
@monicakarnes This was because the BBOK product was disabled this morning --we were testing the issue when the product is still purchase-able even though it was disabled in BigCommerce. Try testing it again, it's now working for me.

**Comment by monicakarnes** [comment]
@jsmnglng-w  Thank you, yes its working now- closing this
