### ISSUE TITLE
JOIN- Select sponsor- Client has to click on Image to select Consultant as their sponsor

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#301]
### Expected behavior
Client should be able to click anywhere within the consultants information to select them 

![image](https://user-images.githubusercontent.com/57115301/91590461-142e6980-e921-11ea-8696-98920610b12a.png)

Note we did have as similar issue Bug #249  with the find consultant modal as well, which was fixed. 

### Actual behavior
 I have to actual click on the image for it to highlight as selected 

![image](https://user-images.githubusercontent.com/57115301/91590569-33c59200-e921-11ea-9977-e40fae7709b9.png)

### Steps to reproduce behavior

Go down join path, enter details to get to select sponsor
search for sponsor
click within the white box of the consultant details --- it should select it at this point--- 
then click on the image it will then select the consultant

**Comment by jsmnglng-w** [comment]
Reopened [TST-159](https://razoyo.atlassian.net/browse/TST-159)

**Comment by suehamre** [comment]
9-2 - Retested this yesterday and it passed. It was listed in slack as the old bug #249. :)
