### ISSUE TITLE
Find a consultant - User is able to continue without selecting the consultant after clicking refine your search

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#305]
### Expected behavior
If user does not click on the consultant to select it, they should receive this error: 
![image](https://user-images.githubusercontent.com/57115316/92159814-9e7c3f00-edf3-11ea-8fdc-5ca29a2bc90b.png)

### Actual behavior
User is able to continue without selecting the consultant after they have done the 'refine search'. See steps to dup below. 

### Steps to reproduce behavior

Click on find a consultant 
![image](https://user-images.githubusercontent.com/57115316/92159964-e00cea00-edf3-11ea-9968-7c2646371394.png)
 
Enter a consultant ID and click search 
 
![image](https://user-images.githubusercontent.com/57115316/92159983-e7cc8e80-edf3-11ea-81b1-99d06474fe24.png)

Click on the consultant to select it then click on refine your search 
![image](https://user-images.githubusercontent.com/57115316/92159993-ee5b0600-edf3-11ea-9345-5ffad5292c84.png)
 
Id is saved in the field – just click on search again 
![image](https://user-images.githubusercontent.com/57115316/92160024-fb77f500-edf3-11ea-912c-d053babd47b3.png)

 Now don’t select the consultant again, and click continue 
 
![image](https://user-images.githubusercontent.com/57115316/92160044-0599f380-edf4-11ea-8f82-d529b4da37cf.png)

User is able to continue, and header looks like this with no name 
![image](https://user-images.githubusercontent.com/57115316/92160059-0cc10180-edf4-11ea-992c-741c65e2e7bb.png)
 
User should get this error message: 
 
![image](https://user-images.githubusercontent.com/57115316/92160074-15b1d300-edf4-11ea-9908-aaca1a009561.png)

I was able to duplicate this on all three searches for Find a consultant.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-198](https://razoyo.atlassian.net/browse/TST-198)

**Comment by suehamre** [comment]
9-9 fixed
