### ISSUE TITLE
Find a party - User is able to continue without selecting party after clicking refine your search

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#309]
### Expected behavior
If user does not select a party the following error message is displayed: 
![image](https://user-images.githubusercontent.com/57115316/92503147-72cbd100-f1c6-11ea-85b4-eeddaf4a6992.png)

### Actual behavior
If user has chosen to refine their search, they are able to continue without selecting the party. 

### Steps to reproduce behavior
Search for a party 
![image](https://user-images.githubusercontent.com/57115316/92503228-91ca6300-f1c6-11ea-8476-01ba6ad04168.png)
Select a party on the search results, then click on refine your search
![image](https://user-images.githubusercontent.com/57115316/92503267-9d1d8e80-f1c6-11ea-96a5-4059b6778bdd.png)
Previous search criteria entered is saved, just click search again
![image](https://user-images.githubusercontent.com/57115316/92503296-ac044100-f1c6-11ea-9e94-4665b597c08e.png)
Do not select party and click continue 
![image](https://user-images.githubusercontent.com/57115316/92503324-b58da900-f1c6-11ea-9722-79692afbcd1c.png)
No error message is received, and user is brought to previous party searched for.
![image](https://user-images.githubusercontent.com/57115316/92503354-c0e0d480-f1c6-11ea-87f2-3af5d8ffc382.png)
If no party selected, they should receive this error: 
![image](https://user-images.githubusercontent.com/57115316/92503377-ca6a3c80-f1c6-11ea-932a-0efcfbaa93bb.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-199](https://razoyo.atlassian.net/browse/TST-199)

**Comment by suehamre** [comment]
9-9 Fixed
