### ISSUE TITLE
Social Sharing link does not affiliate the consultant

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#311]
Stone and I tried to do a test this morning with a social sharing link for facebook and the Consultant does not populate once on the Big C site. 

Here’s what we did: 

Stone created the link like he normally would in his admin account in Multibrain. I gave him the URL for the big C site in QA1  -  
https://tastefully-simple-sandbox-2.mybigcommerce.com/

He sent me this link to use 
https://tastefully-simple-sandbox-2.mybigcommerce.com/?SCID=999999030

Since this Cons ID in that link is for the sales test account, I just changed it to CID#0000028. 
https://tastefully-simple-sandbox-2.mybigcommerce.com/?SCID=0000028 

But it did not populate my consultant in the header: 

![image](https://user-images.githubusercontent.com/57115316/92653920-a84ee800-f2b4-11ea-9ace-5b3a977b13b9.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-204](https://razoyo.atlassian.net/browse/TST-204)

**Comment by suehamre** [comment]
9-11  - Using this link, my consultant was now affiliated and populated in the header. 
https://tastefully-simple-sandbox-2.mybigcommerce.com/?SCID=0000028
