### ISSUE TITLE
New consultant was not created in Prowess

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#315]
### Expected behavior
Completing the join process should create a new consultant in Prowess, TSN, myHQ. 

### Actual behavior
Completing the join process the new consultant was not created in Prowess, TSN or myHQ. 

### Steps to reproduce behavior
I completed the join process in Big C with the following information. 
Email  = shouldbefixed@mailinator.com 
eccsuserinfo table shows last signup page ID =20 
I also noticed that the item number is Null 
![image](https://user-images.githubusercontent.com/57115316/92934965-c4b26800-f40d-11ea-9369-a7784016d00f.png)
The item is still active in item maintenance 
![image](https://user-images.githubusercontent.com/57115316/92935027-d85dce80-f40d-11ea-8262-cd6d359123d3.png)
And in Big C 
![image](https://user-images.githubusercontent.com/57115316/92935072-e90e4480-f40d-11ea-8fc2-a86afe86da74.png)

Big C order: 
![image](https://user-images.githubusercontent.com/57115316/92935093-f297ac80-f40d-11ea-8f00-b47947d548f6.png)

**Comment by TastefullySimple** [comment]
Correct order download bug when creating a blank affiliate.

**Comment by suehamre** [comment]
9-17  Entered a new join using email address victorytoday@mailinator.com and the user info table still shows null for the item number: 
![image](https://user-images.githubusercontent.com/57115316/93535080-df07ac80-f90b-11ea-9c4e-074ab4bae695.png)
![image](https://user-images.githubusercontent.com/57115316/93535122-f21a7c80-f90b-11ea-80e5-f1090bf8e525.png)
New consultant agreement audit trail report has this error: 
![image](https://user-images.githubusercontent.com/57115316/93535175-0fe7e180-f90c-11ea-9852-15b6a437b902.png)

**Comment by TastefullySimple** [comment]
The item number field is null for all the records in prod. I'm not sure that is the root issue.

**Comment by TastefullySimple** [comment]
Current sticking point is a SSL error on an internal web service call.

**Comment by monicakarnes** [comment]
9.28.20 - attempted again :( 
getting the error again in Prowess 
![image](https://user-images.githubusercontent.com/57115301/94463798-22bbab00-0183-11eb-91f7-144a9a3256eb.png)
I see it TSN 
![image](https://user-images.githubusercontent.com/57115301/94463872-40891000-0183-11eb-9430-d7ebec6c55c1.png)
I can see it in the Table- - TSProfiles.dbo.Eccs.Userinfo at Status of 50 
![image](https://user-images.githubusercontent.com/57115301/94463935-526ab300-0183-11eb-95a5-c66f3fc154ff.png)
 I see in TSprofiles.dbo .Consultant - it shows contact entry status still shows in ICEAUDIT----- 
![image](https://user-images.githubusercontent.com/57115301/94463971-61e9fc00-0183-11eb-8597-cfd13e3b24a1.png)
and when I look there it shows the last update was at 10:30 and its not yet completed  
![image](https://user-images.githubusercontent.com/57115301/94464014-73cb9f00-0183-11eb-86d0-21d508b73020.png)

**Comment by TastefullySimple** [comment]
This was fixed
