### ISSUE TITLE
Host reward slider - update the word free to be all caps FREE

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#316]
### Expected behavior
Per the approved verbiage and user story the word 'free' should always be in all caps 'FREE' 

### Actual behavior
The word 'free' is not capitalized on any of the boxes: 
![image](https://user-images.githubusercontent.com/57115316/93091691-0dfbf500-f664-11ea-8de8-ca08b69334d0.png)

### Steps to reproduce behavior

Go to big C and click on host, scroll down and view the host slider

![image](https://user-images.githubusercontent.com/57115316/93091597-ef95f980-f663-11ea-846c-23cec463810a.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-208](https://razoyo.atlassian.net/browse/TST-208)

**Comment by staciejurczak** [comment]
This is complete on the marketing sandbox, and Jackie has sync'd to the tech sandbox so it's showing there now too:
https://tastefully-simple-sandbox-2.mybigcommerce.com/host
https://tastefully-simple-sandbox-1.mybigcommerce.com/host
https://tastefully-simple-sandbox-2.mybigcommerce.com/join-us
https://tastefully-simple-sandbox-1.mybigcommerce.com/join-us
2020-09-14--1600104400_1602x317_scrot.png 2020-09-14--1600104380_1514x331_scrot.png

**Comment by suehamre** [comment]
9-14 Fixed.
