### ISSUE TITLE
Hold: Join Release - Used an email address that is already associated to a consultant at checkout - order went under that cons

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#32]
### Expected behavior
Researching what this should be.

### Actual behavior
Denise and Sue both had this issue happen. They inadvertently used an email address at checkout (not on the personal information page) that is already associated to a consultant, therefore the order went under that cons vs the cons they chose to sign up under. Big C orders #504 & 503. TSN order #'s 26908519 & 26908517.

### Steps to reproduce behavior
Use an email address at checkout that is already associated to a consultant

**Comment by monicakarnes** [comment]
checked- done
