### ISSUE TITLE
Switching parties- Wrong consultant photo is displayed in the cart 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#322]
### Expected behavior
The consultant photo displayed in the cart should match the consultant selected in the header. 

### Actual behavior
After selecting a party, changing consultant, changing party the consultant's photo in the cart does not update. 

### Steps to reproduce behavior

Started with clean cookies – no cons and no party. Clicked find a party and searched by state MN  - no name. Selected Cathy Albers Party under Elaine Johnson and continue: 
![image](https://user-images.githubusercontent.com/57115316/93646976-f5c20800-f9cc-11ea-891e-4d5356440eb5.png)
![image](https://user-images.githubusercontent.com/57115316/93646992-fc507f80-f9cc-11ea-8e08-05a0a1869957.png)
Went to shop and added an item to my cart: 
![image](https://user-images.githubusercontent.com/57115316/93647013-083c4180-f9cd-11ea-814f-c965b3e84918.png)
I then went to edit in the header and changed the consultant to Betty Evans  - CID#28
The consultant in the header updated and the party was dropped as it should be: 
![image](https://user-images.githubusercontent.com/57115316/93647053-19854e00-f9cd-11ea-83d8-3a5d652e49ca.png)
Clicked on find a party and searched by state and no name and selected cloud day’s party under consultant Karen Moe 
![image](https://user-images.githubusercontent.com/57115316/93647072-2609a680-f9cd-11ea-8874-f306bba0ba8d.png)
I am brought here like I should be: 
![image](https://user-images.githubusercontent.com/57115316/93647089-33269580-f9cd-11ea-90b5-8f5c40c84382.png)
But then clicked to view my cart. The consultant and party updated but the consultant photo did not. The photo displayed is still Betty Evans photo not Karen Moe’s. 
![image](https://user-images.githubusercontent.com/57115316/93647109-40dc1b00-f9cd-11ea-9579-0f32a7cc6eed.png)
This is Karen Moe’s photo: 
![image](https://user-images.githubusercontent.com/57115316/93647132-4e91a080-f9cd-11ea-8437-f9fcba5a0c33.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-213](https://razoyo.atlassian.net/browse/TST-213)

**Comment by wbyrnetx** [comment]
Waiting for technical approach confirmation...

**Comment by TastefullySimple** [comment]
> Waiting for technical approach confirmation...

Party API calls have been updated to return a consultant image url.

**Comment by suehamre** [comment]
9-22 I have deleted cookies and retried this a few times. I am still getting the same results as above when following the same steps above. Betty's picture remains in the shopping cart and should be updated to Karen Moes.

**Comment by jsmnglng-w** [comment]
@suehamre I'm currently working on updating the code in the fronted so that the correct consultant image coming from the API will be displayed

**Comment by suehamre** [comment]
@jsmnglng-w , thank you! I retested because it was assigned back to me so I thought it was ready!

**Comment by suehamre** [comment]
9-23 Fixed.
