### ISSUE TITLE
Font in footer is different on consultant spotlight page

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#324]
### Expected behavior
Font in the footer should be the same on all pages. 

### Actual behavior
Consultant Spotlight page the font changes. 

### Steps to reproduce behavior
Go to homepage and view the footer and font: 
![image](https://user-images.githubusercontent.com/57115316/93921581-5788b780-fcd6-11ea-83c9-e2aa386a2073.png)

Click on 'Consultant spotlight' in the footer, then scroll down and view the footer and font again: 
![image](https://user-images.githubusercontent.com/57115316/93921643-725b2c00-fcd6-11ea-8c8d-bc061d28c840.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-216](https://razoyo.atlassian.net/browse/TST-216)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/94167812-8e83d800-fe52-11ea-86a6-0c1111c9e803.png)
 Fixed, now at 12pt font size

**Comment by staciejurczak** [comment]
@suehamre @mandi920  We have QAed this on our end. Please see results below. I will close the ticket on our end. 
-Camaryn

https://tastefully-simple-sandbox-2.mybigcommerce.com/consultant-spotlight

Consultant Spotlight footer:

![image](https://user-images.githubusercontent.com/65304780/94290348-ae350200-ff1f-11ea-81c7-c1f0968f5afa.png)

Other page’s footer:
![image](https://user-images.githubusercontent.com/65304780/94290326-a83f2100-ff1f-11ea-8a85-10c45cd070b3.png)

Marketing Sandbox: https://tastefully-simple-sandbox-1.mybigcommerce.com/consultant-spotlight

Consultant Spotlight footer:
![image](https://user-images.githubusercontent.com/65304780/94290294-9e1d2280-ff1f-11ea-9c58-07c9540b8015.png)

Other page’s footer:
![image](https://user-images.githubusercontent.com/65304780/94290270-952c5100-ff1f-11ea-99ea-d2aa5a08bfd3.png)
