### ISSUE TITLE
Join- Confetti shoots off to the left of the screen, instead of by the party horn 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#326]
Confetti should pop over the party horn on the Join Confirmation page. 

Confetti is shooting off over to the left corner of the screen 

Go down the join path, complete agreement, watch on confirmation page where the confetti opens 

![Join process - Confetti to theleft](https://user-images.githubusercontent.com/57115301/94209105-18529600-fe91-11ea-8896-a14b3606a7ed.gif)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-220](https://razoyo.atlassian.net/browse/TST-220)

**Comment by staciejurczak** [comment]
We have created a ticket for this issue and has assigned 2 story points.

**Comment by monicakarnes** [comment]
fixed- closing thanks
