### ISSUE TITLE
new account  - address record is created three times and myhQ contact blows up

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#328]
### Expected behavior
When creating an account on Big C, only one record should be created in TS Data tables. 

### Actual behavior
When creating an account from checkout area and placing an order, three records are created for the address. 
email address = createbeforepay@mailinator.com

![image](https://user-images.githubusercontent.com/57115316/94313473-696f9200-ff44-11ea-9be1-f131e210e959.png)

### Steps to reproduce behavior
Went to big c and selected a consultant, CID#28, then added items to my cart and went to checkout. 
Step 1 of checkout user is required to enter an email address and checkout as guest or can click 'Sign in now' 
![image](https://user-images.githubusercontent.com/57115316/94313706-d4b96400-ff44-11ea-8a96-b5712874f595.png)
If they click sign in now, they then have the option to create an account, I clicked this and created my account: 
![image](https://user-images.githubusercontent.com/57115316/94314097-7c369680-ff45-11ea-9ee2-f7a5f9c81d41.png)
I then navigated back to the checkout and placed the order. 
The new account is created in TSProfiles.dbo.userobject. 
![image](https://user-images.githubusercontent.com/57115316/94315022-55795f80-ff47-11ea-809b-639ca1f35b8f.png)

in dbo.address  - three records were created. I would expect only one to be created, correct? 
![image](https://user-images.githubusercontent.com/57115316/94315093-75a91e80-ff47-11ea-93ed-319d064b7e67.png)

Email address  = createbeforepay@mailinator.com  Big C ID#5354

inmyHQ address book when I try to view this contact I get an error: 
![image](https://user-images.githubusercontent.com/57115316/94315214-b4d76f80-ff47-11ea-85c4-cffdc0f40e49.png)

![image](https://user-images.githubusercontent.com/57115316/94315231-bef96e00-ff47-11ea-9976-15ee404d0ba4.png)

**THIS IS A DIFFERENT EXAMPLE THAT I DID EARLIER TODAY BELOW:**  
On this example, I checked out with the order and then on the confirmation page created my account. 
![image](https://user-images.githubusercontent.com/57115316/94315642-86a65f80-ff48-11ea-9345-43dc7b6a982a.png)

on this one there is only two records in dbo.address 
![image](https://user-images.githubusercontent.com/57115316/94315722-b48ba400-ff48-11ea-98e5-6082976d2cc2.png)

but in myHQ address book, CID #28 it displays 3 times: 
![image](https://user-images.githubusercontent.com/57115316/94315789-d71dbd00-ff48-11ea-8359-bf8f3f9a131c.png)

**Comment by TastefullySimple** [comment]
We believe this is a database integration issue.

**Comment by mandi920** [comment]
@suehamre is this fixed?

**Comment by sevincent** [comment]
Corrected contact address logic in orders.uspU_BatchDetailStatusByOrderNumber so it would handle null business names and find the existing address. Added logic to bcom.uspI_BigCommerceOrderLine to only create one address record for a user that functions as both billing and shipping.
