### ISSUE TITLE
New Client account - mobile phone number is not saved to database 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#331]
### Expected behavior
Mobile phone should be saved to TSProfiles.contact.phone. 

### Actual behavior
Created a new account and added a primary phone number and a mobile phone number. Only the primary is saved to the contact.phone database. 

### Steps to reproduce behavior
Create new account in Big C and add a primary phone number and a mobile phone number. 
Email address = primaryandmobile@mailinator.com 
Contact XID = 9542886
Big C customer XID  = 611
![image](https://user-images.githubusercontent.com/57115316/94482695-50165200-019f-11eb-9a57-b608dfac898b.png)

**Comment by TastefullySimple** [comment]
@richierubin is this ready for QA?

**Comment by richierubin** [comment]
I thought this was fixed, but let me look in the morning and I'll reassign as needed.

**Comment by monicakarnes** [comment]
This is now saving- closing bug 

EmailAddress = 'Testphonemobilesave@mailinator.com'
ContactXID = '9542942'
![image](https://user-images.githubusercontent.com/57115301/96047742-2f0a5e00-0e3b-11eb-88dd-f5526a561dd2.png)
![image](https://user-images.githubusercontent.com/57115301/96047856-57925800-0e3b-11eb-8d82-64b630bea3af.png)
