### ISSUE TITLE
Shopping Cart - Shipping Section - Drop down boxes are too short -Cutting off the bottom of the text

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#333]
### Expected behavior
I would expect to be able to see the whole word of the country and the state

### Actual behavior
The bottom part of the word is cut off.

### Steps to reproduce behavior
Add an item to your cart and go to the cart. Once on the cart click the Add Info link in the Shipping section. 
![image](https://user-images.githubusercontent.com/57953952/94595036-e013d480-024f-11eb-835f-279a8ee1817a.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-222](https://razoyo.atlassian.net/browse/TST-222)

**Comment by wbyrnetx** [comment]
Just checking up on this one. Can we close this issue out?

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/95351890-48ce0300-0887-11eb-8fe1-8c8badef67ac.png)
 yes, fixed - closing
