### ISSUE TITLE
TSO Account - Address Tab - Add an address with an apostrophe in the name

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#334]
### Expected behavior
I would expect the apostrophe to display correctly.

### Actual behavior
The apostrophe shows #039;s instead of '.

### Steps to reproduce behavior
This one is broke in Tech and Business boxes..  When you are logged into the clients TSO account and you are under the Address tab and you add an address and include apostrophe in the name... my example was I entered in Mari's House as my 1st and last name and when I saved it and went to look at it it used #039;s instead of ' in the name text.
![image](https://user-images.githubusercontent.com/57953952/94595236-2cf7ab00-0250-11eb-88f5-687015292299.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-223](https://razoyo.atlassian.net/browse/TST-223)

**Comment by wbyrnetx** [comment]
Can we close this out now?

We see it's working on the live site.
![Screen Shot 2020-10-06 at 11 49 25 AM](https://user-images.githubusercontent.com/4029452/95373239-5775e380-08a2-11eb-88a4-e04e46a60089.png)

**Comment by mandi920** [comment]
@monicakarnes can this be closed?

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/95467569-3a452180-0943-11eb-8627-5423adc045a5.png)
