### ISSUE TITLE
Consultant ID going to the home page for some

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#336]
### Expected behavior
When I type in the consultants webpage address I would expect it to bring me to their webpage.

### Actual behavior
When I type in the consultants webpage address it takes me to the home page.

### Steps to reproduce behavior

Per Monica: I attempted this today- Consultant ID 166521 and when I clicked the link, looks like its gonna go to sandbox1 as it should... 

here is what I see  https://tastefully-simple-sandbox-1.mybigcommerce.com/web/gbrooks
![image](https://user-images.githubusercontent.com/57953952/94731007-b9c26780-0329-11eb-8250-0887de047c9d.png)
 it takes me to the main page - 
![image](https://user-images.githubusercontent.com/57953952/94731058-cba40a80-0329-11eb-9c50-d65f78486d2d.png)
 I attempted to just type in  the link  https://tastefully-simple-sandbox-1.mybigcommerce.com/web/gbrooks  and when I do that, it takes me to the same page. 

If I try to find my consultant through the modal, then click on to select it, once selected click on the name in the Header Garth Brooks , it takes me to his webpage, but you can see the link in the URL is different - its listed as https://tastefully-simple-sandbox-1.mybigcommerce.com/web 
 
below is his webpage I see  then 
![image](https://user-images.githubusercontent.com/57953952/94731121-de1e4400-0329-11eb-8c4f-a5a21b93604d.png)

Appears to work properly for khuntley and #28.

**Comment by jsmnglng-w** [comment]
This looks like an API issue. I tried fetching https://qa1-tsapi.tastefullysimple.com/sb/web/gbrooks and https://qa1-tsapi.tastefullysimple.com/sb/web/khuntley, and for `gbrooks`, I'm getting a `null` value. But for `khuntley`, I'm getting the correct data
![Screen Shot 2020-09-30 at 3 13 43 PM](https://user-images.githubusercontent.com/69249028/94735094-cc3f9f80-032f-11eb-94be-40ad2d1b6a4f.png)

**Comment by TastefullySimple** [comment]
@suehamre @monicakarnes  does gbrooks has TS connected.
I get no results back.
https://stage-tsapi.tastefullysimple.com/sb/web/gbrooks

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/94744716-111f0280-033f-11eb-90a3-7482632ce24a.png)

**Comment by monicakarnes** [comment]
Fixed- Closing- Thanks!
