### ISSUE TITLE
[STAGE] Party code - first digit is being removed

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#337]
### Expected behavior
When I enter the link for a party I would expect to be brought to the details of that party.

### Actual behavior
When I enter the link for an open party the first digit is being removed causing a very old closed party to appear.

### Steps to reproduce behavior
I entered this link below, which is for the party listed above under CID#28,  and was brought to a completely different party, which is very old and closed. 

https://tastefully-simple-sandbox-1.mybigcommerce.com/p/3664828
![image](https://user-images.githubusercontent.com/57953952/94734452-e036d180-032e-11eb-92de-5a525e9768ac.png)

The Consultant this is under is CID#959 - Heidi Lawson. The party is Melissa Gibson, as you can see below the party id number matches the last six digits of the one I searched for.
![image](https://user-images.githubusercontent.com/57953952/94734502-f349a180-032e-11eb-85fb-1812c6d6089a.png)
Per Jared: 
This need to be logged to razoyo. The party is parsing code is removing the first digit
![image](https://user-images.githubusercontent.com/57953952/94734263-96e68200-032e-11eb-8902-f934811b03d3.png)
https://tastefully-simple-sandbox-1.mybigcommerce.com/p/3664536

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-225](https://razoyo.atlassian.net/browse/TST-225)

**Comment by monicakarnes** [comment]
Fixed closing- thanks
