### ISSUE TITLE
#4 - Join Release - Order number is missing from the congratulations page

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#34]
### Expected behavior
Order number should display per the mock up:
![image](https://user-images.githubusercontent.com/57953952/73957316-ccd08500-48cb-11ea-851f-a7f5eb88f023.png)

### Actual behavior
Order number does not display.

### Steps to reproduce behavior
Sign up as a consultant - go through checkout then the congratulations page will appear.

**Comment by monicakarnes** [comment]
4/10- I am still not seeing this listed on the Confirmation page. 

![image](https://user-images.githubusercontent.com/57115301/79002533-4b3ce380-7b16-11ea-9bf9-ed32ecc1f519.png)

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-195

**Comment by wbyrnetx** [comment]
Currently getting this 500 error and not able to continue on this.
![Screen Shot 2020-08-28 at 1 03 23 PM](https://user-images.githubusercontent.com/4029452/91732040-ac249100-eb75-11ea-8b02-44ad353ae397.png)

**Comment by wbyrnetx** [comment]
We fixed this and it's ready for QA.

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/94208712-1cca7f00-fe90-11ea-97e9-d6749dd5b260.png)

yeah, its there - fixed closing
