### ISSUE TITLE
Issue maintaining party association into the cart on mobile

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#341]
### Expected behavior
The party should still show once you go to the cart.

### Actual behavior
No party appears when you go to the cart just the consultant

### Steps to reproduce behavior
Device: iOS (likely all mobile devices)
Browser: Chrome

Open Mobile Menu, choose Find Party (or Switch Party)
Select a State, then select a party 
Shop for an item and add to Cart.
Go to cart, no party appears on cart just the consultant.

https://tastefullysimple.sharepoint.com/sites/Phase1Relaunch/Shared%20Documents/PSST/video-20201003-143200-fac2c83a.mp4

repeating same sequence on desktop, chrome, gets appropriate result -- showing both party and consultant.

Consultants reporting:
 
jacki Pitkow
Brook Myers

Teams Notes:
[11:13 AM] wbyrne (Guest)
    Looking into this one. Have you guys tried this with other mobile devices & mobile browsers? I don't think this is specific to iOS & Chrome, I'm also seeing it on iOS Safari and Desktop chrome (with mobile emulator enabled).
​[11:14 AM] wbyrne (Guest)
    My question would be... do we have ANY mobile device showing the selected party on the cart?
​[11:15 AM] Julie Cabinaw
    Not so far wbyrne (Guest)  Is it actually persisting in the data, but the UI isn't reflecting it?
​[11:16 AM] wbyrne (Guest)
    That's what it seems. Here's a screenshot from desktop chrome in mobile mode. I don't know if it was ever even implemented to show the party on the cart.
![image](https://user-images.githubusercontent.com/57953952/94996977-a1428f00-056d-11eb-899c-d10ad3061f56.png)
[11:17 AM] wbyrne (Guest)
    If I had any screenshot or example of this working properly in the past (even on tech sandbox) that would be helpful
​[11:17 AM] wbyrne (Guest)
    I'm trying to determine if this is something that was implemented and is not working properly... or if it was never implemented.
​[11:24 AM] Sue Hamre
    wbyrne (Guest), I just checked in the tech sandbox and I am only seeing the party bar/affiliation if I am within the menu and not within the cart. 
​[11:26 AM] wbyrne (Guest)
    Ya, so it sounds like this isn't something that's broken, it's something that wasn't implemented.
​[11:26 AM] jwise (Guest)
    Sue Hamre correct it's in the menu on every page along with the consultant bar
​[11:29 AM] wbyrne (Guest)
    Seems like this is related:
https://github.com/tastefully-simple/cornerstone/issues/223
​[11:30 AM] wbyrne (Guest)
    But ya... I'm not seeing anything about mobile cart page party bar
​[11:30 AM] wbyrne (Guest)
    Just having it in the mobile menu

**Comment by jsmnglng-w** [comment]
@mandi920 to implement this, can we get a mockup for how it will look like?

**Comment by mandi920** [comment]
@jsmnglng-w Here is a link to the mock-up. The one thing that hs changed since that mock is that the party area should be green, not tan, as it shows in comp.  https://tastefullysimple.sharepoint.com/sites/Phase1Relaunch/Shared%20Documents/Cart/Comps/TSOP1_ConsultantAffiliation_061820_Final/comps/M%20in%20party%20with%20consultant.png

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-231](https://razoyo.atlassian.net/browse/TST-231)

**Comment by jsmnglng-w** [comment]
@mandi920 I finished implementing the party bar in the cart page in mobile, but how do we want it to look like when there is no party selected yet? Currently, I just made it the same as the consultant:
![Screen Shot 2020-10-05 at 9 31 16 PM](https://user-images.githubusercontent.com/69249028/95205283-c8d26b00-07aa-11eb-927d-6e3afcead7ca.png)

**Comment by mandi920** [comment]
​[10:22 AM] Julie Cabinaw
    
my recommendation as a first step: Change color of party bar to soft red (style guide error state color of #FFDDDD) if no party selected and message should read : 

You have not selected a party (Find a Party)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/95590696-fb2ed300-0a0b-11eb-8709-ad683084512c.png)
![image](https://user-images.githubusercontent.com/57115301/95590908-447f2280-0a0c-11eb-8b85-01fc28b41ce6.png)
fixed, closing
