### ISSUE TITLE
Consultant Page does not display unique URL in browser address bar

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#342]
### Expected behavior
The full URL will be in the address bar

### Actual behavior

Consultants   use their consultant info page as their unique URL to share with   others.  They used to be able to copy the URL from the web browser to   share.  Now the URL is generic

### Steps to reproduce behavior
Paste www.tastefullysimple.com/web/bevans into the browser

![image](https://user-images.githubusercontent.com/57953952/94997066-3b0a3c00-056e-11eb-84b4-551bf9726557.png)

Situation: Consultants use their consultant info page as their unique URL to share with others.  They used to be able to copy the URL from the web browser to share.  Now the URL is generic.
 
There is a workaround -- consultatns can go to myHQ>Market My Business>Customize my Website and copy their link. Including the steps to login to the site, that is 4 clicks. Inconvenient but there is a workaround.  They can also memorize it or save it elsewhere.

**Comment by jsmnglng-w** [comment]
@mandi920 this was already implemented in Shogun, and ready for testing.

**Comment by mandi920** [comment]
Fixed
