### ISSUE TITLE
Party links not appearing in myHQ>Parties: Put TinyURL back out there

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#343]
### Expected behavior
Party   page tiny url needs to be available

### Actual behavior
The party link to my catalog show is not displaying in MYHQ.   When I go to my hosts party, it's gone.

### Steps to reproduce behavior

![image](https://user-images.githubusercontent.com/57953952/94997097-87557c00-056e-11eb-8998-58dbc843ef0e.png)

[9:54 AM] Sue Hamre
Julie Cabinaw & Stephanie Heseltine, this is the party page Tiny URL that they are referring to that was removed along with the evites.
![image](https://user-images.githubusercontent.com/57953952/94997859-8b37cd00-0573-11eb-9f90-d38191215d47.png)
Julie this is where we talked about they were going to have to go to the client party details page in TSO and copy the URL from the address bar to share.

[9:55 AM] Julie Cabinaw
    Yes, but the URL does not show in the address bar, so they cannot do that.  (Logging that next (smile) (smile))
​[10:08 AM] Stephanie Heseltine
    Correct the URL on the new website doesn't show any specific details to get them to that party. 
​[10:19 AM] Sue Hamre
    It doesn't show the details in the URL however, it does bring you to the correct party details page if you copy and paste it. This is similiar to the consultant webpage URL now how it doesn't have the consultant's /bevans (name) at the end it's only /web but it still brings them to the page. That being said, how I validated this morning was with a party page tiny URL and that did work so we will add this as a hot issue to get this added back to myHQ. 
​[10:31 AM] Julie Cabinaw
    Sue, can you describe that? You're saying, if you copy the url that looks generic, it will still copy the right thing? If I try to do that it just redirects to home page.
Edited​[10:41 AM] Sue Hamre
    Julie, yes that is what I was saying it was working for me. 
​[10:42 AM] Julie Cabinaw
    INteresting, doesn't work for me.  
​[10:42 AM] Sue Hamre
    and it worked for Charlotte
​[10:44 AM] Julie Cabinaw
SO you are on the party details page.  You go the browser, copy the generic looking link and paste it, and it takes you there? Can you try copying that and putting it incognito or clearing your cache? or pasting it into an email?  Below for example, is me copying it from a party details page:   https://www.tastefullysimple.com/party-details  If you assume the typical case is a consultant copying this and sending it a host or guest, the guest or host will not have the saved cookies from that party and the link won't resolve, correct?

[10:47 AM] Sue Hamre
    ugh, yes.. that is what I was doing but now as incognito it doesn't work so it probably was a cookies thing, dang. (sad) 

Refererence Consultant: Chris M Toenjes, Jacki Pitkow, Jenny Westerman, Alicia Thorp, Linda Scollon, REnee Akers Muprhy, David Holden Rice, Frank Joey, Holly Stankowski,

**Comment by suehamre** [comment]
10-3 Fixed :)
