### ISSUE TITLE
Correct Consultant Level not appearing on the Consultant Page

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#347]
### Expected behavior
The correct consultant level should be displayed.

### Actual behavior
Some consultants pages are not showing their correct level - This is not true for all consultants;

### Steps to reproduce behavior
1. Go to www.tastefullysimple.com/web/koneill3
2. Her level should show cobber but instead shows Consultant

Teams Notes:
[10:41 AM] Julie Cabinaw
Katie says she  is Copper but showing as Consultant
![image](https://user-images.githubusercontent.com/57953952/94998027-ae16b100-0574-11eb-9d95-30fe2e89f347.png)
Katie says she  is Copper but showing as Consultant
[10:44 AM] Sue Hamre
    Kara Carpenter - Would you mind taking a look at this issue please? 
​[10:45 AM] Kara Carpenter
    Logging on now
​[10:54 AM] Kara Carpenter
    Julie Cabinaw Sue Hamre I think this needs to be logged as a bug. Both Prowess and the initial Consultant search on TSO show her as copper. It is only when you click the link to go to her TS Page does it show consultant. Same with Kerry. I’m not sure where TS.com is pulling consultant from
​[10:55 AM] Sue Hamre
    Thanks for checking Kara!
(1 liked)​[11:03 AM] Charlotte Zumhofe
    Thanks for checking, Kara.  wbyrne (Guest) we're thinking this may have something to do with how the data is coming over from the consultants webpage on myHQ.  Can you take a peek?  
​[11:09 AM] wbyrne (Guest)
    Here's what we get from TSAPI on the consultant detail page for Katie
![image](https://user-images.githubusercontent.com/57953952/94998047-d6061480-0574-11eb-84bc-2e128b3a2abf.png)
[11:09 AM] wbyrne (Guest)
    I'm assuming that Title field is what populates there (I cannot verify because we do not have access to Shogun).
​[11:10 AM] wbyrne (Guest)
    But it seems right to me, because we default to it saying "Consultant" there
​[11:11 AM] wbyrne (Guest)
    So if it needs to say "Copper" there, then I think TSAPI needs to be returning "Copper" Title instead of blank ""
​[11:27 AM] Charlotte Zumhofe
    wbyrne (Guest) I would agree.  Kara Carpenter does this make sense to you as well?
​[11:29 AM] wbyrne (Guest)
    If you pull this consultant up in myHQ do you see Copper?
​[11:31 AM] Charlotte Zumhofe
    Yes.  They show as Copper Leader
​[11:31 AM] wbyrne (Guest)
    Weird... no clue why the API isn't reflecting that then
​[11:32 AM] wbyrne (Guest)
    Let me see if I can find a consultant that IS showing copper on the consultant detail page. Then we can compare API responses
​[11:34 AM] Charlotte Zumhofe
    Sue's getting you one.  (smile)

​[11:34 AM] wbyrne (Guest)
    Found one

![image](https://user-images.githubusercontent.com/57953952/94998060-eb7b3e80-0574-11eb-9153-4d4faa3a577e.png)
Well.. I found another one that SHOULD be Copper
![image](https://user-images.githubusercontent.com/57953952/94998079-fd5ce180-0574-11eb-8828-e3d227df5f9b.png)
The API is not consistent. The API call we make to get the list of consultants returns the right Title field.
![image](https://user-images.githubusercontent.com/57953952/94998094-0a79d080-0575-11eb-94d9-4864b7852f7f.png)
[11:37 AM] Kara Carpenter
    
wbyrne (Guest) it isn't only affecting Copper though.  Another example is CID 52580 She is a leader showing as Consultant

Edited​[11:37 AM] wbyrne (Guest)
    Right
​[11:38 AM] wbyrne (Guest)
    The API we use on the consultant detail page is not returning the right Title. Ever.
​[11:38 AM] wbyrne (Guest)
    Whereas for the exact same consultants... in the API response we get for Find a Consultant... we are getting the correct title.
​[11:39 AM] Kara Carpenter
    One example of a Cons who is showing the correct title is 112.  She's showing as Diamond Leader everywhere
​[11:39 AM] wbyrne (Guest)
    Interesting. Either way... the fix needs to happen on the API side for this call:

https://tsapi.tastefullysimple.com/consultant/info?cid=0174250
​[11:41 AM] wbyrne (Guest)
    It works for Sheri for whatever reason. But not for most other consultants.
![image](https://user-images.githubusercontent.com/57953952/94998108-1b2a4680-0575-11eb-8e50-8f85bb1562b3.png)
[11:41 AM] Charlotte Zumhofe
    Works for cons ID 1975
​[11:42 AM] Charlotte Zumhofe
    So, do we need to get Jared to fix it?
​[11:42 AM] wbyrne (Guest)
    Ya
​[11:42 AM] Kara Carpenter
    Charlotte Zumhofe yup
​[11:42 AM] Charlotte Zumhofe
    Ok.  Thank you for checking it out!!!  Appreciate you!
​[11:42 AM] wbyrne (Guest)
Find a consultant API ... always return the right Title
Consultant info API... returns the right Title for some and blank for the rest
​[11:42 AM] wbyrne (Guest)
    No problem!
​[11:43 AM] Charlotte Zumhofe
    Jared Sanow can you take a peek at this one?

**Comment by monicakarnes** [comment]
This is still not fixed in QA1- my examples - Consultant ID # 2051 and Consultant ID # 112
![image](https://user-images.githubusercontent.com/57115301/95789054-698cc300-0ca2-11eb-8b50-d4ef12e8177d.png)
![image](https://user-images.githubusercontent.com/57115301/95789124-8fb26300-0ca2-11eb-875a-c99b194c77bd.png)

![image](https://user-images.githubusercontent.com/57115301/95789165-a0fb6f80-0ca2-11eb-94f4-bd615171b6b5.png)
![image](https://user-images.githubusercontent.com/57115301/95789186-abb60480-0ca2-11eb-95ed-a736203798b3.png)

**Comment by monicakarnes** [comment]
This is fixed Checked Mobile and desktop - closing bug

![image](https://user-images.githubusercontent.com/57115301/97047209-3833b300-153e-11eb-8d61-79525c410645.png)


![image](https://user-images.githubusercontent.com/57115301/97047139-1c301180-153e-11eb-9632-25e823123605.png)
