### ISSUE TITLE
DevExpress Issue

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#348]
### Steps to reproduce behavior

![image](https://user-images.githubusercontent.com/57953952/94998343-de5f4f00-0576-11eb-8aaf-6f34acb32947.png)
[10:31 AM] Ezra Eash
    Sue Hamre -Catching up on the chain; I am familiar with the devexpress issue.  There is a devexpress install the needs to be performed on the web server; we only encounter this in non-prod envs after we upgrade a web server or build it new.  Let me look into it
​[10:38 AM] Sue Hamre
    Thanks Ezra Eash! I was surprised to see it made it to production as well because I also have only ever seen it in the test environments. 
(1 liked)​[10:51 AM] Carolyn Schmidt
    Ezra Eash - can we assume you are addressing this issue, and if so, what's your best guess on an ETA? 
​[10:53 AM] Ezra Eash
    Carolyn Schmidt -working on the shoptastefullysimple.com domain not redirecting correctly; is the dev express issue hotter?  I am guessing the dev express could take 1-2 hours.  shoptastefullysimple.com re-direct issue could take 1 hour.  Let me know which is higher priority.  Also may need Will for the shoptastefullysimple.com re-direct issue
​[10:54 AM] Ezra Eash
    Will had me change the name servers for shoptastefullysimple.com last night and added a redirect in godaddy but sounds like that didn't work for us.  We had to make the change in order to be able to get the big commerce ssl cert to work . . . 
(1 liked)​[10:54 AM] Carolyn Schmidt
    I believe the devexpress issues is hotter, I would suggest you redirect, unless you hear otherwise from Julie Cabinaw or Charlotte Zumhofe
(2 liked)​[10:56 AM] Carolyn Schmidt
    Related to the dev express issue, are there other web servers that already have dev express installed that can be left in and the ones without taken out, so we can eliminate the impact to consultants right now? 
Edited​[10:58 AM] Charlotte Zumhofe
    Carolyn Schmidt and Ezra Eash the devexpress issue doesn't impact any of the consultants capabilities on myHQ.  It's an annoyance versus an issue.  CS may get questions because they don't know what it means, but the consultants have full capabilities.

**Comment by TastefullySimple** [comment]
This is ready for QA in prod.
