### ISSUE TITLE
Join Release - Please add formatting for the phone numbers and social security numbers

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#35]
### Expected behavior
Automatically add the dashes and only allow them to add the correct amount of digits

### Actual behavior
When the user does not add the dashes they cannot proceed and the error message tells them to Please enter a valid phone number & Please enter your social security number

### Steps to reproduce behavior
Enter your social security number and phone number on the tell us about yourself page

**Comment by TastefullySimple** [comment]
Phone numbers and SSN should format as you type.

**Comment by monicakarnes** [comment]
Checked- done- formatting is there for both
