### ISSUE TITLE
Sticky Header is too tall

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#350]
### Steps to reproduce behavior

![image](https://user-images.githubusercontent.com/57953952/94997328-fd0e1780-056f-11eb-96fd-3f89d3e2c754.png)

[10:43 AM] jwise (Guest)
    Hey all! Noticing a small design issue on my laptop (small screen). the sticky header is quite tall, it would be an easy fix for me to take care of 
[11:07 AM] Julie Cabinaw
    Yes, please and thank you!!
​[11:08 AM] jwise (Guest)
    Julie Cabinaw Carolyn Schmidt is this something you'd like me to fix today at 911 rates or Monday at normal rates? It should take less than hour, but depends on if there are responsiveness issues.
​[11:09 AM] Julie Cabinaw
    it looks ok on mobile, I would say it can wait until monday rates (smile)
(2 liked)​[11:09 AM] Julie Cabinaw
    Its cosmetic.
​[11:09 AM] jwise (Guest)
    Sounds good, I agree it's a fairly small cosmetic issue (smile)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-228](https://razoyo.atlassian.net/browse/TST-228)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/95387374-3d460080-08b6-11eb-88c3-81d6ebb1babf.png)
here is what i see

**Comment by mandi920** [comment]
@monicakarnes can this be closed?
