### ISSUE TITLE
Choose your party button slightly cut off

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#351]
### Steps to reproduce behavior

![image](https://user-images.githubusercontent.com/57953952/94997366-347cc400-0570-11eb-80ae-13edf37ebb00.png)

[11:23 AM] jwise (Guest)
    Julie Cabinaw also found this that I can add to that ticket for Monday. Functionality works, button is just slightly cut off. This one may be a bit trickier.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-229](https://razoyo.atlassian.net/browse/TST-229)

**Comment by mandi920** [comment]
Fixed
