### ISSUE TITLE
Party Detail page does not display unique URL in browser address bar

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#353]
### Expected behavior
Full URL would be displayed in the address bar.

### Actual behavior
Situation:  Party LInks are no longer available to consultants in myHQ, so workaround was to be that consultants or hosts could grab the URL from the web browser from the party details page.

The URL for a party details page does not contain the party ID, however, so the consultant cannot copy the link from the web  browser either.

### Steps to reproduce behavior
1. Click Find a party
2. Enter a state and click search
3. Click on one of the parties and click continue

![image](https://user-images.githubusercontent.com/57953952/94997644-2def4c00-0572-11eb-9528-1f297b58ccf9.png)

[10:36 AM] Charlotte Zumhofe
    Julie Cabinaw this is the same issues as the consultant webpages.  If the client copies the url, it actually still maintains the party affiliation through the cookie.  We can also address this by adding the tiny url back to myHQ.

**Comment by jsmnglng-w** [comment]
@mandi920 This was already implemented with this Pull Request: https://github.com/tastefully-simple/cornerstone/pull/340, and is ready for testing
