### ISSUE TITLE
When clicking on shop on an Ipad it does not open megamenu

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#354]
### Expected behavior
I would expect the megamenu to open when I click on the shop button in the megamenu.

### Actual behavior
The shop button changes color so you know it has been clicked on but nothing happens.

### Steps to reproduce behavior
Go to www.tastefullysimple.com on an ipad and try to click shop on the menu at the top.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-232](https://razoyo.atlassian.net/browse/TST-232)

**Comment by monicakarnes** [comment]
Wasn't sure what Ipad so I checked a couple of them - Fixed Closing 

Checked- Ipad 7th in Safari
![image](https://user-images.githubusercontent.com/57115301/95353809-52f10100-0889-11eb-8ebe-70fcf58b960b.png)

Checked iPad Pro 12.9 2018 in Safari
![image](https://user-images.githubusercontent.com/57115301/95354058-9ba8ba00-0889-11eb-8666-fddf54afdcf0.png)

Checked iPad Air 2019 in Safari 
![image](https://user-images.githubusercontent.com/57115301/95354216-c561e100-0889-11eb-9831-5ebfaf48d68a.png)

Checked iPad Mini 2019 in Safari 
![image](https://user-images.githubusercontent.com/57115301/95354399-fd692400-0889-11eb-9815-abb152c31b06.png)
