### ISSUE TITLE
No scroll bar when viewing Find a consultant results - mobile multiple browsers - desktop safari

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#355]
### Expected behavior
I would expect to see a scroll bar when there are multiple consultants otherwise I would think I have to choose the top one that is displayed.

### Actual behavior
No scroll bars appear until I start to scroll

### Steps to reproduce behavior
Click on find a consultant - use zip code 85338 and click search

![image](https://user-images.githubusercontent.com/57953952/95111929-d71a7b80-0705-11eb-910e-702c1af6c107.png)
![image](https://user-images.githubusercontent.com/57953952/95111949-e13c7a00-0705-11eb-8beb-e48028bc7b37.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-234](https://razoyo.atlassian.net/browse/TST-234)

**Comment by mandi920** [comment]
Let me know if this link doesn't work for you.
https://tastefullysimple.sharepoint.com/sites/Phase1Relaunch/Shared%20Documents/PSST/video-20201004-213518-7c580f79.mp4

**Comment by monicakarnes** [comment]
Looks like you can see now that there is more than one...  I don't see the scroll bar, unless you hover and try to scroll. 
![image](https://user-images.githubusercontent.com/57115301/95384077-b727bb00-08b1-11eb-882a-fb1454d100dc.png)

Here you can see the scroll bar but its very light... not sure if you can darken that up?
![image](https://user-images.githubusercontent.com/57115301/95384448-40d78880-08b2-11eb-9860-c2f14ae13c8a.png)

**Comment by monicakarnes** [comment]
Ok, closing per discussion. thanks
