### ISSUE TITLE
Consultant Webpage 404 page causing error when coming from Facebook "Facebook Business Page"

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#356]

**Comment by TastefullySimple** [comment]
@mandi920 Please add details.

**Comment by mandi920** [comment]
@TastefullySimple I'm working with Julie to get the details but basically from what I understand is when they create a Facebook business page it is not letting them link to their TS page because it thinks it is a 404 page.

**Comment by TastefullySimple** [comment]
This is correct the page doesn't exist.

**Comment by mandi920** [comment]
[8:25 AM] Julie Cabinaw
    
Good news, retesting my FB page this morning with the consultant info page link, FB is now accepting the page link.  This can be closed.
