### ISSUE TITLE
Add to Cart button covering up product image on small mobile devices

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#357]
### Expected behavior
Would want either the text to shrink in these cases, have the button move down, etc. Jen mentioned you would come up with some options we could choose from.

### Actual behavior
The add to cart button is wrapping causing it to be very large.

### Steps to reproduce behavior
Go to the plp on an Iphone SE.

**Comment by jsmnglng-w** [comment]
Ticket for this issue: [TST-236](https://razoyo.atlassian.net/browse/TST-236)

**Comment by monicakarnes** [comment]
Here it is on Iphone SE - on the PLP
![image](https://user-images.githubusercontent.com/57115301/95353107-867f5b80-0888-11eb-96fa-87b5e59d3296.png)
 Here is the PDP
![image](https://user-images.githubusercontent.com/57115301/95353333-c5adac80-0888-11eb-8658-868899cbccbd.png)
 Fixed - closing

**Comment by suehamre** [comment]
This is happening again. See screenshots below: 
Samsung S10 +  -Browserstack in QA1 – Tech sandbox
![image](https://user-images.githubusercontent.com/57115316/96296725-5a18bd00-0fb5-11eb-8b04-b122c488954e.png)
Samsung S10 +   - Production 
![image](https://user-images.githubusercontent.com/57115316/96296743-643abb80-0fb5-11eb-8c71-424418a918df.png)
Iphone 11 promax – Browserstack QA1
![image](https://user-images.githubusercontent.com/57115316/96296766-6e5cba00-0fb5-11eb-89a0-7d51285be027.png)

**Comment by monicakarnes** [comment]
This is really big on the Samsung S6
![image](https://user-images.githubusercontent.com/57115301/96645976-0548af80-12f1-11eb-8239-a347ab350233.png)

**Comment by monicakarnes** [comment]
Way better on Samsung S6 
![image](https://user-images.githubusercontent.com/57115301/96931138-72d81580-1482-11eb-87ef-fb81e4795fec.png)

**Comment by monicakarnes** [comment]
Also checked more below

SS10+ 
![image](https://user-images.githubusercontent.com/57115301/96933025-62756a00-1485-11eb-9c73-6b242b744676.png)

Iphone6 
![image](https://user-images.githubusercontent.com/57115301/96933581-50e09200-1486-11eb-8cfd-32c4007e7418.png)

iphone 7 
![image](https://user-images.githubusercontent.com/57115301/96933686-884f3e80-1486-11eb-8e54-e2e6a625ef82.png)
