### ISSUE TITLE
Mobile - Consultant name is not bolded when selected

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#359]
### Expected behavior
When you have a consultant selected the name should be bolded like it is on desktop. 

### Actual behavior
In mobile, when a consultant is selected the consultants name is not bolded. Instead 'your consultant is' is bolded. See below: 
![image](https://user-images.githubusercontent.com/57115316/95248527-06e88280-07dd-11eb-838b-9e9ce092a1bd.png)

### Steps to reproduce behavior
Go to tastefullysimple.com on a mobile device and click find a consultant. 
Select the consultant
View the bottom where the consultants name is displayed. 
I duplicated this on a Samsung S10+ and iphone11

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-237](https://razoyo.atlassian.net/browse/TST-237)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/95512343-4f8b7180-097e-11eb-8811-f0dea8ec78c6.png)
![image](https://user-images.githubusercontent.com/57115301/95512504-88c3e180-097e-11eb-93cb-e5ebbd71aa63.png)
 Fixed closing
