### ISSUE TITLE
Unable to search for a party by Fundraiser name

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#361]
### Expected behavior
Users should be able to search for a party using the 'find a party' bar and search by state & host name or fundraiser name

### Actual behavior
Find a party bar is only recognizing host name. 

### Steps to reproduce behavior
Set up a Fundraiser party in myHQ 
![image](https://user-images.githubusercontent.com/57115316/95321430-a864e800-0860-11eb-9dc0-60e6ec0a0883.png)
![image](https://user-images.githubusercontent.com/57115316/95321475-b450aa00-0860-11eb-84b9-eb20e012d7bb.png)
![image](https://user-images.githubusercontent.com/57115316/95321546-ccc0c480-0860-11eb-9548-1879ec554d37.png)

Go to tastefullysimple.com and click on Find a party. 
Select a state and enter Fundraiser Name click search  - This scenario is MN and Fundraiser Name 
![image](https://user-images.githubusercontent.com/57115316/95321817-3214b580-0861-11eb-8e8b-9f46241edd6f.png)
I get the error that no party was found 
![image](https://user-images.githubusercontent.com/57115316/95321867-42c52b80-0861-11eb-8244-fb9c5590304b.png)
If I remove the fundraiser name, the party is in the search, but appearing with the host name only
![image](https://user-images.githubusercontent.com/57115316/95321973-6ab48f00-0861-11eb-9b06-1d62d590c85b.png)

![image](https://user-images.githubusercontent.com/57115316/95322012-799b4180-0861-11eb-9118-9efefc9133b5.png)

**Comment by jsmnglng-w** [comment]
@suehamre @TastefullySimple this looks like an API issue. The way we are currently searching for a party is with this API endpoint `/search/party/{state}/{page}/{size}?name={name}`. And trying it with `/search/party/mn/1/6?name=Fundraiser%20Name`, I don't get a result back.

**Comment by suehamre** [comment]
10-8  - Searching for a party by fundraiser name does pull up the party so I am closing this bug. However, I posted a message in teams to Julie asking if we should put an enhancement request in for the search results modals to show the fundraiser name in addition to the host name. Currently it only shows the host name.
