### ISSUE TITLE
Search for a Consultant sometimes hangs

### ISSUE THREAD

**Issue by TastefullySimple** [tastefully-simple/cornerstone#363]
WIN10 laptop, Chrome.
This has occurred a handful of times for me. Never on an initial search, but randomly when I repeat searching for a consultant 3 or 4 times. 

Here is the screenshot. I've left it for several minutes and it remains. If I refresh the page, I return to my prior page with the same consultant.  

![image](https://user-images.githubusercontent.com/53190431/95345965-eeca3f00-0880-11eb-9774-491e05038ca2.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-240](https://razoyo.atlassian.net/browse/TST-240)

**Comment by monicakarnes** [comment]
Seems to be fixed, can't duplicate now..
