### ISSUE TITLE
Order affiliated with a Party and able to shop with HQ as consultant

### ISSUE THREAD

**Issue by TastefullySimple** [tastefully-simple/cornerstone#364]
Have there been any reports of orders coming through with a party attached and associated with HQ as the consultant? 	
I searched for a consultant by zip code (55357) and 25 miles. 
	I selected Holly Munsterteiger
	I visited Holly's page (which affiliated me with Holly)
	I selected a party on her list (which affiliated me with the party)
	All good so far. 
	Then, I decided to search for another consultant by zip code (55357), exact. There are no consultants in this zip code, and I selected the 'Shop with Tastefully Simple' from the blue bar at the bottom of the Search window.
![image](https://user-images.githubusercontent.com/53190431/95346470-8334a180-0881-11eb-96de-88b59e228be6.png)

The result was that I was affiliated with HQ as a consultant, and the Party affiliation remained. Should the party affiliation been removed? Is it possible the logic that would have removed it does not kick off when selecting the blue bar "shop with TS"

![image](https://user-images.githubusercontent.com/53190431/95346531-95164480-0881-11eb-9639-73e5198e473b.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-239](https://razoyo.atlassian.net/browse/TST-239)

**Comment by richierubin** [comment]
This was a problem in BigCommerceJobs.  The fix is currently in place in QA where I do a check if the partyID is not 0, and the consultant is the default for that environment.

**Comment by monicakarnes** [comment]
Looks like this is fixed- I started with consultant in header,  added item to cart, selected a party under that consultant, clicked to edit my consultant, and used the zip code provided above (55357) - no results so then selected to continue with TS consultant and it updated, my cart and header and removed my party as I would expect. 
![image](https://user-images.githubusercontent.com/57115301/95772700-ca0c0800-0c82-11eb-993b-906838920728.png)

![image](https://user-images.githubusercontent.com/57115301/95772750-dee89b80-0c82-11eb-9775-506e8912324c.png)


![image](https://user-images.githubusercontent.com/57115301/95772628-ab0d7600-0c82-11eb-9147-bb70ce77fce4.png)
