### ISSUE TITLE
Mobile- Consultant Image and Verbiage is not showing completely 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#365]
Here is how it should display for image and verbiage - 
![image](https://user-images.githubusercontent.com/57115301/95348267-7a44cf80-0883-11eb-8582-c24f4ae44f33.png)

Iphone 11 ProMax-- before I have selected my party- 
![image](https://user-images.githubusercontent.com/57115301/95347724-d2c79d00-0882-11eb-9e7a-eea7be610bde.png)
after I have selected my party 
![image](https://user-images.githubusercontent.com/57115301/95347760-deb35f00-0882-11eb-87a6-058576cdcfeb.png)

Iphone 7 
![image](https://user-images.githubusercontent.com/57115301/95347824-f7bc1000-0882-11eb-9d16-c8763228de5c.png)

Samsung Galaxy S9 plus 
![image](https://user-images.githubusercontent.com/57115301/95347879-086c8600-0883-11eb-8273-44ab8da734d2.png)

Samsung Galaxy S7 
![image](https://user-images.githubusercontent.com/57115301/95347932-191cfc00-0883-11eb-9634-05cbde177635.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-238](https://razoyo.atlassian.net/browse/TST-238)

**Comment by monicakarnes** [comment]
Seems that if they haven't selected a consultant yet, and TS is who they are shopping with that that these are still cut off..  Can you please make the adjustment there as well. 
Samsung 10 plus 
![image](https://user-images.githubusercontent.com/57115301/95381201-6ca43f80-08ad-11eb-9248-0a03f8b73d51.png)
Samsung 9 plus 
![image](https://user-images.githubusercontent.com/57115301/95381749-34513100-08ae-11eb-90ed-709cde771eba.png)
Samsung galaxy s7 
![image](https://user-images.githubusercontent.com/57115301/95381908-75494580-08ae-11eb-8437-922d20b0e13a.png)

and Iphones- are ok but not great for TS consultant - 
iphone 7 
![image](https://user-images.githubusercontent.com/57115301/95382125-cc4f1a80-08ae-11eb-954d-b7fc6835e595.png)

Iphone 11 Pro Max 
![image](https://user-images.githubusercontent.com/57115301/95382267-01f40380-08af-11eb-8b69-9ce7a4a18d9e.png)


looks better on Iphones/samsungs.. when a consultant is selected..
Iphone 
![image](https://user-images.githubusercontent.com/57115301/95380999-28b13a80-08ad-11eb-81c2-abcfeaf26537.png)
 samsung
![image](https://user-images.githubusercontent.com/57115301/95382327-19cb8780-08af-11eb-9a64-e4c9c3f4ac74.png)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/95479991-fb1dcd00-0950-11eb-9e08-424a15b27d5d.png)
![image](https://user-images.githubusercontent.com/57115301/95480028-040e9e80-0951-11eb-93b9-0be3b46a4c04.png)
Thank you looks good - closing
