### ISSUE TITLE
Clients able to use the spacebar to get past entering phone # which then turns into 999.999.9999

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#368]
Client can enter spacebar to get past entering a valid phone number through the check out process. They should not be able to enter in just spacebar to bypass this required field. 

![image](https://user-images.githubusercontent.com/57115301/95386241-9dd43e00-08b4-11eb-8ac0-5f831083ab90.png)

![image](https://user-images.githubusercontent.com/57115301/95386300-af1d4a80-08b4-11eb-8f43-0e4b7ea696b8.png)

When they do that, the system, then enters in all 9's for the phone number. 999.999.9999 here you can see the order in myHQ 
![image](https://user-images.githubusercontent.com/57115301/95386469-f9063080-08b4-11eb-9c72-e9b1c4e3aa25.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-242](https://razoyo.atlassian.net/browse/TST-242)

**Comment by monicakarnes** [comment]
Can you please implement these same changes on the Mobile Phone as well? 
Not allowed to enter just spacebar
No letters
No Special Characters 

![image](https://user-images.githubusercontent.com/57115301/95781034-a05add00-0c92-11eb-802d-235114e0ac97.png)

**Comment by monicakarnes** [comment]
Sorry this still is allowing me to start with a space for the phone number and then also do characters and letters. 

I started with clean cookies :(  

![image](https://user-images.githubusercontent.com/57115301/96032091-d1b6e280-0e23-11eb-8990-73499aaa8107.png)

**Comment by monicakarnes** [comment]
Sorry didn't mean to close it, as its still an issue.... wrong button...

**Comment by jsmnglng-w** [comment]
@TastefullySimple it looks like PR #382 is not yet published. I can still see my old code in Tech Sandbox

**Comment by monicakarnes** [comment]
Thanks now I see it and it works, closing bug
