### ISSUE TITLE
Consultant webpage URL wraps 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#369]
CID 21235 contacted us regarding how her web url displays on her website.   It looks like the 1 wraps to the second line.  Is there any way around the wrapping of the web url?

![image](https://user-images.githubusercontent.com/57115301/95403576-39c37100-08d8-11eb-9da0-f6ba27d1b558.png)

**Comment by TastefullySimple** [comment]
This fix needs to be made it shogun. I detailed the fix to Jackie and Julie on Tuesday.
