### ISSUE TITLE
Find a consultant in Header, then you click to webpage, then click to find new- Page displays 2 different consultants

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#373]
So I started by selecting a consultant in the header, and then clicked to view the webpage for that consultant... ID # 2051
![image](https://user-images.githubusercontent.com/57115301/95485164-f8be7180-0956-11eb-8559-6c3d9a0162ac.png)

then I clicked on the edit in the Header to find a different consultant, which took me to the find consultant modal, and I entered in ID # 112 - it updated my consultant name in the header, but didn't refresh the page below to show Sheri' page and you can see also in the screen shot that the web URL is also still on my consultant ID# 2051 Cone 

![image](https://user-images.githubusercontent.com/57115301/95485294-23a8c580-0957-11eb-8fb0-6efc940900dd.png)

Good news is that if if clicked to go to the cart, that the consultant info does update, in the cart with the correct consultant. 
![image](https://user-images.githubusercontent.com/57115301/95485457-5fdc2600-0957-11eb-8f39-fd907def43a0.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-241](https://razoyo.atlassian.net/browse/TST-241)

**Comment by monicakarnes** [comment]
Fixed Thanks!
