### ISSUE TITLE
Mobile - Cannot click on cart when menu is open

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#377]
### Expected behavior
When on a mobile device, user should be able to click on the cart icon and go to the cart. 

### Actual behavior
When on a mobile device, user is not able to click on the cart icon and go to the cart. 

### Steps to reproduce behavior
Happens on Android/Chrome and Iphone/Safari
Have items in your cart.
Open the menu and click on the cart icon, nothing happens.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-243](https://razoyo.atlassian.net/browse/TST-243)

**Comment by monicakarnes** [comment]
I have tested this on Samsung 10+  Samsung 7, Samsung 6 , iPhone 11 Pro Max, iPhone 7 and its fixed 

Closing
