### ISSUE TITLE
Some client accounts did not get migrated that should have 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#379]
### Expected behavior
Clients that had logged into their accounts within the last 24 months should have been migrated over to Big C. 

### Actual behavior
There are a few reports of clients who are not receiving the forgot password and do not appear to have been migrated to Big C. 

### Steps to reproduce behavior
Examples of clients in PRODUCTION 
From Zendesk Tickets:
When viewing reporting services username report Betty Sue srednasb@gmail.com ​has a last login time stamp of 5/5/2020 
![image](https://user-images.githubusercontent.com/57115316/95631626-a447ee80-0a49-11eb-8d20-5033ae4fe594.png)
When I view the Customer search in Big C her email address in not in our system.
Can you check into this for us?
We have had many cases where clients are not showing in the Customer search and they have tried multiple times to reset password as directed only to not get a reset password email delivered.
![image](https://user-images.githubusercontent.com/57115316/95631899-1caeaf80-0a4a-11eb-8b28-22872fc0e212.png)

Another example from PRODUCTION
momz74@yahoo.com 
![image](https://user-images.githubusercontent.com/57115316/95632058-72835780-0a4a-11eb-929f-13e4c42b3901.png)

**Comment by richierubin** [comment]
Moving records over to the new system is a convenience thing for the customers, and there are some that did not import (took 10 hours with prod data).  If customers create a new user account in BC with the same email that exists in our system their previous orders, etc. will all get associated with this email address.

**Comment by suehamre** [comment]
I've updated CS and the zendesk ticket lettting them know to have the clients create new accounts.
