### ISSUE TITLE
Mobile - Red party bar-   After clicking to cart- then go click back to menu 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#389]
### Expected behavior
Party bar should remain Green unless, you are within the cart and do not have a party selected then it would be Red. 

### Actual behavior
I'm getting the Red party bar, on mobile, if I've been to the cart, and then click back into the menu

![image](https://user-images.githubusercontent.com/57115301/96641896-feb73980-12ea-11eb-81ee-44f0d78df54a.png)

![image](https://user-images.githubusercontent.com/57115301/96641917-05de4780-12eb-11eb-80c8-c0c6048fa92c.png)

![image](https://user-images.githubusercontent.com/57115301/96641932-0b3b9200-12eb-11eb-9497-35a14eb72cce.png)

### Steps to reproduce behavior
Iphone, 11 Pro Max, Iphone 7  Samsung S10+ 

Clicked to find a consultant
Selected a consultant
Shop for item
Add item to cart
Click into Cart
Click on 3 lines to get back to the Menu
See the Red party bar, with no selected party 
Click to arrow to see product drop menu, Product menu opens, close menu
Then you see the Green party bar again.

**Comment by jsmnglng-w** [comment]
@monicakarnes can you clarify this part. I don't quite understand it. I guess which arrow do I click to see the product drop menu? 😅
```
Click to arrow to see product drop menu, Product menu opens, close menu
Then you see the Green party bar again.
```

**Comment by monicakarnes** [comment]
@jsmnglng-w  yep sorry here hopefully this helps :)
![image](https://user-images.githubusercontent.com/57115301/96643326-05df4700-12ed-11eb-8426-93ac2d2008aa.png)
![image](https://user-images.githubusercontent.com/57115301/96643356-11327280-12ed-11eb-961d-910a959f3a9e.png)

**Comment by jsmnglng-w** [comment]
@monicakarnes I tried replicating it and I'm in the cart page but I don't get the green find party bar when clicking on the mobile menu and then clicking the product drop down. It still remains red. From your screenshot, you might be not in the cart page, that's why it's green? But for the expected behavior, are you saying that even though you're in the cart page and then click on the mobile menu, the party bar should be green even though there is no party selected?

**Comment by monicakarnes** [comment]
@jsmnglng-w   Yes when on mobile, You should only see the Red party bar when no party is selected and you are in the shopping cart.   If you are not in the shopping cart, you should see the Green party bar.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-263](https://razoyo.atlassian.net/browse/TST-263)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/97642166-80594680-1a12-11eb-9412-7ce785bd9fd4.png)
closing bug
