### ISSUE TITLE
Join Release - Message missing when submitting a zip code search and no qualified consultants are found

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#39]
### Expected behavior
When submitting a zip code search and no qualified consultants are found and the HQ consultant is returned the following message should be displayed between the Tastefully Simple sponsor box and the Independent Consultant Agreement box: There is not a consultant in the area you've specified, but not to worry! We will contact you shortly to help you find the best sponsor near you.
![image](https://user-images.githubusercontent.com/57953952/73960159-fd1a2280-48cf-11ea-8f78-757f098a186d.png)

### Actual behavior
No message is displayed

### Steps to reproduce behavior
Search for a consultant in an area that no results will be returned. Zip code used while testing was 61554.

**Comment by TastefullySimple** [comment]
Added message 
> There is not a consultant in the area you've specified, but not to worry! We will contact you shortly to help you find the best sponsor near you.
