### ISSUE TITLE
Mobile- Auto Selected Party- when you have multiple page results 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#390]
### Expected behavior
I would expect that I have to make a selection, and it doesn't auto make one for me with multiple pages to select from 

### Actual behavior
When you search for a party example, State of MN, and click search You receive 3 pages, of results of open parties..... on page 3 the  last page only one party is displayed here, but it is auto selected --- but shouldn't be 

### Steps to reproduce behavior

Mobile that I have seen this on, - Iphone 11 ProMax, Samsung 10+ Samsung 6 

![image](https://user-images.githubusercontent.com/57115301/96642769-3b376500-12ec-11eb-9f9e-bed424c6ce27.png)

![image](https://user-images.githubusercontent.com/57115301/96642794-44283680-12ec-11eb-9551-67516f8c0ef1.png)

![image](https://user-images.githubusercontent.com/57115301/96642744-2e1a7600-12ec-11eb-98e3-6363f29c40ff.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-260](https://razoyo.atlassian.net/browse/TST-260)

**Comment by monicakarnes** [comment]
This is fixed on desktop and mobile- closing bug Thanks!
