### ISSUE TITLE
Add to Cart Indicator is not updating upon adding items to the cart 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#392]
### Expected behavior
When you add an item to the cart, the item should be added to the cart and the Cart indicator count bubble should update accordingly to match the number of items, you have added. 

### Actual behavior
When you add an item to the cart, the cart indicator count didn't update as it should. 
However if you click into the cart, to view, then it refreshes and the count increases. 

### Steps to reproduce behavior
Shop products select and add items to cart
Take a look at the shopping cart and see that your cart indicator count doesn't increase as you add items 

Desk top view- 
added item to cart no change to cart indicator
![image](https://user-images.githubusercontent.com/57115301/96738531-708f9180-1384-11eb-8c18-03e6e7e25f4a.png)

Added item to cart and viewed cart 
![image](https://user-images.githubusercontent.com/57115301/96739356-54d8bb00-1385-11eb-8dd8-9b0aa1709079.png)

Continue searching on the sight and now you can see the count cuz you have been to the cart 
![image](https://user-images.githubusercontent.com/57115301/96739506-789c0100-1385-11eb-8ea0-336dcbe6c975.png)

Mobile view 
add an item no change to cart indicator
![image](https://user-images.githubusercontent.com/57115301/96738772-ae8cb580-1384-11eb-8911-1d641ecffcb8.png)

After I add item to my cart- and clicked to view the cart 
![image](https://user-images.githubusercontent.com/57115301/96738949-e136ae00-1384-11eb-9d0d-6cae7b7394d3.png)

Back to searching for items - now you can see the count 
![image](https://user-images.githubusercontent.com/57115301/96739095-0aefd500-1385-11eb-8eb4-cf58b7014928.png)

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-262](https://razoyo.atlassian.net/browse/TST-262)

**Comment by monicakarnes** [comment]
Desktop is working 
![image](https://user-images.githubusercontent.com/57115301/97035986-c30bb200-152c-11eb-9566-490be151866d.png)

Working on Mobile SS6, ss10+, iphone11PM, iphone 7, Ipad7th
![image](https://user-images.githubusercontent.com/57115301/97036430-6fe62f00-152d-11eb-9acc-26ea2c8c5b6d.png)
