### ISSUE TITLE
Welcome to my party- Party details are missing - All party types

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#395]
Here is what I see in QA1 now 
![image](https://user-images.githubusercontent.com/57115301/97020039-af555100-1516-11eb-8ac6-7d616c9d8a4b.png)

Here is what I see currently in Production and what we need to see and keep 

![image](https://user-images.githubusercontent.com/57115301/97020116-c85e0200-1516-11eb-92c3-6ae099dfed50.png)

**Comment by staciejurczak** [comment]
Ticket was created for this https://razoyo.atlassian.net/browse/TST-266

**Comment by jsmnglng-w** [comment]
@monicakarnes The API for the party details page has been fixed. The party details are now showing again.

@TastefullySimple should there be any handling of other return values besides the data being returned? Or it is safe to say that when you select a party from "Find a party", that selected party is available/valid and will always show in the party details page?

**Comment by monicakarnes** [comment]
@jsmnglng-w  Thank you, yes I'm now seeing the party details  again 
![image](https://user-images.githubusercontent.com/57115301/97194056-b202b100-1777-11eb-8dd2-d22c90308d10.png)

**Comment by mandi920** [comment]
@monicakarnes - can this be closed?

**Comment by monicakarnes** [comment]
LOOKS like we broke this again though

![image](https://user-images.githubusercontent.com/57115301/98011905-1946e380-1dbe-11eb-8565-09b9848f0569.png)

**Comment by jsmnglng-w** [comment]
@monicakarnes I'm currently working on the closed-party feature that's why the Party Details page is affected currently

**Comment by monicakarnes** [comment]
@jsmnglng-w  Thanks for letting me know 👍

**Comment by monicakarnes** [comment]
@jsmnglng-w  Did you ever get the answer to your question you had listed above?

**Comment by jsmnglng-w** [comment]
@monicakarnes yes, I think the answer for my question was the closed-party feature will account for that, and this is ready for QA 😄

**Comment by monicakarnes** [comment]
@jsmnglng-w  Good, Yes I seen that this is working again- Closing bug - thanks!

![image](https://user-images.githubusercontent.com/57115301/98702705-57a14d00-2340-11eb-81d4-1d32842338ac.png)
