### ISSUE TITLE
Low Priority: Join Release - Change wording under find your sponsor to match fields

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#40]
### Expected behavior
On the tell us about yourself page the second sentence under 2. Find Your Sponsor should say: Search by consultant ID, consultant name or zip code.

### Actual behavior
Currently says: Search by name/ID, or search by location. Since the input boxes are different than the mockup this no longer makes sense.

**Comment by monicakarnes** [comment]
Fixed, Closing bug
