### ISSUE TITLE
PROD BUG: Consultant photo in cart does not update when party & Consultant have changed. 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#404]
### Expected behavior
The consultants photo in the cart should be updated whenever the consultant selected changes.

### Actual behavior
The consultant photo in the cart is not updating when the selected party and consultant changes. 

### Steps to reproduce behavior
Selected CID#119862 - Adrienne Swanson as the consultant. 
Did find a party and selected one of her parties. 
Added item to cart
Copied a party URL into the browser for Jacki Pitkow https://www.tastefullysimple.com/p/11339734 
The consultant and party is updated as expected but it is still displaying Adrienne's picture. 
![image](https://user-images.githubusercontent.com/57115316/97631179-965d0c00-19fe-11eb-99c7-a91371fb3815.png)

**Comment by suehamre** [comment]
I was able to duplicate this in QA1 also.

**Comment by jsmnglng-w** [comment]
Created a ticket for this issue: [TST-280](https://razoyo.atlassian.net/browse/TST-280)

**Comment by monicakarnes** [comment]
here is what I started with, for Stephanie, and Ottos' party 
![image](https://user-images.githubusercontent.com/57115301/98011294-46df5d00-1dbd-11eb-814b-67285c27111a.png)
I then copied and pasted in the link for the party https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370803 
for Sheri and now it looks like it updated, my consultant, photo, and party correctly 
![image](https://user-images.githubusercontent.com/57115301/98011470-7ee6a000-1dbd-11eb-98f4-1c664b9d0dce.png)
 Closing bug
