### ISSUE TITLE
Quantities Doubling in Cart

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#407]
### Expected behavior
When I click add to cart from the product list page view I would expect one item to be added to my cart.

### Actual behavior
When you use add to cart from the product list page view two items are added to my cart instead of one.

### Steps to reproduce behavior
Go to https://www.tastefullysimple.com/desserts-baking hover over the Cinnamon Muffin Melt Mix product - click the add to cart button. You will see two were added to the cart.

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-282

**Comment by TastefullySimple** [comment]
Working are desktop.
@monicakarnes would you please test on mobile.

**Comment by monicakarnes** [comment]
Seems to be working on mobile, looked at SS10+, SSS6, iphone 11promax and iphone 7
