### ISSUE TITLE
Low Priority: Join Release - Change case

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#41]
### Expected behavior
On the tell us about yourself page the in the 2. Find Your Sponsor section we would like the following changes:
Search by consultant ID > Search by Consultant ID
Search by consultant name > Search by Consultant Name
Search near me > Search Near Me
Select your sponsor > Select Your Sponsor

**Comment by monicakarnes** [comment]
Fixed closing bug
