### ISSUE TITLE
Not seeing any Staff Notes as expected for affiliations 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#413]
Expected from US P1B- 190
When the order is placed, grab the consultant ID and or Party ID and then call the storefront API to deal with the cart, and in the cart, set the Consultant ID and the Party ID in the staff notes field.

Actual results
I'm not seeing any Staff notes listed upon checkin the order 

Reproduce Steps
Added item to my cart
Find a consultant search for ID 2051
Find a party search - Stephanies' party
Click on cart icon, then click view cart
Check out as a guest   my order # 1095
Check BC order and staff note section
![image](https://user-images.githubusercontent.com/57115301/98299180-e565ec80-1f7c-11eb-9934-b165e5da9502.png)
![image](https://user-images.githubusercontent.com/57115301/98299188-eac33700-1f7c-11eb-9bdf-359a3b139215.png)
![image](https://user-images.githubusercontent.com/57115301/98299228-f878bc80-1f7c-11eb-9c47-67934f5eddf8.png)

**Comment by TastefullySimple** [comment]
This feature was cut. Not technically possible
