### ISSUE TITLE
WebhookCartaffiliation is not capturing the cart info when shopping with Tastefully Simple

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#417]
### Expected behavior
The webhookcartaffiliation should log all carts with items in it and include the following: 
 When client is in the cart, the system needs to be smart enough to know that if they have items, the system should make an API call to capture the BC cart ID, consultant ID and the Party ID.  This will occur before checkout.

### Actual behavior
When I am in the cart and shopping with Tastefully Simple, nothing is being logged to the webhookcartaffiliation table. 

### Steps to reproduce behavior
Start with clean cookies and go to tastefullysimple.com 
Add items to cart
View cart 
View webhookcartaffiliationtable

**Comment by TastefullySimple** [comment]
Nothing would show up as cookie data is not set.

**Comment by suehamre** [comment]
Chatted through this at stand up and confirmed this is not a bug. Closing.
