### ISSUE TITLE
Product quick view modal has horizontal scroll bars (Desktop)

### ISSUE THREAD

**Issue by TastefullySimple** [tastefully-simple/cornerstone#418]
### Expected behavior
Product quick view modal **should not** have horizontal scroll bars

### Actual behavior
Product quick view modal has horizontal scroll bars 

### Steps to reproduce behavior
Open the quick view for a production in QA1 or production.
Add the bottom of the modal notice the scroll bar.
![image](https://user-images.githubusercontent.com/53190431/98723234-b625f580-2357-11eb-98aa-4d8f0ef9a71e.png)

**Comment by jsmnglng-w** [comment]
https://razoyo.atlassian.net/browse/TST-295

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/99594489-dd646e80-29b8-11eb-81f6-71b91eedd6ca.png)
closing
