### ISSUE TITLE
Search for Product box- When you add item - Redirects to cart and shouldn't 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#419]
### Expected behavior
When you add items to your cart, it shouldn't redirect you to the cart page

### Actual behavior
When you search for items using the keyword or product # text box and click on add item to cart, it adds it and automatically redirects you to the cart. 
 

### Steps to reproduce behavior
go to website
go to search box
![image](https://user-images.githubusercontent.com/57115301/98740370-8df6c080-2370-11eb-8c37-7e5e9b504499.png)
Type in keyword- examples- cake, beer, drink--- then click search icon to get your results 
review your results, select one of your results and add to cart 
![image](https://user-images.githubusercontent.com/57115301/98740511-cd251180-2370-11eb-9014-5ba2a83dae3c.png)
it automatically redirects you to the cart and added your item 
![image](https://user-images.githubusercontent.com/57115301/98740682-137a7080-2371-11eb-823c-ec27aa99e363.png)

It should have allowed you to continue to shop and not taking you to the cart .

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-289

**Comment by monicakarnes** [comment]
fixed - closing
