### ISSUE TITLE
JOIN- Error Message - Please provide an ID 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#421]
### Expected behavior
When the client is trying to join, and they have already sign up, after they enter in their same personal information and click on checkout they should receive the message "If you continue to experience issues, please contact the customer service team at 866.448.6446 

Unless we want it to also reflect your cart message as well - This information is already associated to an active consultant account, Please contact  The Customer Service team with questions at 866.448.6446

### Actual behavior
I'm receiving an Error  " Please provide an ID"    along with the customer service message. 
![image](https://user-images.githubusercontent.com/57115301/98850339-3e6ccf00-241a-11eb-8b5b-14d2d056dad9.png)

### Steps to reproduce behavior
Note- my client has already joined and is an active consultant- table status 50 
Client details below
Mr Ross Gellar
email address RossG@mailinator.com  Password Beerbread1! 
SSN 837-23-7747 
DOB 10/18/1988
Address 3700 S Plaza Dr Santa Ana CA 92704 

Went to join, went to log in page signed in via email and password
Got to kit page, clicked on next
Enter in all of my same personal information
Selected sponsor and agreed to T & C 
Clicked on Checkout
Received error message

**Comment by TastefullySimple** [comment]
What should the message say? We didn't change any error message on the Join sign up forms.

**Comment by monicakarnes** [comment]
@TastefullySimple  So looking at this- I'm sorry but it attached the wrong screen shot above here is the one that should have been attached is below... and we need to remove  "Please provide an ID "  as they won't be able to do that on here. 
![image](https://user-images.githubusercontent.com/57115301/98955299-5567fb80-24c4-11eb-96c3-2d27f95f91b9.png)

We could also update, the message to reflect that they are already a consultant for this situation and update the message to reflect that.. "This information is already associated to an active consultant account, Please contact The Customer Service team with questions at 866.448.6446"  OR just leave the remaining message "If you continue to experience issues please contact the customer services team at 866.448.6446

**Comment by TastefullySimple** [comment]
> We could also update, the message to reflect that they are already a consultant for this situation and update the message to reflect that.. "This information is already associated to an active consultant account, Please contact The Customer Service team with questions at 866.448.6446" OR just leave the remaining message "If you continue to experience issues please contact the customer services team at 866.448.6446
This is an enhancement request.

**Comment by monicakarnes** [comment]
Ok, for now can you just remove the "Please provide an ID"

**Comment by TastefullySimple** [comment]
Please provide an ID is a real error message. It means the form isn't sending the cart id.

**Comment by monicakarnes** [comment]
K, closing
