### ISSUE TITLE
Wrong consultant image in shopping cart - happens when following a link to a different consultant after being affiliated to a party 

### ISSUE THREAD

**Issue by TastefullySimple** [tastefully-simple/cornerstone#422]
Search for and affiliated with Sue's Test Party
![image](https://user-images.githubusercontent.com/53190431/98998386-ad6e2480-24fb-11eb-90d4-3c1d39a721a9.png)

I followed Karen's link https://tastefully-simple-sandbox-2.mybigcommerce.com/web/khuntley
The affiliation works. 
![image](https://user-images.githubusercontent.com/53190431/98998496-d4c4f180-24fb-11eb-993b-334a9ac9b228.png)

When I go back to the cart I see Betty's image and not Karen's. 
The consultant name is correct and the party affiliation was removed.
![image](https://user-images.githubusercontent.com/53190431/98998587-050c9000-24fc-11eb-9700-dc9af5e85810.png)

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-291

**Comment by jsmnglng-w** [comment]
@TastefullySimple this was done in Shogun. The issue was caused by the consultant image cookie not being updated whenever the user goes to a consultant page. I updated the **Consultant page - script** in Shogun to set the correct consultant image cookie. And it is now ready for testing

**Comment by monicakarnes** [comment]
This is fixed, Started with consultant and party added item  went to cart, then pasted in URL link for webpage to another consultant. and displayed the correct image
