### ISSUE TITLE
Closed party message- when no consultant is affiliated 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#423]
### Expected behavior
When the user clicks a link to a closed party and there is no consultant affiliation and they are  brought to the new page please update the message to be: ‘Darn this party is closed’ and nothing else.

Because I had clean cookies, I have no associated party or consultant so I should still see in the header Find a consultant and the party bar should say Find a party 

So like this but without the mess of my crossed out verbiage.. 
![image](https://user-images.githubusercontent.com/57115301/99006789-a7cb0b80-2508-11eb-8928-fe49c874bb9a.png)

### Actual behavior
I'm getting to the party detail page, and also has Null information listed 
![image](https://user-images.githubusercontent.com/57115301/99006136-99302480-2507-11eb-8170-bcd598d8ae32.png)

### Steps to reproduce behavior
Started with clean cookies
went to Tastefully Simple site
went to my closed party link 
https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370812
Michelle Za’s closed party link  Under Jennifer Cons 43454 
Got the party details page

**Comment by jsmnglng-w** [comment]
https://razoyo.atlassian.net/browse/TST-292

**Comment by monicakarnes** [comment]
Looks like this worked now for closed party, including the header and party bar
![image](https://user-images.githubusercontent.com/57115301/99113177-66903580-25b4-11eb-8e6e-11306a9be36e.png)
