### ISSUE TITLE
Closed party- Consultant no longer in header - its says Null is my consultant 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#424]
### Expected behavior
if there is an affiliated consultant in the banner (not using the link) the original message should be displayed: Darn, this party is over, but there’s more fun in store!

 The affiliated consultant will be in the header, And the affiliated consultants parties will be displayed on the page. 

### Actual behavior
I'm seeing the Consultant information change to Null is your consultant 

### Steps to reproduce behavior
here is where I started, consultant selected in my header, ID 2051 
![image](https://user-images.githubusercontent.com/57115301/99007477-e7462780-2509-11eb-80b2-c80943debf57.png)

clicked over to my closed party link 
https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370812

See my consultant is NULL is my consultant 
![image](https://user-images.githubusercontent.com/57115301/99007592-21afc480-250a-11eb-9361-e01b1e3008dc.png)

**Comment by jsmnglng-w** [comment]
https://razoyo.atlassian.net/browse/TST-293

**Comment by monicakarnes** [comment]
Seems to be working, my consultant remained as it should for who I had selected 
![image](https://user-images.githubusercontent.com/57115301/99113904-9b50bc80-25b5-11eb-8438-42035c7c4600.png)
