### ISSUE TITLE
Receiving 'Congratulations' confirmation page and should not be

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#425]
### Expected behavior
When checking out with regular products, user should receive the normal confirmation page. 

### Actual behavior
After starting down the join path and navigating away, and checking out with regular products I receive the 'Congratulations' confirmation page. 

### Steps to reproduce behavior
Cleared cookies  - went directly to join and did the sign up: 
![image](https://user-images.githubusercontent.com/57115316/99010689-19f31e80-2510-11eb-8525-d494f299b32b.png)
Went to personal info page, did not fill out any info, clicked on recipes, then clicked blog, then clicked shop and went to dressings and oils and added an item to my cart. I get the pop up: 
![image](https://user-images.githubusercontent.com/57115316/99010729-31caa280-2510-11eb-8bee-7bbe2baf196d.png)
Selected I don’t wish to join at this time: 
The pop is removed and I still see both the join kit and the avocado oil in my cart: 
![image](https://user-images.githubusercontent.com/57115316/99010765-427b1880-2510-11eb-9006-2578a8d1ee0a.png)
I click checkout: 
The bbok is removed as it should be: 
![image](https://user-images.githubusercontent.com/57115316/99010791-4eff7100-2510-11eb-9232-04abebecc486.png)
Entered same email address I did on sign up and checked out as a guest:
![image](https://user-images.githubusercontent.com/57115316/99010815-5b83c980-2510-11eb-8495-1fd4c98fb348.png)
I receive the 'Congratulations' confirmation page: 
![image](https://user-images.githubusercontent.com/57115316/99010873-78200180-2510-11eb-8068-e8a0bb1f3dbd.png)

**Comment by jsmnglng-w** [comment]
https://razoyo.atlassian.net/browse/TST-294

**Comment by monicakarnes** [comment]
Followed steps above and I got the correct confirmation page
![image](https://user-images.githubusercontent.com/57115301/99119274-92181d80-25be-11eb-82e1-b5a7191f43b1.png)
