### ISSUE TITLE
View cart button is not visible when placing a large order

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#429]
### Expected behavior
User should be able to click on the cart icon and see the 'view cart' button and click to go to their cart. 

### Actual behavior
When there are several items in the cart and the user clicks the cart icon, they are not able to see the 'view cart' button and there is no scroll bar within that dropdown view. The only scroll bar is in the background. 

### Steps to reproduce behavior
Go to ts.com and add several items to your cart. 
Click the cart icon on the top right to get the cart pop up to display and view. 
![image](https://user-images.githubusercontent.com/57115316/99320778-fabb0080-2831-11eb-9426-07e0a8caabc4.png)

**Comment by staciejurczak** [comment]
https://razoyo.atlassian.net/browse/TST-296

**Comment by monicakarnes** [comment]
Looks like this is working now, I can see with small screen that I have a scroll bar, and can scroll down to get to the view cart page 
![image](https://user-images.githubusercontent.com/57115301/99996061-d9519b80-2d80-11eb-9522-369f6b9bcad6.png)

![image](https://user-images.githubusercontent.com/57115301/99996085-e4a4c700-2d80-11eb-866f-c3b25b79b5f2.png)
and if clicked it takes me to the cart as expected 
![image](https://user-images.githubusercontent.com/57115301/99996177-ff773b80-2d80-11eb-8c79-6ba076c5ba62.png)
