### ISSUE TITLE
Join Release - Edit cart - Image overlays on the verbiage

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#43]
### Expected behavior
The image does not cover up any of the wording on the cart page.

### Actual behavior
The BBOK image is covering up the B in Business Blast Off Kit

### Steps to reproduce behavior
Click to Edit my cart. And below you can see that the image is squishing the verbiage and covering it up. 
![image](https://user-images.githubusercontent.com/57953952/73984072-6c5a3b80-48fd-11ea-8fd0-62b4e2890ec7.png)
![image](https://user-images.githubusercontent.com/57953952/73984090-7b40ee00-48fd-11ea-8d4a-e760dc1be338.png)

**Comment by TastefullySimple** [comment]
Adjusted column padding

**Comment by monicakarnes** [comment]
check done
