### ISSUE TITLE
Default consultant photo missing in shopping cart

### ISSUE THREAD

**Issue by TastefullySimple** [tastefully-simple/cornerstone#432]
Step to reproduce.
1. follow this party link https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370755
2. Add a product to your cart.
3. Go to the shopping cart. No consultant photo
![image](https://user-images.githubusercontent.com/53190431/99682586-fdda0a80-2a44-11eb-82ce-c600ae4e2ed2.png)

I noticed when I selected a party with a consultant that had a real photo it worked.
1. follow this party link  https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370801
2. Add a product to your cart.
3. Go to the shopping cart. Consultant photo displayed. 
![image](https://user-images.githubusercontent.com/53190431/99682931-688b4600-2a45-11eb-8e23-72ccd75d2fb2.png)

**Comment by jsmnglng-w** [comment]
https://razoyo.atlassian.net/browse/TST-299

**Comment by monicakarnes** [comment]
Used this open party link- https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370813 
and it worked 
![image](https://user-images.githubusercontent.com/57115301/99999035-38191400-2d85-11eb-92e0-f9c0f83dcf1b.png)

Also tried for closed party link  with clean cookies no consultant in my banner to begin with  https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370842 

get the closed page as I should 
![image](https://user-images.githubusercontent.com/57115301/99999164-5aab2d00-2d85-11eb-9f53-8c37d622a1d7.png)
added item to my cart and it looks right with TS 

Also tried same link but with the consultant in my header and it looks right too 
![image](https://user-images.githubusercontent.com/57115301/99999333-9d6d0500-2d85-11eb-970f-78efe1eba13a.png)


Closing bug
