### ISSUE TITLE
Consultant is cleared from banner after placing an order and should not be

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#433]
### Expected behavior
Consultant should remain in banner until the user either selects a different consultant or clears cookies. 

### Actual behavior
Consultant is being cleared from banner after order is placed. 

### Steps to reproduce behavior
Started with clean cookies
Added items to cart
Selected a consultant -CID #28
Went to cart 
Verified cart notification table 
Copied a closed party link in browser  - https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370585
Got the ‘darn party is over message’ 
Went to cart 
Checked out
![image](https://user-images.githubusercontent.com/57115316/99690627-fa974c80-2a4d-11eb-8474-806b6f1925af.png)
After placing the order, I clicked the TS logo to go back to the home page,  and my consultant is cleared from the header and should not be because I did not clear cookies. 
![image](https://user-images.githubusercontent.com/57115316/99690653-fff49700-2a4d-11eb-95fb-ba0634ad63f9.png)

**Comment by TastefullySimple** [comment]
Fixed order confirmation javascript. Business Sandbox and Prod had the correct version.

**Comment by suehamre** [comment]
Retested. Fixed. :)
