### ISSUE TITLE
Affiliation- Went back to previous consultant- when I placed order under HQ Consultant 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#434]
Created account for bugornot@mailinator.com  
![image](https://user-images.githubusercontent.com/57115301/99691549-f7e92700-2a4e-11eb-8274-389799ea9a87.png)
Logged into my account and have one item in  my cart and I also selected my consultant as Kevin Mack ID# 188546 
![image](https://user-images.githubusercontent.com/57115301/99691667-1818e600-2a4f-11eb-81e9-32dd040d5279.png)
Then I logged out, and cleaned my cookies
![image](https://user-images.githubusercontent.com/57115301/99691757-2961f280-2a4f-11eb-8eab-e7428a0eba4f.png)
Then went back into my account and I see my item in my cart and that I'm not associated to any consultant (as expected cuz I cleaned cookies)  and I currently see I'm shopping with TS 160785 
![image](https://user-images.githubusercontent.com/57115301/99691910-557d7380-2a4f-11eb-8bdd-df8e41484cb8.png)
Placed my order BC # 1188 
![image](https://user-images.githubusercontent.com/57115301/99691956-60d09f00-2a4f-11eb-8b89-1afdbd3d6155.png)
Checked WebhookOrderNotification and see that I'm associated to Consultant ID 160785 
![image](https://user-images.githubusercontent.com/57115301/99692085-83fb4e80-2a4f-11eb-8066-d8f2ffcb3c4f.png)
Checked back after a few mins and see that now my order is associated with the consultant I had chosen earlier Kevin Mack id# 188546
![image](https://user-images.githubusercontent.com/57115301/99692201-a8572b00-2a4f-11eb-8dc2-3f6632d89807.png)
When I look here also see that its under Kevin as well 
![image](https://user-images.githubusercontent.com/57115301/99693099-9e81f780-2a50-11eb-891c-8ec0aabf0be3.png)

I'm thinking that if the client really wanted to not have it associated to any of our consultants- (that's why the clean their cookies), that it should stay under the TS Consultant 160785...... if they wanted a different consultant they would have selected that upon the process..

**Comment by TastefullySimple** [comment]
Updated to clear cart notification values. Previously is we got nothing we stopped without clearing the values.

**Comment by monicakarnes** [comment]
This fixed an now working... 

![image](https://user-images.githubusercontent.com/57115301/99722157-dc454700-2a75-11eb-80c4-ab66a6b0cd1a.png)
