### ISSUE TITLE
Party affiliation & cons photo in cart is incorrect

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#438]
### Expected behavior
The consultant selected in the banner should be the consultant affiliated to the party selected. 

### Actual behavior
The consultant photo and party that is displayed is associated to a different consultant that was is in the banner. 

### Steps to reproduce behavior
Sorry, all, this is the best I can do to remember how I got this to happen. This happened during the prod release today 11/20. So, this example is from Production. 
 I can't give you the exact steps though cause I was messing around way to much, but it went something like this. After verify the fundraiser name was displaying on the host planner and party details page for this party, https://www.tastefullysimple.com/p/11336459, I used the 'find a party' search to find a party that was a catalog party and for todays date to verify it on the attend tab - found party for Jamie Gall under CID#56230 Angie Dreher viewed the webpage. Then I was messing around in the join path to verify the pop ups, first the sign in then the sign up, I had chosen CID#32 in the join path, went all the way to checkout and clicked the TS logo to go to homepage, then viewed cart - and on the pop up clicked the 'i don't wish to join' at this time, cart is now empty, so did shop and added an item to my cart. When I got back to the cart I see that my consultant in the banner is Holly and it says I am shopping with Holly, CID#32 but the photo is Angie's CID#56230 and the party is still affiliated which is also Angies.
![image](https://user-images.githubusercontent.com/57115316/99840217-c1d0a380-2b31-11eb-81b9-36a1d29ef4a0.png)
![image](https://user-images.githubusercontent.com/57115316/99840230-c8f7b180-2b31-11eb-9e35-179d91ea59b6.png)

Angie Dreher CID#56230 is the consultant for Jamie Gall’s party
![image](https://user-images.githubusercontent.com/57115316/99840260-d57c0a00-2b31-11eb-84f3-584f78dce640.png)

**Comment by jsmnglng-w** [comment]
https://razoyo.atlassian.net/browse/TST-301

**Comment by TastefullySimple** [comment]
AB#225

**Comment by monicakarnes** [comment]
closing this is working in qa1 and prod
