### ISSUE TITLE
Join Release - APO/FPO & PR missing

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#44]
### Expected behavior
APO/FPO & PR should be options to select in the state dropdown when searching for a sponsor

### Actual behavior
APO/FPO & PR are missing from sponsor search state dropdown on tell us about yourself page
![image](https://user-images.githubusercontent.com/57953952/74044717-20f16d00-4991-11ea-8620-f495f1b4efef.png)

### Steps to reproduce behavior
Sign up for a join and when you get to step 2 to select a sponsor search for APO/FPO or PR.
Example:
![image](https://user-images.githubusercontent.com/57953952/74047948-cbb85a00-4996-11ea-8e8c-3919bfc88dc1.png)

**Comment by monicakarnes** [comment]
checked - done
