### ISSUE TITLE
 Mobile - Party Details link from party URL - Doesn't load keeps spinning 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#440]
Mobile- When you come to our site for the 1st time  and use a Party URL link  when it takes you to Welcome to My Party  Page to view the Party Details  

You can see it just spin and doesn't load the page 

![image](https://user-images.githubusercontent.com/57115301/99983541-9a681980-2d71-11eb-9ac9-6dd1b8111f39.png)

But if you look on the menu you can see the Consultant and the Party are affiliated to the account  
![image](https://user-images.githubusercontent.com/57115301/99983722-d602e380-2d71-11eb-9bbb-8f428add43a1.png)

Please updated so that this will display on Mobile when they get to the page

**Comment by jsmnglng-w** [comment]
Tried recreating the issue and it also happens in the Desktop. https://razoyo.atlassian.net/browse/TST-302

**Comment by jsmnglng-w** [comment]
@monicakarnes code changes are made in Shogun so this is ready for testing in Tech Sandbox

**Comment by monicakarnes** [comment]
tested on mobile phones- 
11pro max 
![image](https://user-images.githubusercontent.com/57115301/100007647-f93d8b00-2d91-11eb-904f-b20abdf64f24.png)
iphone 8 
![image](https://user-images.githubusercontent.com/57115301/100007670-03f82000-2d92-11eb-8cc6-ee7ca9fc738c.png)
iphone 7 
![image](https://user-images.githubusercontent.com/57115301/100007689-0ce8f180-2d92-11eb-99c0-feed961106a9.png)
iphone 6S 
![image](https://user-images.githubusercontent.com/57115301/100007724-17a38680-2d92-11eb-905a-d2b071b208ab.png)

Tested on Samsung 
SS10+ 
![image](https://user-images.githubusercontent.com/57115301/100007764-28ec9300-2d92-11eb-8dcb-94f78843d87f.png)
SS9 
![image](https://user-images.githubusercontent.com/57115301/100007805-3a359f80-2d92-11eb-8162-2923e6d1e5dc.png)
SS8 + 
![image](https://user-images.githubusercontent.com/57115301/100007840-44f03480-2d92-11eb-9d9b-2fa9389852c9.png)
SSS6 
![image](https://user-images.githubusercontent.com/57115301/100007873-533e5080-2d92-11eb-9246-abb2415fea9c.png)

Note I did also place orders on most of them and looks like orders are coming over an attaching to consultant and party as they should... wait for 2 more to download, but think we are good to close the bug  

 and also side note- I was not able to reproduce this on the desktop on our side
