### ISSUE TITLE
Clicking on view party in the green party bar does not display the party details. 

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#441]
### Expected behavior
When clicking the view party in the dropdown the client party details page should be displayed and all the details. 

### Actual behavior
When clicking on shop from an open party, then click view details from the green party dropdown not all the party details are displayed. 

### Steps to reproduce behavior
**PROD Example:** 
Need to have a consultant selected in the banner. 
Clicked on a closed party link and get to the 'darn this party is over page' https://www.tastefullysimple.com/p/11336459  (this link is from prod)
Parties are displayed under the 'attend & past' and click on 'shop for one of the open parties.
Click on the green party bar and click 'view party' and not all the party details are displayed. 
![image](https://user-images.githubusercontent.com/57115316/100022968-bc7d8e00-2da9-11eb-866a-46d70ac45d30.png)

**Comment by jsmnglng-w** [comment]
https://razoyo.atlassian.net/browse/TST-303
