### ISSUE TITLE
Party Link for deleted party brings user to the party details and allows order to be affiliated

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#446]
### Expected behavior
If the party is deleted or closed, the link should display this party has been closed message. 

### Actual behavior
Following a link for a closed party displays the client party details page and allows the user to attach an order to the party. 

### Steps to reproduce behavior
Set up a party in myHQ
![image](https://user-images.githubusercontent.com/57115316/100252922-15facf80-2f06-11eb-9ec6-a17890b6aeed.png)
![image](https://user-images.githubusercontent.com/57115316/100252948-1f843780-2f06-11eb-82e7-de2cf314bd2d.png)
Verified I could get to the party details page in TS.com
![image](https://user-images.githubusercontent.com/57115316/100253028-39257f00-2f06-11eb-81cc-0d3547139816.png)
I then deleted the party in myHQ and copied the URL into my browser again and I am still able to get to the party details page: 
![image](https://user-images.githubusercontent.com/57115316/100253105-535f5d00-2f06-11eb-9023-7be20399f7e3.png)
Site allows me to proceed and checkout with the order and affiliate it to the deleted party: 
![image](https://user-images.githubusercontent.com/57115316/100253166-64a86980-2f06-11eb-9273-344f39b0accb.png)
![image](https://user-images.githubusercontent.com/57115316/100253340-96b9cb80-2f06-11eb-8d2b-993f7adffef8.png)

![image](https://user-images.githubusercontent.com/57115316/100253379-a6391480-2f06-11eb-813a-86adc2f01d1a.png)

**Comment by jsmnglng-w** [comment]
@suehamre calling the party details API, the API shows that **PID#10370843** is not closed
![Screen Shot 2020-11-25 at 10 24 26 AM](https://user-images.githubusercontent.com/69249028/100255032-a803d780-2f08-11eb-9d8c-9147e2fab422.png)

**Comment by suehamre** [comment]
@jsmnglng-w , I suppose not because I deleted it. @TastefullySimple  - Do we need to update the API to have 'is closed or 'deleted'?

**Comment by suehamre** [comment]
AB#223

**Comment by monicakarnes** [comment]
Set up my party for Kevin Mack    https://tastefully-simple-sandbox-2.mybigcommerce.com/p/10370844
![image](https://user-images.githubusercontent.com/57115301/100914415-a43bfc00-3498-11eb-9d2c-9b2fafebbbb7.png)

Currently can't get to view party details page I get Darn this party is over  even thought is shown on my attend parties section
![image](https://user-images.githubusercontent.com/57115301/100914852-38a65e80-3499-11eb-8753-1344a6c90482.png)

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/100914963-612e5880-3499-11eb-9997-1aa3acff88df.png)
will have to wait until bug 448 gets fixed 1st to check this one then

**Comment by monicakarnes** [comment]
This is already fixed and in prod. Closing
