### ISSUE TITLE
Party Dates updated to current dates- After being in the Past - Not able to get Party details page

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#448]
### Expected behavior
If the party date has been updated to reflect a new date the party should display in the Attend section of the my parties with the updated information. The party should have the shop available to shop with this party. If they click the shop the Green party bar should be updated with the Host's information. If they click to view the party details for this party that information should display. 

### Actual behavior
When I click in the party bar to view the party details information. I am then taken to the Darn this party is closed page and am not able to see the details for the party 

![image](https://user-images.githubusercontent.com/57115301/100911400-c764ac80-3494-11eb-9f97-b034f8794d5a.png)

![image](https://user-images.githubusercontent.com/57115301/100911439-d64b5f00-3494-11eb-8df8-fae3f50fca0e.png)

### Steps to reproduce behavior
So I had parties set up in myhq these party dates all had party dates for November, which now is all past. So I went into myhq and updated the party dates to reflect this month of December.  And now when I try to view my parties I'm not able to see the party details for these parties.. 

My consultant ID # 2051
Here is the list of parties that were updated to December dates 
![image](https://user-images.githubusercontent.com/57115301/100911729-380bc900-3495-11eb-82ad-1de05a917065.png)

![image](https://user-images.githubusercontent.com/57115301/100911838-58d41e80-3495-11eb-8a52-03c70b5b6d98.png)

**Comment by jsmnglng-w** [comment]
@monicakarnes this looks like an API issue. I'm getting a Bad Request response coming from the API every time I go to the party details page. @TastefullySimple did anything change in the Party Details API? I'm fetching `https://qa1-tsapi.tastefullysimple.com/party/detail?pid={pid}`

Example:
Fetching `https://qa1-tsapi.tastefullysimple.com/party/detail?pid=10370822` gives me:
![Screen Shot 2020-12-02 at 12 43 42 PM](https://user-images.githubusercontent.com/69249028/100917268-88d2f000-349c-11eb-9ee1-c4a01da6ff38.png)

**Comment by monicakarnes** [comment]
I'm also seeing this on other parties I've attempted to view the party details for as well for parties I just set up

**Comment by TastefullySimple** [comment]
The bug with TSAPI has been fixed and published to QA1.

**Comment by monicakarnes** [comment]
Looks like this is fixed I'm able to get to my parties now and see the party details page  THANKS! closing bug 

![image](https://user-images.githubusercontent.com/57115301/101181530-9b6f3580-3612-11eb-90e0-b73412a6684a.png)
