### ISSUE TITLE
Join Release - Shipping is the same as billing checkbox errors

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#45]
### Expected behavior
When you leave the box checked for my shipping is the same as billing you should be able to proceed to the next page.

### Actual behavior
When you leave the box checked for my shipping is the same as billing, and receive error messages to enter address and cannot proceed. If you uncheck the box, the fields appear - do nothing and recheck the box try to check out – still no go – then uncheck the box again – now the fields are gone.

![image](https://user-images.githubusercontent.com/57953952/74047028-4aac9300-4995-11ea-8121-e076352caf17.png)
 

### Steps to reproduce behavior
Enter all of your personal information and leave the box checked for my shipping is the same as billing and click checkout.

**Comment by suehamre** [comment]
2-7 SH - Fixed. :)
