### ISSUE TITLE
Past Consultants unable to join - getting Please Provide an ID messag

### ISSUE THREAD

**Issue by kcarpenterTS** [tastefully-simple/cornerstone#450]
### Expected behavior
Past (inactive) consultant is able to join on TS.com as long as her Financial and Compliance Statuses are okay in Prowess. 
![image](https://user-images.githubusercontent.com/42840281/101412967-13ef2400-38a9-11eb-85ab-77e1d6f86832.png)

### Actual behavior
Past Consultant receives message to Please Provide an ID and to contact Customer Service. 
![image](https://user-images.githubusercontent.com/42840281/101413452-ec4c8b80-38a9-11eb-8ae1-612f67c5d132.png)

### Steps to reproduce behavior
I have not been able to get this to reproduce myself but Customer Service Technology was able to when they were helping the two past consultants that were trying to sign up.  I've tried with others and it allows me to proceed.  Steps CSTS Took:

1. Go to tastefullysimple.com
2. Click Join
3. Click Join Today
4. Log in using email address and password associated with previous consultant record
5. Enter Personal information
6. Select Answer to question at bottom about money
7. Search for Sponsor
8. Check Agreement box 
9. Click Checkout button

**Comment by suehamre** [comment]
The error messages were updated with the 1/4/21 Join release and this is no longer displaying.
