### ISSUE TITLE
Join Release - My mobile is my primary checkbox issue

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#46]
### Expected behavior
The client should not have to give out their mobile number if they choose not to. We would like to change the verbiage on these boxes to make it more clear.

Change:
Mobile Phone Number > Primary Phone Number
My mobile number is my primary checkbox > My primary is my mobile number
Primary Phone > Secondary Phone Number

### Actual behavior
If you only put a phone number in the primary phone field you will get an error.
![image](https://user-images.githubusercontent.com/57953952/74048314-995b2c80-4997-11ea-9f2e-c10a581d2326.png)

**Comment by suehamre** [comment]
2-7-20 SH - I was able to get through without a mobile phone number and only a primary phone. The data saved correctly.  We feel there is no longer a need for the UI changes. Closing bug. IF someone disagrees, please reopen.
