### ISSUE TITLE
Join Release - Tell Us About Yourself - Billing/Shipping drop down - No APO/FPO/PR

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#47]
### Expected behavior
APO/FPO/PR should be options to choose on the billing/shipping drop down on the tell us about yourself page.

### Actual behavior
APO/FPO/PR are not options to choose.

Tell Us About Yourself Page
![image](https://user-images.githubusercontent.com/57953952/74048673-49c93080-4998-11ea-91e5-2db15ce139e9.png)
Big Commerce Cart for reference
![image](https://user-images.githubusercontent.com/57953952/74048723-606f8780-4998-11ea-9b7e-86db8d890d83.png)
![image](https://user-images.githubusercontent.com/57953952/74048759-72512a80-4998-11ea-87b5-56cec372ea16.png)

### Steps to reproduce behavior
Sign up or log in > on the tell us about yourself page click the state dropdown on the billing and shipping sections.

**Comment by monicakarnes** [comment]
checked done
