### ISSUE TITLE
Join Release - Confetti animation is not working on the confirmation page

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#48]
### Expected behavior
It is supposed to look like confetti is flying. Sue is not seeing it when completing joins in Chrome.

### Actual behavior
The animation does not happen. It works when you paste the link in but not when you go through the path.

### Steps to reproduce behavior
Go through the join process and when you hit the welcome page the confetti will look like it is flying.

https://tastefully-simple-sandbox-2.mybigcommerce.com/welcome/

**Comment by suehamre** [comment]
SH - I see the confetti now! :)
