### ISSUE TITLE
Join Release - Congratulations page - lower Customer Service info

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#49]
### Expected behavior
The link will open an email provider window

### Actual behavior
https://tastefully-simple-sandbox-2.mybigcommerce.com/welcome/

On this page when Denise clicks on the help@tastefullysimple.com link

The screen refreshes to the Congratulations page again instead of outlook to send an email.
![image](https://user-images.githubusercontent.com/57953952/74066104-113b4e00-49bc-11ea-8008-0834b13a3858.png)

### Steps to reproduce behavior
Go through the join process until you get to the welcome page.

**Comment by monicakarnes** [comment]
checked- done
