### ISSUE TITLE
Join Release - Buy Now - issue after finding consultant

### ISSUE THREAD

**Issue by mandi920** [tastefully-simple/cornerstone#50]
### Expected behavior
Per Denise:
Using the QA1 buy now link -

https://tastefully-simple-sandbox-2.mybigcommerce.com/cart.php?action=add&sku=150440&source=buy_button

I wanted to test a scenario and noticed that after I click change for my consultant on the cart screen - then find a consultant by ID number – and click on the Shop now link for this consultant – I am taken to the checkout page instead of the cart page where I can see my item and the consultant change in the lower part of the cart.

tested this same scenario in Prod – buy now.

https://shoptastefullysimple.com/cart.php?affiliate_action=add&sku=150300&source=buy_button

And after completing the search we are taken back to the cart as expected-  something has broken it in QA1.  (not sure if it was any join builds)

### Steps to reproduce behavior
Per Denise:
Using the QA1 buy now link -

https://tastefully-simple-sandbox-2.mybigcommerce.com/cart.php?action=add&sku=150440&source=buy_button

I wanted to test a scenario and noticed that after I click change for my consultant on the cart screen - then find a consultant by ID number – and click on the Shop now link for this consultant – I am taken to the checkout page instead of the cart page where I can see my item and the consultant change in the lower part of the cart.

**Comment by monicakarnes** [comment]
checked- done
