### ISSUE TITLE
Shipping address same as billing checkbox - checking and unchecking gets hosed

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#51]
### Expected behavior
 - Shipping information boxes should always appear for info to be entered if the box for same as billing is unchecked. 

### Actual behavior
 - If you uncheck the box, the recheck, then uncheck again the boxes disappear. 

### Steps to reproduce behavior
 - Unselect the checkbox for 'my shipping is the same as billing', reselect it, and unselect again, boxes disappear. Then check again, and not able to proceed past the page.

**Comment by TastefullySimple** [comment]
Textboxes are not delete. Corrected code to clear the fields.

**Comment by monicakarnes** [comment]
checked- done
