### ISSUE TITLE
What comes in your kit

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#69]
### Expected behavior
verbiage for the progress bar and under the image of the BBOK should be: What comes in your kit

### Actual behavior 
What Comes in Your Kit? is listed under the image still 

### Steps to reproduce behavior
I see the Progress bar has been updated. 
![image](https://user-images.githubusercontent.com/57115301/75916783-903a6f80-5e1e-11ea-9ddd-3c144fd6c94c.png)

Under the image of the BBOK- there is also a statement that needs to be updated as well 
What comes in your kit 

Currently you see this, 
![image](https://user-images.githubusercontent.com/57115301/75916817-9e888b80-5e1e-11ea-943f-5037576e40fa.png)

**Comment by monicakarnes** [comment]
I noticed that we now have it listed an extra time in qa1 - What Comes in Your Kit-  We need to removed the black lettering - then it will be all fixed. 
![image](https://user-images.githubusercontent.com/57115301/76340006-ded98500-62c8-11ea-9171-e65cf00c5cf3.png)

Here is what prod currently looks like- 
![image](https://user-images.githubusercontent.com/57115301/76340062-f6b10900-62c8-11ea-87a3-a7e96d4bc864.png)

**Comment by TastefullySimple** [comment]
Removed extra heading.

**Comment by monicakarnes** [comment]
fixed- closing
