### ISSUE TITLE
Grey/Spinner needed for delay time from Ready to Join to Whats in your kit

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#74]
### Expected behavior
When the client is logged into TS.com as a registered user, and the click to Join Us, and clicks to Get Started they should be taken directly to the Whats in your kit page. 

I am wondering if we can either gray out the page with an overlay, or create a spinner to show its thinking before they are taken to the Whats in your kit page. 

### Actual behavior
They click to Get Started, and briefly see the Ready to Join-Login/Sign up page before being taken to the Whats in your kit page.

![token ready to join page](https://user-images.githubusercontent.com/57115301/76357697-29b5c580-62e6-11ea-909b-ffcd7643d554.gif)

### Steps to reproduce behavior
Client goes to TS.com and logs in as Registered user
Client clicks on JoinUs
Client clicks on Get Started
Client sees Ready to Join- Login/Sign up page.

**Comment by monicakarnes** [comment]
Fixed- closing bug

**Comment by monicakarnes** [comment]
Feels like this grayed out time has shrunk with this last change you made it isn't long enough now. 
![Grayed out screen time increase ](https://user-images.githubusercontent.com/57115301/76557862-4ed34100-646a-11ea-8074-93601c62caf1.gif)

**Comment by TastefullySimple** [comment]
Added a delay

**Comment by monicakarnes** [comment]
Thanks that is better, closing bug
