### ISSUE TITLE
Display of the items that comes in your kit

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#75]
### Expected behavior
The display of the items in the kit should be the same as they are in prod. 
They are listed out side by side.

![image](https://user-images.githubusercontent.com/57115301/76358040-cd9f7100-62e6-11ea-85da-8f755ad044e5.png)

### Actual behavior
I now see the items in the kit listed in one long line.

![image](https://user-images.githubusercontent.com/57115301/76358111-ee67c680-62e6-11ea-8c0e-8101537fce18.png)

### Steps to reproduce behavior
Client goes to TS.com- client logged in as Registered user
Client clicked to Join Us
Client clicked Get Started
Client sees the What comes in your kit page

**Comment by TastefullySimple** [comment]
Fixed layout.

**Comment by monicakarnes** [comment]
fixed- closing
