### ISSUE TITLE
Registered TSO client- Doesn't populate information- Via Sign Up

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#76]
### Expected behavior
If the client is a registered user and is not logged in, and goes through the login or sign up page with their existing TS.com account information the system should recognize that they have an account and pre-populate the saved information from their profile. This includes:
First Name
Last Name
Email address
Shipping address line one
Shipping address line 2
Shipping City
Shipping State
Shipping Zip Code
Primary Phone Number
'My Primary is my mobile'
Mobile Phone Number
Billing address line 1
Billing address line 2
Billing address city
Billing address state
Billing address zip code

here is my client info 
![image](https://user-images.githubusercontent.com/57115301/76439182-03496600-638a-11ea-8a71-e0a29632f976.png)

### Actual behavior
When the client gets to the Tells us about yourself page no information is pre-populated. 

![image](https://user-images.githubusercontent.com/57115301/76439375-4efc0f80-638a-11ea-894c-aca972978468.png)

![image](https://user-images.githubusercontent.com/57115301/76439433-63400c80-638a-11ea-95ea-0da338e54e03.png)

### Steps to reproduce behavior
Client goes to TS.com
Client clicks on JoinUs
Client clicks on Get Started
Client clicks on Sign up
Client enters is 1st name
Client enters last name
Client enters in email address
Client enters password
Client retypes password
Client clicks on next 
Client sees Whats in your kit page
Client clicks next
Client is taken to the Tell us about your self page
Client should see pre-populated information from TS.com Profile---- but it is blank.

**Comment by monicakarnes** [comment]
Sorry I should have included the email address I used for TSO registered account- 
grillman@mailinator.com
Password = Beerbread1!

**Comment by TastefullySimple** [comment]
Closing as this is building a sitecore TSO login into big commerce.
