### ISSUE TITLE
Billing & Shipping address different on TS.com Profile---Coming over as the SAME checkbox

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#77]
### Expected behavior
If the client is a Registered User on TS.com and logged in, then clicks to Join Us and clicks to get Started, and when they get to the Tell us about you personal information page their TS.com Profile information comes over, if the Billing & Shipping address are different, the Billing Address should be listed and the Shipping Address should be listed and the checkbox- Shipping Address Same as Billing should not be selected. 

### Actual behavior

The TS.com profile information is coming over, but the Billing Address is displayed 
The Checkbox - Shipping Address is Same as Billing is actually checked - and shouldn't be due to the different addresses. 

![image](https://user-images.githubusercontent.com/57115301/76461597-3140a180-63ae-11ea-97a1-588df3a23e33.png)

If you unclick the checkbox- Shipping Address is Same as Billing, you can see that the information is actually populating correctly.  

![image](https://user-images.githubusercontent.com/57115301/76461769-811f6880-63ae-11ea-9718-ab45f9be1ee6.png)

### Steps to reproduce behavior
Go to TS.com
Log in to Registered TS.com account     mtdew@mailinator.com password = Beerbread1!
Click to Join Us
Click to Get Started
Client taken to Whats in your kit page
Client clicks next
Client taken to Tell us about you- personal info page
Client sees details from the TS.com profile
Client sees that the Billing information is listed
Client sees that it show the check box selected for Shipping address is the same (when its not) 
Client can uncheck the check box to see the correct Shipping Address listed.

**Comment by TastefullySimple** [comment]
The is ready for testing in the Tech Sandbox.

**Comment by monicakarnes** [comment]
Just checked this, and I'm not seeing the change. The box is still checked, and it shouldn't be as the addresses are different, and the shipping address is not expanded to see the address.

**Comment by TastefullySimple** [comment]
The is ready for testing in the Tech Sandbox.

**Comment by monicakarnes** [comment]
fixed, closing
