### ISSUE TITLE
Discount that is displaying that she got a client promotion discount of $99.99 on BBOK order & Error

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#82]
### Expected behavior
There should NOT be a client promotion discount show for the amount of $99.99 on the BBOK
Also should NOT be an error showing when trying to access the details of the order for the BBOK
### Actual behavior
There is a client promotion discount showing for the amount of $99.99 on the BBOK
There is a Compilation Error when trying to view the order details through the clients TS.com account.
### Steps to reproduce behavior

3-11-20- Getting Compilation Error.  sounds like its more than just this new join order, getting the error during check out process- Sue just tried to place an order via TSO and get the error on the checkout confirmation page, but sees the order in TSN #  26908662 - 

Went to TS.com logged into registered account, Went  to JoinUs, Get Started- had some info pre-populated, Completed the rest and continued through the process to complete the agreement. Once the agreement process was completed. 

I logged out of TS.com- cleaned cookies- 

Went back to TS.com- logged into my account- rain@mailinator.com  password = Beerbread1!

Went to Order history-  and clicked into the order- 26908661 to see if I can see the client promotion discount.... but I get a error shown below. 

![image](https://user-images.githubusercontent.com/57115301/77104138-83ef0e80-69e9-11ea-9672-6a23ad5420b6.png)

 
![image](https://user-images.githubusercontent.com/57115301/77104159-8f423a00-69e9-11ea-8695-97b57e5ef866.png)

3-9-2020: Hide client promotion and p1 subtotal.

![image](https://user-images.githubusercontent.com/57115301/77104193-9f5a1980-69e9-11ea-946f-9b2ad1ec763c.png)

Joined new consultant via new join path.  Eva Smith ID 188821 

Went to TS.com and logged into her account-  eva.smith@mailinator.com     Password123

When you click into her profile, then click on orders- and click into view her BBOK order which is order # 26908603 – you can see that there is a discount that is displaying that she got a client promotion discount of $99.99 ---- Luckily you can see it didn’t effect the bottom line total… but it can still be confusing to the client. 

![image](https://user-images.githubusercontent.com/57115301/77104220-ac770880-69e9-11ea-8391-1c90b5c7c4fa.png)

**Comment by mandi920** [comment]
Closing this due to Sitecore TSO no longer being active.
