### ISSUE TITLE
Error messages & Text Boxes   do not match which can be confusing 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#83]
### Expected behavior
If you receive an error message, there should be a Text box named the same thing so you know which box you need to update. 

### Actual behavior
You do receive error message, but they are not the same as the text boxes. 
Here is the text boxes:

•	Prefix
•	Preferred Name
•	First Name
•	Last Name
•	Social Security
•	Date of Birth
•	Mobile phone number
•	Primary phone 
•	Billing Address
•	Billing City
•	Billing Zip Code
•	Shipping Address
•	Shipping City
•	Shipping Zip Code
•	How will you be using your TS cash
•	Select your Sponsor
•	Independent Consultant Agreement Terms & Conditions 

Here is the error messages
![image](https://user-images.githubusercontent.com/57115301/77107031-0e397180-69ee-11ea-9d06-cb42f16bf021.png)

Here is the error messages:

•  Please select your preferred title.
•  Please enter your legal name.
•  Please enter your last name.
•  Please enter your Social Security Number.
•  Please enter your birth date.
•  Please enter a valid primary phone number.
•  Please enter a billing street address.
•  Please enter your billing address city.
•  Please select enter billing zip code.
•  Please enter a shipping street address.
•  Please enter your shipping address city.
•  Please enter your shipping zip code.
•  Please indicate how you will be using your TS cash.
•  Please select a sponsor.
•  Please check the box above to indicate that you accept the Terms and Conditions.

### Steps to reproduce behavior
Go to TS.com
Go to Get Started
Enter details for log in or sign up
Go to whats in your kit click next
Go to Tell us about yourself page click on check out to receive the error messages

**Comment by TastefullySimple** [comment]
@monicakarnes Please condense the bug down to the messages that are incorrect.

**Comment by monicakarnes** [comment]
Here you go maybe this is better :)  Please Update the information in Red coloring for both the text boxes and the error messages.  Thank you! 

![image](https://user-images.githubusercontent.com/57115301/77192936-5ff40180-6aab-11ea-9ae1-41d18b1abc06.png)

**Comment by TastefullySimple** [comment]
This is ready for testing.

**Comment by monicakarnes** [comment]
![image](https://user-images.githubusercontent.com/57115301/78942914-4e859000-7a80-11ea-9fc4-442810f0bd9a.png)

![image](https://user-images.githubusercontent.com/57115301/78942975-6f4de580-7a80-11ea-9988-2e44683b7000.png)


I have not entered anything on this page as of yet... and when click to check out to view the errors I get this error instead.....

**Comment by TastefullySimple** [comment]
This one is ready for testing again.

**Comment by monicakarnes** [comment]
Thanks for fixing the error I was receiving above- 

We still have a couple little fixes for the verbiage ---- Ignore the blue underline- that was from my copy and pasting....   Please fix the items high-lighted in yellow. 
![image](https://user-images.githubusercontent.com/57115301/79008857-e2f4fe80-7b23-11ea-9e9f-94fb9de83748.png)

Please enter your First Name
Please enter a valid Primary Phone Number
Please check the box above to indicate that you accept the Independent Consultant Agreement Terms and Conditions.

**Comment by monicakarnes** [comment]
This has been fixed, closing bug. 
![image](https://user-images.githubusercontent.com/57115301/79138463-29dc3180-7d7a-11ea-965c-18f865f1eb0c.png)
