### ISSUE TITLE
Can't Complete a JOIN---- Asks for primary phone one when I already entered, one or I selected my mobile is my primary

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#84]
### Expected behavior
When you enter your  Mobile Phone number, you should be able have is also as your Primary Phone number.  Or if you Choose to enter a Primary Phone that is different from your Mobile Phone you should be able to continue through the join process and complete the agreement, to move to check out page.  

### Actual behavior
It is not allowing me to enter a primary number other than mobile and proceed. 

![image](https://user-images.githubusercontent.com/57115301/78944168-e71d0f80-7a82-11ea-89f8-3b0b34bf0e8d.png)

Doesn't allow me to have my mobile as my primary

![image](https://user-images.githubusercontent.com/57115301/78944240-103da000-7a83-11ea-858f-29ddcccdefd8.png)

### Steps to reproduce behavior
TS.com
click on Join Us
Click on Get Started
Click on Sign up, enter 1st name, last name, email address, password, re-enter password click next
On what comes in my kit page, click on next
On Personal information page, start to enter in your details. 
On the mobile phone number field - enter number, and continued to fill in my address and select my sponsor. 
Then clicked to check out and received error. 

Same happens if you enter in a mobile phone, and then enter a different primary phone number. You receive the same error about entering in a primary phone number.

**Comment by TastefullySimple** [comment]
This is ready for testing.

**Comment by monicakarnes** [comment]
this is fixed- closing bug
