### ISSUE TITLE
Confirmation page- spelling error it says 'algo' and should be 'also'

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#86]
### Expected behavior
On the confirmation page- after completing your agreement. 
number 2 Get Cash- in the second sub bullet- 1st line  it should read the following:

Through Propay, you also get paid! 

### Actual behavior
Through Propay, you algo get paid! 

![image](https://user-images.githubusercontent.com/57115301/79128097-90585400-7d68-11ea-9f16-a400d48ec005.png)

### Steps to reproduce behavior
Click to Join us on TS.com
Click to get Get Started
Click to Sign up, enter in 1st name, last name, email address, password, re-enter password. click next
What comes in your kit page, click next
Tell us about you page enter in details then
Continue and enter billing& shipping details,
Continue and enter sponsor,
Agree to T & C
click check out
Complete the details for checkout and agreement to receive confirmation page. 
Review details on Number 2 Get Cash to view spelling error.

**Comment by TastefullySimple** [comment]
Look like the typo was in the User Story 
https://tsrelaunchtest.atlassian.net/browse/P1R-131

**Comment by monicakarnes** [comment]
fixed, closing bug
![image](https://user-images.githubusercontent.com/57115301/79150079-c5c36880-7d8d-11ea-9c6b-35151c7f577e.png)
