### ISSUE TITLE
APO - ground & rush processing bug

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#9]
### Expected behavior
The cart should update according to the selections you make 

### Actual behavior
The cart shipping & processing fees are not updating in the cart after changes

### Steps to reproduce behavior

Adding attachment with details and screen shots
[APO- ground & rush processing bug.docx](https://github.com/tastefully-simple/cornerstone/files/3805951/APO-.ground.rush.processing.bug.docx)

**Comment by Denise219** [comment]
Changes were made - retested and passed  - closing bug.
