### ISSUE TITLE
Credit- Total displayed in TSN order history and myHQ order history columns - not reflecting shipping refund 

### ISSUE THREAD

**Issue by monicakarnes** [tastefully-simple/cornerstone#91]
### Expected behavior
The total amount for shipping, being refunded back should be included in the total amount of the refund.

### Actual behavior
It is only displaying P1 total, and is excluding the shipping portion. here is myhq view
![image](https://user-images.githubusercontent.com/57115301/79511095-396eab00-8004-11ea-8a30-6247131e9da2.png)

here is tsn view-
![image](https://user-images.githubusercontent.com/57115301/79511160-5b682d80-8004-11ea-8a69-b3e92cd618e6.png)

### What needs to change###
So again the credit Total that I should see here should be the same as the original ($167.99) 
As this was a full credit order, so I get all of the shipping charges back.  

Note- that if it was a partial credit, then you would get no shipping back, so it would be right-

**Comment by Denise219** [comment]
4/22 Still broken -placed new order.
TSN view:
![image](https://user-images.githubusercontent.com/57686045/80033877-0ec49c80-84b3-11ea-9589-1f6d5c5b1641.png)

myHQ view:
![image](https://user-images.githubusercontent.com/57686045/80034023-4f241a80-84b3-11ea-8e8f-aa2dbefd13b9.png)

**Comment by Denise219** [comment]
Totals match - closing.
![image](https://user-images.githubusercontent.com/57686045/80236241-7a784800-8620-11ea-9ed7-d41a75e172f1.png)

![image](https://user-images.githubusercontent.com/57686045/80236270-895efa80-8620-11ea-8169-46eae7023c15.png)
