### ISSUE TITLE
Credit - shipping applied to credit order for partial shipment

### ISSUE THREAD

**Issue by Denise219** [tastefully-simple/cornerstone#93]
Hi SteveO,

This might tie into the other bugs but I wanted to call out this specific scenario.
Maybe when you fix the bug about both kits being credited instead of one this will get fixed with that.  BUG# 92

BIC C order 670 - order was for 2 buy now kits.
I elected to refund 1 kit  - there should not have been any shipping credit applied to the credit order.
When the credit order # 26914693 was created there was shipping credit amount applied.

Thanks!

**Comment by Denise219** [comment]
4/22 still broken
Placed a new BC order # 695
Order had two buy now kits.
Refunded one kit.

When the credit order # 26915921 was created  - it appears that shipping is being applied for credit.
![image](https://user-images.githubusercontent.com/57686045/80036452-5c430880-84b7-11ea-9f11-073407cb0f78.png)

![image](https://user-images.githubusercontent.com/57686045/80036479-69f88e00-84b7-11ea-9b75-7f4cb454156a.png)

When a refund is processed for partial order no shipping credit should be applied.

**Comment by Denise219** [comment]
Still broken

**Comment by monicakarnes** [comment]
[Retesting #92.docx](https://github.com/tastefully-simple/cornerstone/files/4566015/Retesting.92.docx)


This is fixed with closing #92 ... so closing this out as well
