### ISSUE TITLE
Credit  - SQL log variances

### ISSUE THREAD

**Issue by Denise219** [tastefully-simple/cornerstone#98]
Used this query
USE TSOnline_TransactionsOME
GO

DECLARE @OrderID INT
       , @OrderGroupNumber INT
       , @OrderNumber INT
       , @CreditOrderGroupNumber INT
       , @CrecitOrderNumber INT

SET @OrderID = 699

SELECT @OrderGroupNumber = x.OrderGroupNumber, @OrderNumber = x.OrderNumber, @CreditOrderGroupNumber = c.CreditOrderGroupNumber
       , @CrecitOrderNumber = c.CreditOrderNumber FROM TSApplications.bcom.Credits c
JOIN TSApplications.eoi.OrderImportSourceXref x ON x.SourceOrderID = CONVERT(VARCHAR(50),c.OrderID)
WHERE OrderID  = @OrderID

SELECT @OrderID OrderID, @OrderGroupNumber OrderGroupNumber, @OrderNumber OrderNumber, @CreditOrderGroupNumber CreditOrderGroupNumber
       , @CrecitOrderNumber CrecitOrderNumber

SELECT 'Group' [Table], * FROM TSOnline_TransactionsOME.dbo.OrderGroup
WHERE OrderGroupNumber IN (@OrderGroupNumber, @CreditOrderGroupNumber)
ORDER BY OrderGroupNumber DESC

SELECT 'Form' [Table], * FROM TSOnline_TransactionsOME.dbo.OrderForm
WHERE OrderNumber IN (@OrderNumber, @CrecitOrderNumber)
ORDER BY OrderGroupNumber DESC

SELECT 'Line' [Table],  * FROM TSOnline_TransactionsOME.dbo.OrderFormLineItem
WHERE OrderNumber IN (@OrderNumber, @CrecitOrderNumber)
ORDER BY LineItemID, OrderGroupNumber DESC

SELECT 'Discount' [Table], * FROM DBA_Scratch.dbo.OrderLineDiscount
WHERE OrderGroupNumber IN (@OrderGroupNumber, @CreditOrderGroupNumber)
ORDER BY OrderGroupNumber DESC

SELECT 'Address' [Table], a.* FROM TSOnline_TransactionsOME.dbo.OrderForm o
JOIN TSOnline_TransactionsOME.dbo.OrderAddress a ON a.OrderGroupNumber = o.OrderGroupNumber
       AND (a.AddressType = 2 OR a.AddressID = o.ShipToAddressID OR a.AddressID = o.RecipientAddressID)
WHERE OrderNumber IN (@OrderNumber, @CrecitOrderNumber)
ORDER BY OrderGroupNumber DESC, AddressType

SELECT 'Shipment' [Table], * FROM TSOnline_TransactionsOME.dbo.Shipment
WHERE OrderGroupNumber IN (@OrderGroupNumber, @CreditOrderGroupNumber)
ORDER BY OrderGroupNumber DESC

Double check the this:
![image](https://user-images.githubusercontent.com/57686045/80236802-4ea99200-8621-11ea-9b54-1181c64e3ffa.png)

Client shipping:
![image](https://user-images.githubusercontent.com/57686045/80236936-7dc00380-8621-11ea-817c-aaa417aca2b9.png)

Eva Jones is the consultant and Ethan Lars is the client  should the credit order have the client name also?
![image](https://user-images.githubusercontent.com/57686045/80237054-b1029280-8621-11ea-82bf-d8810143fb0e.png)

Total line items are different:
![image](https://user-images.githubusercontent.com/57686045/80237172-e4452180-8621-11ea-9820-3847650cca38.png)

posting this here for FYI based on conversation with Steve-  TSINet should be Zero for credit.  
![image](https://user-images.githubusercontent.com/57686045/80237288-1ce4fb00-8622-11ea-8466-db62869d00c3.png)

**Comment by sevincent** [comment]
PartOneTaxableAmount
Looking at production orders, I don’t see any examples where the original order had a PartOneTaxableAmount where the credit had a value other than zero. Just continuing that tradition.

ClientShipping
This was a bug. Should have been fixed with Issue #93.

UserFirstName, UserLastName
Fixed

Total line items are different:
Fixed

TSINet
Zero on all existing credits.

**Comment by monicakarnes** [comment]
looked at order 711 

part one taxable amount is how he left it
![image](https://user-images.githubusercontent.com/57115301/81235804-6db10800-8fc1-11ea-8491-ef5677b2ac30.png)


Client shipping I had issued back 3.99 so this is correct
![image](https://user-images.githubusercontent.com/57115301/81235730-41958700-8fc1-11ea-82cd-dc63050f0b04.png)

User first name and user last name are the same 
![image](https://user-images.githubusercontent.com/57115301/81235977-c2ed1980-8fc1-11ea-901f-4384d1c4ab2e.png)

total line items are same 
![image](https://user-images.githubusercontent.com/57115301/81236008-dc8e6100-8fc1-11ea-8543-726ab52b4a15.png)

TSINet still shows correct at zero
![image](https://user-images.githubusercontent.com/57115301/81236069-ffb91080-8fc1-11ea-8bd4-ed0752159615.png)


Closing bug
